/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "Demux_1x2_8Bits_estructural.v:1.1-49.10" *)
module Demux_1x2_8Bits_estructural(In, clk4, clk2, clk, validIn, outValid0_estructural, outValid1_estructural, data_out0_estructural, data_out1_estructural);
  (* src = "Demux_1x2_8Bits_estructural.v:2.21-2.23" *)
  input [7:0] In;
  (* src = "Demux_1x2_8Bits_estructural.v:9.39-9.51" *)
  reg [7:0] ValorFuturo0;
  (* src = "Demux_1x2_8Bits_estructural.v:3.27-3.30" *)
  input clk;
  (* src = "Demux_1x2_8Bits_estructural.v:3.21-3.25" *)
  input clk2;
  (* src = "Demux_1x2_8Bits_estructural.v:3.15-3.19" *)
  input clk4;
  (* src = "Demux_1x2_8Bits_estructural.v:5.26-5.46" *)
  output [7:0] data_out0_estructural;
  reg [7:0] data_out0_estructural;
  (* src = "Demux_1x2_8Bits_estructural.v:5.47-5.67" *)
  output [7:0] data_out1_estructural;
  reg [7:0] data_out1_estructural;
  (* src = "Demux_1x2_8Bits_estructural.v:4.20-4.40" *)
  output outValid0_estructural;
  reg outValid0_estructural;
  (* src = "Demux_1x2_8Bits_estructural.v:4.42-4.62" *)
  output outValid1_estructural;
  reg outValid1_estructural;
  (* src = "Demux_1x2_8Bits_estructural.v:13.13-13.21" *)
  reg selector = 1'h0;
  (* src = "Demux_1x2_8Bits_estructural.v:3.32-3.39" *)
  input validIn;
  (* src = "Demux_1x2_8Bits_estructural.v:11.14-11.26" *)
  reg validTemp_In;
  (* src = "Demux_1x2_8Bits_estructural.v:12.14-12.27" *)
  reg validTemp_In1;
  (* src = "Demux_1x2_8Bits_estructural.v:16.9-28.12" *)
  always @(posedge clk4)
    if (selector) validTemp_In <= validIn;
  (* src = "Demux_1x2_8Bits_estructural.v:16.9-28.12" *)
  always @(posedge clk4)
    if (selector) ValorFuturo0 <= In;
  (* src = "Demux_1x2_8Bits_estructural.v:16.9-28.12" *)
  always @(posedge clk4)
    if (!selector) data_out1_estructural <= In;
  (* src = "Demux_1x2_8Bits_estructural.v:29.9-38.12" *)
  always @*
    if (selector) data_out0_estructural = ValorFuturo0;
  (* src = "Demux_1x2_8Bits_estructural.v:29.9-38.12" *)
  always @*
    if (!selector) validTemp_In1 = validIn;
  (* src = "Demux_1x2_8Bits_estructural.v:44.9-46.12" *)
  always @(posedge clk)
    outValid1_estructural <= validTemp_In1;
  (* src = "Demux_1x2_8Bits_estructural.v:40.9-42.12" *)
  always @(negedge clk4)
    outValid0_estructural <= validTemp_In;
  (* src = "Demux_1x2_8Bits_estructural.v:16.9-28.12" *)
  always @(posedge clk4)
    selector <= clk2;
endmodule
