/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* src = "Mux2x1_8Bits_estruct.v:1.1-40.10" *)
module Mux2x1_8Bits_estruct(In0, In1, clk, valid0, valid1, outValid, data_out_estruct);
  (* src = "Mux2x1_8Bits_estruct.v:18.5-31.8" *)
  wire [7:0] _00_;
  (* src = "Mux2x1_8Bits_estruct.v:33.5-38.8" *)
  wire _01_;
  (* src = "Mux2x1_8Bits_estruct.v:18.5-31.8" *)
  wire _02_;
  (* src = "Mux2x1_8Bits_estruct.v:35.21-35.33" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "Mux2x1_8Bits_estruct.v:22.30-22.43" *)
  wire _07_;
  (* src = "Mux2x1_8Bits_estruct.v:22.12-22.44" *)
  wire _08_;
  (* src = "Mux2x1_8Bits_estruct.v:27.12-27.44" *)
  wire _09_;
  (* src = "Mux2x1_8Bits_estruct.v:2.17-2.20" *)
  input [7:0] In0;
  (* src = "Mux2x1_8Bits_estruct.v:2.21-2.24" *)
  input [7:0] In1;
  (* src = "Mux2x1_8Bits_estruct.v:8.15-8.28" *)
  reg [7:0] ValorAnterior = 8'h00;
  (* src = "Mux2x1_8Bits_estruct.v:3.11-3.14" *)
  input clk;
  (* src = "Mux2x1_8Bits_estruct.v:5.22-5.30" *)
  output [7:0] data_out_estruct;
  reg [7:0] data_out_estruct;
  (* src = "Mux2x1_8Bits_estruct.v:4.16-4.24" *)
  output outValid;
  reg outValid;
  (* src = "Mux2x1_8Bits_estruct.v:10.9-10.17" *)
  reg selector = 1'h0;
  (* src = "Mux2x1_8Bits_estruct.v:3.16-3.22" *)
  input valid0;
  (* src = "Mux2x1_8Bits_estruct.v:3.24-3.30" *)
  input valid1;
  (* src = "Mux2x1_8Bits_estruct.v:9.9-9.18" *)
  wire validTemp;
  assign { _03_[31:1], _01_ } = selector + (* src = "Mux2x1_8Bits_estruct.v:35.21-35.33" *) 32'd1;
  assign _04_ = ~ (* src = "Mux2x1_8Bits_estruct.v:18.5-31.8" *) _09_;
  assign _05_ = ~ (* src = "Mux2x1_8Bits_estruct.v:18.5-31.8" *) _08_;
  assign _06_ = _04_ & (* src = "Mux2x1_8Bits_estruct.v:18.5-31.8" *) _05_;
  (* src = "Mux2x1_8Bits_estruct.v:18.5-31.8" *)
  always @*
    if (!_06_) ValorAnterior = _00_;
  assign _07_ = ~ (* src = "Mux2x1_8Bits_estruct.v:22.30-22.43" *) selector;
  assign _08_ = valid0 && (* src = "Mux2x1_8Bits_estruct.v:22.12-22.44" *) _07_;
  assign _09_ = valid1 && (* src = "Mux2x1_8Bits_estruct.v:27.12-27.44" *) selector;
  (* src = "Mux2x1_8Bits_estruct.v:33.5-38.8" *)
  always @(posedge clk)
    outValid <= validTemp;
  (* src = "Mux2x1_8Bits_estruct.v:33.5-38.8" *)
  always @(posedge clk)
    data_out_estruct <= ValorAnterior;
  (* src = "Mux2x1_8Bits_estruct.v:33.5-38.8" *)
  always @(posedge clk)
    selector <= _01_;
  assign _00_ = _09_ ? (* full_case = 32'd1 *) (* src = "Mux2x1_8Bits_estruct.v:27.12-27.44|Mux2x1_8Bits.v:27.9-30.12" *) In1 : In0;
  assign _02_ = _08_ ? (* full_case = 32'd1 *) (* src = "Mux2x1_8Bits_estruct.v:22.12-22.44|Mux2x1_8Bits.v:22.9-25.12" *) valid0 : 1'h0;
  assign validTemp = _09_ ? (* full_case = 32'd1 *) (* src = "Mux2x1_8Bits_estruct.v:27.12-27.44|Mux2x1_8Bits.v:27.9-30.12" *) valid1 : _02_;
  assign _03_[0] = _01_;
endmodule

(* src = "Recirculacion_estruct.v:1.1-67.10" *)
module Recirculacion_estruct(In0, In1, In2, In3, validIn, data_mux0, data_Probador0, data_mux1, data_Probador1, data_mux2, data_Probador2, data_mux3, data_Probador3);
  (* src = "Recirculacion_estruct.v:2.17-2.20" *)
  input [7:0] In0;
  (* src = "Recirculacion_estruct.v:2.22-2.25" *)
  input [7:0] In1;
  (* src = "Recirculacion_estruct.v:2.27-2.30" *)
  input [7:0] In2;
  (* src = "Recirculacion_estruct.v:2.32-2.35" *)
  input [7:0] In3;
  (* src = "Recirculacion_estruct.v:5.22-5.36" *)
  output [7:0] data_Probador0;
  reg [7:0] data_Probador0;
  (* src = "Recirculacion_estruct.v:7.22-7.36" *)
  output [7:0] data_Probador1;
  reg [7:0] data_Probador1;
  (* src = "Recirculacion_estruct.v:9.22-9.36" *)
  output [7:0] data_Probador2;
  reg [7:0] data_Probador2;
  (* src = "Recirculacion_estruct.v:11.22-11.36" *)
  output [7:0] data_Probador3;
  reg [7:0] data_Probador3;
  (* src = "Recirculacion_estruct.v:4.22-4.31" *)
  output [7:0] data_mux0;
  (* src = "Recirculacion_estruct.v:6.22-6.31" *)
  output [7:0] data_mux1;
  (* src = "Recirculacion_estruct.v:8.22-8.31" *)
  output [7:0] data_mux2;
  (* src = "Recirculacion_estruct.v:10.22-10.31" *)
  output [7:0] data_mux3;
  (* src = "Recirculacion_estruct.v:3.11-3.18" *)
  input validIn;
  (* src = "Recirculacion_estruct.v:55.1-65.4" *)
  always @*
    if (!validIn) data_Probador3 = In3;
  (* src = "Recirculacion_estruct.v:42.1-52.4" *)
  always @*
    if (!validIn) data_Probador2 = In2;
  (* src = "Recirculacion_estruct.v:29.1-39.4" *)
  always @*
    if (!validIn) data_Probador1 = In1;
  (* src = "Recirculacion_estruct.v:16.1-26.4" *)
  always @*
    if (!validIn) data_Probador0 = In0;
  assign data_mux3 = validIn ? (* full_case = 32'd1 *) (* src = "Recirculacion_estruct.v:56.12-56.24|Recirculacion.v:56.9-63.12" *) In3 : 8'h00;
  assign data_mux2 = validIn ? (* full_case = 32'd1 *) (* src = "Recirculacion_estruct.v:43.12-43.24|Recirculacion.v:43.9-50.12" *) In2 : 8'h00;
  assign data_mux1 = validIn ? (* full_case = 32'd1 *) (* src = "Recirculacion_estruct.v:30.12-30.24|Recirculacion.v:30.9-37.12" *) In1 : 8'h00;
  assign data_mux0 = validIn ? (* full_case = 32'd1 *) (* src = "Recirculacion_estruct.v:17.12-17.24|Recirculacion.v:17.9-24.12" *) In0 : 8'h00;
endmodule

(* top =  1  *)
(* src = "phy_tx_estruct.v:4.1-92.10" *)
module phy_tx_estruct(In0, In1, In2, In3, clk, clk2, clk4, valid0, valid1, valid2, valid3, validIn, data_out_estruct, valid_out, data_Probador0, data_Probador1, data_Probador2, data_Probador3);
  (* src = "phy_tx_estruct.v:5.17-5.20" *)
  input [7:0] In0;
  (* src = "phy_tx_estruct.v:29.12-29.20" *)
  wire [7:0] In0_good;
  (* src = "phy_tx_estruct.v:6.17-6.20" *)
  input [7:0] In1;
  (* src = "phy_tx_estruct.v:29.22-29.30" *)
  wire [7:0] In1_good;
  (* src = "phy_tx_estruct.v:7.17-7.20" *)
  input [7:0] In2;
  (* src = "phy_tx_estruct.v:29.32-29.40" *)
  wire [7:0] In2_good;
  (* src = "phy_tx_estruct.v:8.17-8.20" *)
  input [7:0] In3;
  (* src = "phy_tx_estruct.v:29.42-29.50" *)
  wire [7:0] In3_good;
  (* src = "phy_tx_estruct.v:9.11-9.14" *)
  input clk;
  (* src = "phy_tx_estruct.v:10.11-10.15" *)
  input clk2;
  (* src = "phy_tx_estruct.v:11.11-11.15" *)
  input clk4;
  (* src = "phy_tx_estruct.v:18.18-18.32" *)
  output [7:0] data_Probador0;
  (* src = "phy_tx_estruct.v:19.18-19.32" *)
  output [7:0] data_Probador1;
  (* src = "phy_tx_estruct.v:20.18-20.32" *)
  output [7:0] data_Probador2;
  (* src = "phy_tx_estruct.v:21.18-21.32" *)
  output [7:0] data_Probador3;
  (* src = "phy_tx_estruct.v:14.18-14.26" *)
  output [7:0] data_out_estruct;
  (* src = "phy_tx_estruct.v:26.12-26.21" *)
  wire [7:0] out_temp1;
  (* src = "phy_tx_estruct.v:26.23-26.32" *)
  wire [7:0] out_temp2;
  (* src = "phy_tx_estruct.v:12.11-12.17" *)
  input valid0;
  (* src = "phy_tx_estruct.v:12.19-12.25" *)
  input valid1;
  (* src = "phy_tx_estruct.v:12.27-12.33" *)
  input valid2;
  (* src = "phy_tx_estruct.v:12.35-12.41" *)
  input valid3;
  (* src = "phy_tx_estruct.v:13.11-13.18" *)
  input validIn;
  (* src = "phy_tx_estruct.v:15.12-15.21" *)
  output valid_out;
  (* src = "phy_tx_estruct.v:27.6-27.17" *)
  wire valid_out_1;
  (* src = "phy_tx_estruct.v:27.19-27.30" *)
  wire valid_out_2;
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_estruct.v:56.14-64.2" *)
  Mux2x1_8Bits_estruct MUX2x1_1_estruct (
    .In0(In0_good),
    .In1(In1_good),
    .clk(clk2),
    .data_out_estruct(out_temp1),
    .outValid(valid_out_1),
    .valid0(valid0),
    .valid1(valid1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_estruct.v:66.14-74.2" *)
  Mux2x1_8Bits_estruct MUX2x1_2_estruct (
    .In0(In2_good),
    .In1(In3_good),
    .clk(clk2),
    .data_out_estruct(out_temp2),
    .outValid(valid_out_2),
    .valid0(valid2),
    .valid1(valid3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_estruct.v:81.14-89.2" *)
  Mux2x1_8Bits_estruct MUX2x1_3_estruct (
    .In0(out_temp2),
    .In1(out_temp1),
    .clk(clk4),
    .data_out_estruct(data_out_estruct),
    .outValid(valid_out),
    .valid0(valid_out_2),
    .valid1(valid_out_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_estruct.v:32.15-46.2" *)
  Recirculacion_estruct Recirculacion_testbench_estruct (
    .In0(In0),
    .In1(In1),
    .In2(In2),
    .In3(In3),
    .data_Probador0(data_Probador0),
    .data_Probador1(data_Probador1),
    .data_Probador2(data_Probador2),
    .data_Probador3(data_Probador3),
    .data_mux0(In0_good),
    .data_mux1(In1_good),
    .data_mux2(In2_good),
    .data_mux3(In3_good),
    .validIn(validIn)
  );
endmodule
