/* Generated by Yosys 0.9 (git sha1 1979e0b) */
`include "cmos_cells.v"

(* top =  1  *)
(* src = "Mux2x1_8Bits.v:1" *)
module Mux2x1_8Bits_synth(In0, In1, clk, valid0, valid1, outValid, data_out);
  (* src = "Mux2x1_8Bits.v:2" *)
  wire _00_;
  (* src = "Mux2x1_8Bits.v:2" *)
  wire _01_;
  (* src = "Mux2x1_8Bits.v:2" *)
  wire _02_;
  (* src = "Mux2x1_8Bits.v:2" *)
  wire _03_;
  (* src = "Mux2x1_8Bits.v:2" *)
  wire _04_;
  (* src = "Mux2x1_8Bits.v:2" *)
  wire _05_;
  (* src = "Mux2x1_8Bits.v:2" *)
  wire _06_;
  (* src = "Mux2x1_8Bits.v:2" *)
  wire _07_;
  (* src = "Mux2x1_8Bits.v:8" *)
  wire _08_;
  (* src = "Mux2x1_8Bits.v:8" *)
  wire _09_;
  (* src = "Mux2x1_8Bits.v:8" *)
  wire _10_;
  (* src = "Mux2x1_8Bits.v:8" *)
  wire _11_;
  (* src = "Mux2x1_8Bits.v:8" *)
  wire _12_;
  (* src = "Mux2x1_8Bits.v:8" *)
  wire _13_;
  (* src = "Mux2x1_8Bits.v:8" *)
  wire _14_;
  (* src = "Mux2x1_8Bits.v:8" *)
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "Mux2x1_8Bits.v:3" *)
  wire _24_;
  (* src = "Mux2x1_8Bits.v:2" *)
  input [7:0] In0;
  (* src = "Mux2x1_8Bits.v:2" *)
  input [7:0] In1;
  (* src = "Mux2x1_8Bits.v:8" *)
  wire [7:0] ValorAnterior;
  (* src = "Mux2x1_8Bits.v:3" *)
  input clk;
  (* src = "Mux2x1_8Bits.v:5" *)
  output [7:0] data_out;
  (* src = "Mux2x1_8Bits.v:4" *)
  output outValid;
  (* init = 1'h0 *)
  (* src = "Mux2x1_8Bits.v:10" *)
  wire selector;
  (* src = "Mux2x1_8Bits.v:3" *)
  input valid0;
  (* src = "Mux2x1_8Bits.v:3" *)
  input valid1;
  (* init = 1'h0 *)
  (* src = "Mux2x1_8Bits.v:9" *)
  wire validTemp;
  NAND _25_ (
    .A(_01_),
    .B(_24_),
    .Y(_16_)
  );
  NOT _26_ (
    .A(_16_),
    .Y(_09_)
  );
  NAND _27_ (
    .A(_24_),
    .B(_02_),
    .Y(_17_)
  );
  NOT _28_ (
    .A(_17_),
    .Y(_10_)
  );
  NAND _29_ (
    .A(_24_),
    .B(_03_),
    .Y(_18_)
  );
  NOT _30_ (
    .A(_18_),
    .Y(_11_)
  );
  NAND _31_ (
    .A(_24_),
    .B(_04_),
    .Y(_19_)
  );
  NOT _32_ (
    .A(_19_),
    .Y(_12_)
  );
  NAND _33_ (
    .A(_24_),
    .B(_05_),
    .Y(_20_)
  );
  NOT _34_ (
    .A(_20_),
    .Y(_13_)
  );
  NAND _35_ (
    .A(_24_),
    .B(_06_),
    .Y(_21_)
  );
  NOT _36_ (
    .A(_21_),
    .Y(_14_)
  );
  NAND _37_ (
    .A(_24_),
    .B(_07_),
    .Y(_22_)
  );
  NOT _38_ (
    .A(_22_),
    .Y(_15_)
  );
  NAND _39_ (
    .A(_24_),
    .B(_00_),
    .Y(_23_)
  );
  NOT _40_ (
    .A(_23_),
    .Y(_08_)
  );
  (* src = "Mux2x1_8Bits.v:36" *)
  DFF _41_ (
    .C(clk),
    .D(ValorAnterior[0]),
    .Q(data_out[0])
  );
  (* src = "Mux2x1_8Bits.v:36" *)
  DFF _42_ (
    .C(clk),
    .D(ValorAnterior[1]),
    .Q(data_out[1])
  );
  (* src = "Mux2x1_8Bits.v:36" *)
  DFF _43_ (
    .C(clk),
    .D(ValorAnterior[2]),
    .Q(data_out[2])
  );
  (* src = "Mux2x1_8Bits.v:36" *)
  DFF _44_ (
    .C(clk),
    .D(ValorAnterior[3]),
    .Q(data_out[3])
  );
  (* src = "Mux2x1_8Bits.v:36" *)
  DFF _45_ (
    .C(clk),
    .D(ValorAnterior[4]),
    .Q(data_out[4])
  );
  (* src = "Mux2x1_8Bits.v:36" *)
  DFF _46_ (
    .C(clk),
    .D(ValorAnterior[5]),
    .Q(data_out[5])
  );
  (* src = "Mux2x1_8Bits.v:36" *)
  DFF _47_ (
    .C(clk),
    .D(ValorAnterior[6]),
    .Q(data_out[6])
  );
  (* src = "Mux2x1_8Bits.v:36" *)
  DFF _48_ (
    .C(clk),
    .D(ValorAnterior[7]),
    .Q(data_out[7])
  );
  (* src = "Mux2x1_8Bits.v:36" *)
  DFF _49_ (
    .C(clk),
    .D(valid0),
    .Q(outValid)
  );
  assign selector = 1'h0;
  assign validTemp = valid0;
  assign _01_ = In0[1];
  assign _24_ = valid0;
  assign ValorAnterior[1] = _09_;
  assign _02_ = In0[2];
  assign ValorAnterior[2] = _10_;
  assign _03_ = In0[3];
  assign ValorAnterior[3] = _11_;
  assign _04_ = In0[4];
  assign ValorAnterior[4] = _12_;
  assign _05_ = In0[5];
  assign ValorAnterior[5] = _13_;
  assign _06_ = In0[6];
  assign ValorAnterior[6] = _14_;
  assign _07_ = In0[7];
  assign ValorAnterior[7] = _15_;
  assign _00_ = In0[0];
  assign ValorAnterior[0] = _08_;
endmodule
