/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "ParaleloSerial_IDL_estruct.v:1.1-66.10" *)
module ParaleloSerial_IDL_estruct(active, clk_32f, clk_4f, IDL_estruct);
  (* src = "ParaleloSerial_IDL_estruct.v:11.1-32.4" *)
  wire _00_;
  (* src = "ParaleloSerial_IDL_estruct.v:57.1-59.4" *)
  wire [2:0] _01_;
  (* src = "ParaleloSerial_IDL_estruct.v:61.1-63.4" *)
  wire _02_;
  (* src = "ParaleloSerial_IDL_estruct.v:11.1-32.4" *)
  wire _03_;
  (* src = "ParaleloSerial_IDL_estruct.v:8.11-8.28" *)
  wire [2:0] _04_;
  (* src = "ParaleloSerial_IDL_estruct.v:11.1-32.4" *)
  wire _05_;
  (* src = "ParaleloSerial_IDL_estruct.v:33.1-54.4" *)
  wire _06_;
  (* src = "ParaleloSerial_IDL_estruct.v:33.1-54.4" *)
  wire _07_;
  (* src = "ParaleloSerial_IDL_estruct.v:33.1-54.4" *)
  wire _08_;
  (* src = "ParaleloSerial_IDL_estruct.v:58.17-58.29" *)
  wire [31:0] _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "ParaleloSerial_IDL_estruct.v:12.5-12.15" *)
  wire _20_;
  (* src = "ParaleloSerial_IDL_estruct.v:34.5-34.15" *)
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  (* src = "ParaleloSerial_IDL_estruct.v:5.16-5.19" *)
  output IDL_estruct;
  reg IDL_estruct;
  (* src = "ParaleloSerial_IDL_estruct.v:2.11-2.17" *)
  input active;
  (* src = "ParaleloSerial_IDL_estruct.v:3.11-3.18" *)
  input clk_32f;
  (* src = "ParaleloSerial_IDL_estruct.v:4.11-4.17" *)
  input clk_4f;
  (* src = "ParaleloSerial_IDL_estruct.v:8.11-8.19" *)
  reg [2:0] selector = 3'h7;
  (* src = "ParaleloSerial_IDL_estruct.v:9.5-9.10" *)
  reg valid;
  assign _09_ = selector + (* src = "ParaleloSerial_IDL_estruct.v:58.17-58.29" *) 32'd1;
  assign _10_ = ~ (* src = "ParaleloSerial_IDL_estruct.v:33.1-54.4" *) _21_;
  assign _12_ = ~ (* src = "ParaleloSerial_IDL_estruct.v:11.1-32.4" *) _20_;
  assign _14_ = | (* src = "ParaleloSerial_IDL_estruct.v:33.1-54.4" *) 1'h1;
  assign _15_ = | (* src = "ParaleloSerial_IDL_estruct.v:33.1-54.4" *) _18_;
  assign _16_ = | (* src = "ParaleloSerial_IDL_estruct.v:11.1-32.4" *) 1'h1;
  assign _17_ = | (* src = "ParaleloSerial_IDL_estruct.v:11.1-32.4" *) _19_;
  assign _18_ = _10_ & (* src = "ParaleloSerial_IDL_estruct.v:33.1-54.4" *) _14_;
  assign _19_ = _12_ & (* src = "ParaleloSerial_IDL_estruct.v:11.1-32.4" *) _16_;
  assign _11_ = ~ _15_;
  (* src = "ParaleloSerial_IDL_estruct.v:33.1-54.4" *)
  always @*
    if (_11_) IDL_estruct = _33_;
  assign _13_ = ~ _17_;
  (* src = "ParaleloSerial_IDL_estruct.v:11.1-32.4" *)
  always @*
    if (_13_) IDL_estruct = _46_;
  assign _20_ = valid == (* src = "ParaleloSerial_IDL_estruct.v:12.5-12.15" *) 32'd1;
  assign _21_ = valid == (* src = "ParaleloSerial_IDL_estruct.v:34.5-34.15" *) 32'd0;
  (* src = "ParaleloSerial_IDL_estruct.v:61.1-63.4" *)
  always @(posedge clk_4f)
    valid <= active;
  (* src = "ParaleloSerial_IDL_estruct.v:57.1-59.4" *)
  always @(posedge clk_32f)
    selector <= _09_[2:0];
  function [0:0] _65_;
    input [0:0] a;
    input [7:0] b;
    input [7:0] s;
    (* full_case = 32'd1 *)
    (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:35.5-52.12" *)
    (* parallel_case *)
    casez (s)
      8'b???????1:
        _65_ = b[0:0];
      8'b??????1?:
        _65_ = b[1:1];
      8'b?????1??:
        _65_ = b[2:2];
      8'b????1???:
        _65_ = b[3:3];
      8'b???1????:
        _65_ = b[4:4];
      8'b??1?????:
        _65_ = b[5:5];
      8'b?1??????:
        _65_ = b[6:6];
      8'b1???????:
        _65_ = b[7:7];
      default:
        _65_ = a;
    endcase
  endfunction
  assign _22_ = _65_(1'h1, 8'hbc, { _30_, _29_, _28_, _27_, _26_, _25_, _24_, _23_ });
  assign _23_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:35.5-52.12" *) 3'h7;
  assign _24_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:35.5-52.12" *) 3'h6;
  assign _25_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:35.5-52.12" *) 3'h5;
  assign _26_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:35.5-52.12" *) 3'h4;
  assign _27_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:35.5-52.12" *) 3'h3;
  assign _28_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:35.5-52.12" *) 3'h2;
  assign _29_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:35.5-52.12" *) 3'h1;
  assign _30_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:35.5-52.12" *) 3'h0;
  assign _31_ = _32_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:34.5-34.15|ParaleloSerial_IDL.v:34.1-53.8" *) _22_ : _22_;
  assign _33_ = _34_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:34.5-34.15|ParaleloSerial_IDL.v:34.1-53.8" *) _08_ : _08_;
  function [0:0] _76_;
    input [0:0] a;
    input [7:0] b;
    input [7:0] s;
    (* full_case = 32'd1 *)
    (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:13.5-30.12" *)
    (* parallel_case *)
    casez (s)
      8'b???????1:
        _76_ = b[0:0];
      8'b??????1?:
        _76_ = b[1:1];
      8'b?????1??:
        _76_ = b[2:2];
      8'b????1???:
        _76_ = b[3:3];
      8'b???1????:
        _76_ = b[4:4];
      8'b??1?????:
        _76_ = b[5:5];
      8'b?1??????:
        _76_ = b[6:6];
      8'b1???????:
        _76_ = b[7:7];
      default:
        _76_ = a;
    endcase
  endfunction
  assign _35_ = _76_(1'h1, 8'hfc, { _43_, _42_, _41_, _40_, _39_, _38_, _37_, _36_ });
  assign _36_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:13.5-30.12" *) 3'h7;
  assign _37_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:13.5-30.12" *) 3'h6;
  assign _38_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:13.5-30.12" *) 3'h5;
  assign _39_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:13.5-30.12" *) 3'h4;
  assign _40_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:13.5-30.12" *) 3'h3;
  assign _41_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:13.5-30.12" *) 3'h2;
  assign _42_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:13.5-30.12" *) 3'h1;
  assign _43_ = selector == (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:0.0-0.0|ParaleloSerial_IDL.v:13.5-30.12" *) 3'h0;
  assign _44_ = _45_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:12.5-12.15|ParaleloSerial_IDL.v:12.1-31.8" *) _35_ : _35_;
  assign _46_ = _47_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_IDL_estruct.v:12.5-12.15|ParaleloSerial_IDL.v:12.1-31.8" *) _05_ : _05_;
  assign _04_ = 3'h7;
  assign _02_ = active;
  assign _01_ = _09_[2:0];
  assign _06_ = _07_;
  assign _00_ = _03_;
  assign _32_ = _21_;
  assign _08_ = _31_;
  assign _34_ = _21_;
  assign _07_ = _33_;
  assign _45_ = _20_;
  assign _05_ = _44_;
  assign _47_ = _20_;
  assign _03_ = _46_;
endmodule
