/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "Mux2x1_8Bits_estruct.v:3.1-51.10" *)
module Mux2x1_8Bits_estruct(In0, In1, clk, valid0, valid1, reset, outValid, data_out);
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  (* src = "Mux2x1_8Bits_estruct.v:4.17-4.20" *)
  input [7:0] In0;
  (* src = "Mux2x1_8Bits_estruct.v:4.21-4.24" *)
  input [7:0] In1;
  (* src = "Mux2x1_8Bits_estruct.v:11.15-11.28" *)
  reg [7:0] ValorAnterior;
  (* src = "Mux2x1_8Bits_estruct.v:5.11-5.14" *)
  input clk;
  (* src = "Mux2x1_8Bits_estruct.v:8.22-8.30" *)
  output [7:0] data_out;
  (* src = "Mux2x1_8Bits_estruct.v:7.16-7.24" *)
  output outValid;
  (* src = "Mux2x1_8Bits_estruct.v:6.11-6.16" *)
  input reset;
  (* src = "Mux2x1_8Bits_estruct.v:13.9-13.17" *)
  wire selector;
  (* src = "Mux2x1_8Bits_estruct.v:5.16-5.22" *)
  input valid0;
  (* src = "Mux2x1_8Bits_estruct.v:5.24-5.30" *)
  input valid1;
  NOT _086_ (
    .A(reset),
    .Y(_050_)
  );
  NOT _087_ (
    .A(selector),
    .Y(_051_)
  );
  NOT _088_ (
    .A(In1[0]),
    .Y(_052_)
  );
  NOT _089_ (
    .A(In1[1]),
    .Y(_053_)
  );
  NOT _090_ (
    .A(In1[2]),
    .Y(_054_)
  );
  NOT _091_ (
    .A(In1[3]),
    .Y(_055_)
  );
  NOT _092_ (
    .A(In1[4]),
    .Y(_056_)
  );
  NOT _093_ (
    .A(In1[5]),
    .Y(_057_)
  );
  NOT _094_ (
    .A(In1[6]),
    .Y(_058_)
  );
  NOT _095_ (
    .A(In1[7]),
    .Y(_059_)
  );
  NOT _096_ (
    .A(valid0),
    .Y(_060_)
  );
  NOT _097_ (
    .A(In0[0]),
    .Y(_061_)
  );
  NOT _098_ (
    .A(In0[1]),
    .Y(_062_)
  );
  NOT _099_ (
    .A(In0[2]),
    .Y(_063_)
  );
  NOT _100_ (
    .A(In0[3]),
    .Y(_064_)
  );
  NOT _101_ (
    .A(In0[4]),
    .Y(_065_)
  );
  NOT _102_ (
    .A(In0[5]),
    .Y(_066_)
  );
  NOT _103_ (
    .A(In0[6]),
    .Y(_067_)
  );
  NOT _104_ (
    .A(In0[7]),
    .Y(_068_)
  );
  NAND _105_ (
    .A(data_out[7]),
    .B(reset),
    .Y(_069_)
  );
  NAND _106_ (
    .A(ValorAnterior[7]),
    .B(_050_),
    .Y(_070_)
  );
  NAND _107_ (
    .A(_069_),
    .B(_070_),
    .Y(_009_)
  );
  NAND _108_ (
    .A(reset),
    .B(data_out[6]),
    .Y(_071_)
  );
  NAND _109_ (
    .A(_050_),
    .B(ValorAnterior[6]),
    .Y(_072_)
  );
  NAND _110_ (
    .A(_071_),
    .B(_072_),
    .Y(_008_)
  );
  NAND _111_ (
    .A(reset),
    .B(data_out[5]),
    .Y(_073_)
  );
  NAND _112_ (
    .A(_050_),
    .B(ValorAnterior[5]),
    .Y(_074_)
  );
  NAND _113_ (
    .A(_073_),
    .B(_074_),
    .Y(_007_)
  );
  NAND _114_ (
    .A(reset),
    .B(data_out[4]),
    .Y(_075_)
  );
  NAND _115_ (
    .A(_050_),
    .B(ValorAnterior[4]),
    .Y(_076_)
  );
  NAND _116_ (
    .A(_075_),
    .B(_076_),
    .Y(_006_)
  );
  NAND _117_ (
    .A(reset),
    .B(data_out[3]),
    .Y(_077_)
  );
  NAND _118_ (
    .A(_050_),
    .B(ValorAnterior[3]),
    .Y(_078_)
  );
  NAND _119_ (
    .A(_077_),
    .B(_078_),
    .Y(_005_)
  );
  NAND _120_ (
    .A(reset),
    .B(data_out[2]),
    .Y(_079_)
  );
  NAND _121_ (
    .A(_050_),
    .B(ValorAnterior[2]),
    .Y(_080_)
  );
  NAND _122_ (
    .A(_079_),
    .B(_080_),
    .Y(_004_)
  );
  NAND _123_ (
    .A(reset),
    .B(data_out[1]),
    .Y(_081_)
  );
  NAND _124_ (
    .A(_050_),
    .B(ValorAnterior[1]),
    .Y(_082_)
  );
  NAND _125_ (
    .A(_081_),
    .B(_082_),
    .Y(_003_)
  );
  NAND _126_ (
    .A(reset),
    .B(data_out[0]),
    .Y(_083_)
  );
  NAND _127_ (
    .A(_050_),
    .B(ValorAnterior[0]),
    .Y(_084_)
  );
  NAND _128_ (
    .A(_083_),
    .B(_084_),
    .Y(_002_)
  );
  NAND _129_ (
    .A(selector),
    .B(valid1),
    .Y(_085_)
  );
  NOT _130_ (
    .A(_085_),
    .Y(_011_)
  );
  NOR _131_ (
    .A(selector),
    .B(_060_),
    .Y(_012_)
  );
  NAND _132_ (
    .A(_051_),
    .B(valid0),
    .Y(_013_)
  );
  NOR _133_ (
    .A(_011_),
    .B(_012_),
    .Y(_014_)
  );
  NAND _134_ (
    .A(_085_),
    .B(_013_),
    .Y(_015_)
  );
  NAND _135_ (
    .A(_050_),
    .B(_015_),
    .Y(_016_)
  );
  NAND _136_ (
    .A(reset),
    .B(outValid),
    .Y(_017_)
  );
  NAND _137_ (
    .A(_016_),
    .B(_017_),
    .Y(_001_)
  );
  NAND _138_ (
    .A(data_out[0]),
    .B(_014_),
    .Y(_018_)
  );
  NOR _139_ (
    .A(_052_),
    .B(_085_),
    .Y(_019_)
  );
  NOR _140_ (
    .A(_061_),
    .B(_013_),
    .Y(_020_)
  );
  NOR _141_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _142_ (
    .A(_018_),
    .B(_021_),
    .Y(_000_[0])
  );
  NAND _143_ (
    .A(data_out[1]),
    .B(_014_),
    .Y(_022_)
  );
  NOR _144_ (
    .A(_053_),
    .B(_085_),
    .Y(_023_)
  );
  NOR _145_ (
    .A(_062_),
    .B(_013_),
    .Y(_024_)
  );
  NOR _146_ (
    .A(_023_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _147_ (
    .A(_022_),
    .B(_025_),
    .Y(_000_[1])
  );
  NAND _148_ (
    .A(data_out[2]),
    .B(_014_),
    .Y(_026_)
  );
  NOR _149_ (
    .A(_054_),
    .B(_085_),
    .Y(_027_)
  );
  NOR _150_ (
    .A(_063_),
    .B(_013_),
    .Y(_028_)
  );
  NOR _151_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  NAND _152_ (
    .A(_026_),
    .B(_029_),
    .Y(_000_[2])
  );
  NAND _153_ (
    .A(data_out[3]),
    .B(_014_),
    .Y(_030_)
  );
  NOR _154_ (
    .A(_055_),
    .B(_085_),
    .Y(_031_)
  );
  NOR _155_ (
    .A(_064_),
    .B(_013_),
    .Y(_032_)
  );
  NOR _156_ (
    .A(_031_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _157_ (
    .A(_030_),
    .B(_033_),
    .Y(_000_[3])
  );
  NAND _158_ (
    .A(data_out[4]),
    .B(_014_),
    .Y(_034_)
  );
  NOR _159_ (
    .A(_056_),
    .B(_085_),
    .Y(_035_)
  );
  NOR _160_ (
    .A(_065_),
    .B(_013_),
    .Y(_036_)
  );
  NOR _161_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  NAND _162_ (
    .A(_034_),
    .B(_037_),
    .Y(_000_[4])
  );
  NAND _163_ (
    .A(data_out[5]),
    .B(_014_),
    .Y(_038_)
  );
  NOR _164_ (
    .A(_057_),
    .B(_085_),
    .Y(_039_)
  );
  NOR _165_ (
    .A(_066_),
    .B(_013_),
    .Y(_040_)
  );
  NOR _166_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _167_ (
    .A(_038_),
    .B(_041_),
    .Y(_000_[5])
  );
  NAND _168_ (
    .A(data_out[6]),
    .B(_014_),
    .Y(_042_)
  );
  NOR _169_ (
    .A(_058_),
    .B(_085_),
    .Y(_043_)
  );
  NOR _170_ (
    .A(_067_),
    .B(_013_),
    .Y(_044_)
  );
  NOR _171_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _172_ (
    .A(_042_),
    .B(_045_),
    .Y(_000_[6])
  );
  NAND _173_ (
    .A(data_out[7]),
    .B(_014_),
    .Y(_046_)
  );
  NOR _174_ (
    .A(_059_),
    .B(_085_),
    .Y(_047_)
  );
  NOR _175_ (
    .A(_068_),
    .B(_013_),
    .Y(_048_)
  );
  NOR _176_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _177_ (
    .A(_046_),
    .B(_049_),
    .Y(_000_[7])
  );
  NOR _178_ (
    .A(reset),
    .B(selector),
    .Y(_010_)
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _179_ (
    .C(clk),
    .D(_001_),
    .Q(outValid)
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _180_ (
    .C(clk),
    .D(_002_),
    .Q(data_out[0])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _181_ (
    .C(clk),
    .D(_003_),
    .Q(data_out[1])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _182_ (
    .C(clk),
    .D(_004_),
    .Q(data_out[2])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _183_ (
    .C(clk),
    .D(_005_),
    .Q(data_out[3])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _184_ (
    .C(clk),
    .D(_006_),
    .Q(data_out[4])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _185_ (
    .C(clk),
    .D(_007_),
    .Q(data_out[5])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _186_ (
    .C(clk),
    .D(_008_),
    .Q(data_out[6])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _187_ (
    .C(clk),
    .D(_009_),
    .Q(data_out[7])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _188_ (
    .C(clk),
    .D(_010_),
    .Q(selector)
  );
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[0] = _000_[0];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[1] = _000_[1];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[2] = _000_[2];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[3] = _000_[3];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[4] = _000_[4];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[5] = _000_[5];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[6] = _000_[6];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[7] = _000_[7];
endmodule
