/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* src = "Mux2x1_8Bits_estruct.v:3.1-51.10" *)
module Mux2x1_8Bits_estruct(In0, In1, clk, valid0, valid1, reset, outValid, data_out);
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  (* src = "Mux2x1_8Bits_estruct.v:4.17-4.20" *)
  input [7:0] In0;
  (* src = "Mux2x1_8Bits_estruct.v:4.21-4.24" *)
  input [7:0] In1;
  (* src = "Mux2x1_8Bits_estruct.v:11.15-11.28" *)
  reg [7:0] ValorAnterior;
  (* src = "Mux2x1_8Bits_estruct.v:5.11-5.14" *)
  input clk;
  (* src = "Mux2x1_8Bits_estruct.v:8.22-8.30" *)
  output [7:0] data_out;
  (* src = "Mux2x1_8Bits_estruct.v:7.16-7.24" *)
  output outValid;
  (* src = "Mux2x1_8Bits_estruct.v:6.11-6.16" *)
  input reset;
  (* src = "Mux2x1_8Bits_estruct.v:13.9-13.17" *)
  wire selector;
  (* src = "Mux2x1_8Bits_estruct.v:5.16-5.22" *)
  input valid0;
  (* src = "Mux2x1_8Bits_estruct.v:5.24-5.30" *)
  input valid1;
  NOT _086_ (
    .A(reset),
    .Y(_050_)
  );
  NOT _087_ (
    .A(selector),
    .Y(_051_)
  );
  NOT _088_ (
    .A(In1[0]),
    .Y(_052_)
  );
  NOT _089_ (
    .A(In1[1]),
    .Y(_053_)
  );
  NOT _090_ (
    .A(In1[2]),
    .Y(_054_)
  );
  NOT _091_ (
    .A(In1[3]),
    .Y(_055_)
  );
  NOT _092_ (
    .A(In1[4]),
    .Y(_056_)
  );
  NOT _093_ (
    .A(In1[5]),
    .Y(_057_)
  );
  NOT _094_ (
    .A(In1[6]),
    .Y(_058_)
  );
  NOT _095_ (
    .A(In1[7]),
    .Y(_059_)
  );
  NOT _096_ (
    .A(valid0),
    .Y(_060_)
  );
  NOT _097_ (
    .A(In0[0]),
    .Y(_061_)
  );
  NOT _098_ (
    .A(In0[1]),
    .Y(_062_)
  );
  NOT _099_ (
    .A(In0[2]),
    .Y(_063_)
  );
  NOT _100_ (
    .A(In0[3]),
    .Y(_064_)
  );
  NOT _101_ (
    .A(In0[4]),
    .Y(_065_)
  );
  NOT _102_ (
    .A(In0[5]),
    .Y(_066_)
  );
  NOT _103_ (
    .A(In0[6]),
    .Y(_067_)
  );
  NOT _104_ (
    .A(In0[7]),
    .Y(_068_)
  );
  NAND _105_ (
    .A(data_out[7]),
    .B(reset),
    .Y(_069_)
  );
  NAND _106_ (
    .A(ValorAnterior[7]),
    .B(_050_),
    .Y(_070_)
  );
  NAND _107_ (
    .A(_069_),
    .B(_070_),
    .Y(_009_)
  );
  NAND _108_ (
    .A(reset),
    .B(data_out[6]),
    .Y(_071_)
  );
  NAND _109_ (
    .A(_050_),
    .B(ValorAnterior[6]),
    .Y(_072_)
  );
  NAND _110_ (
    .A(_071_),
    .B(_072_),
    .Y(_008_)
  );
  NAND _111_ (
    .A(reset),
    .B(data_out[5]),
    .Y(_073_)
  );
  NAND _112_ (
    .A(_050_),
    .B(ValorAnterior[5]),
    .Y(_074_)
  );
  NAND _113_ (
    .A(_073_),
    .B(_074_),
    .Y(_007_)
  );
  NAND _114_ (
    .A(reset),
    .B(data_out[4]),
    .Y(_075_)
  );
  NAND _115_ (
    .A(_050_),
    .B(ValorAnterior[4]),
    .Y(_076_)
  );
  NAND _116_ (
    .A(_075_),
    .B(_076_),
    .Y(_006_)
  );
  NAND _117_ (
    .A(reset),
    .B(data_out[3]),
    .Y(_077_)
  );
  NAND _118_ (
    .A(_050_),
    .B(ValorAnterior[3]),
    .Y(_078_)
  );
  NAND _119_ (
    .A(_077_),
    .B(_078_),
    .Y(_005_)
  );
  NAND _120_ (
    .A(reset),
    .B(data_out[2]),
    .Y(_079_)
  );
  NAND _121_ (
    .A(_050_),
    .B(ValorAnterior[2]),
    .Y(_080_)
  );
  NAND _122_ (
    .A(_079_),
    .B(_080_),
    .Y(_004_)
  );
  NAND _123_ (
    .A(reset),
    .B(data_out[1]),
    .Y(_081_)
  );
  NAND _124_ (
    .A(_050_),
    .B(ValorAnterior[1]),
    .Y(_082_)
  );
  NAND _125_ (
    .A(_081_),
    .B(_082_),
    .Y(_003_)
  );
  NAND _126_ (
    .A(reset),
    .B(data_out[0]),
    .Y(_083_)
  );
  NAND _127_ (
    .A(_050_),
    .B(ValorAnterior[0]),
    .Y(_084_)
  );
  NAND _128_ (
    .A(_083_),
    .B(_084_),
    .Y(_002_)
  );
  NAND _129_ (
    .A(selector),
    .B(valid1),
    .Y(_085_)
  );
  NOT _130_ (
    .A(_085_),
    .Y(_011_)
  );
  NOR _131_ (
    .A(selector),
    .B(_060_),
    .Y(_012_)
  );
  NAND _132_ (
    .A(_051_),
    .B(valid0),
    .Y(_013_)
  );
  NOR _133_ (
    .A(_011_),
    .B(_012_),
    .Y(_014_)
  );
  NAND _134_ (
    .A(_085_),
    .B(_013_),
    .Y(_015_)
  );
  NAND _135_ (
    .A(_050_),
    .B(_015_),
    .Y(_016_)
  );
  NAND _136_ (
    .A(reset),
    .B(outValid),
    .Y(_017_)
  );
  NAND _137_ (
    .A(_016_),
    .B(_017_),
    .Y(_001_)
  );
  NAND _138_ (
    .A(data_out[0]),
    .B(_014_),
    .Y(_018_)
  );
  NOR _139_ (
    .A(_052_),
    .B(_085_),
    .Y(_019_)
  );
  NOR _140_ (
    .A(_061_),
    .B(_013_),
    .Y(_020_)
  );
  NOR _141_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _142_ (
    .A(_018_),
    .B(_021_),
    .Y(_000_[0])
  );
  NAND _143_ (
    .A(data_out[1]),
    .B(_014_),
    .Y(_022_)
  );
  NOR _144_ (
    .A(_053_),
    .B(_085_),
    .Y(_023_)
  );
  NOR _145_ (
    .A(_062_),
    .B(_013_),
    .Y(_024_)
  );
  NOR _146_ (
    .A(_023_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _147_ (
    .A(_022_),
    .B(_025_),
    .Y(_000_[1])
  );
  NAND _148_ (
    .A(data_out[2]),
    .B(_014_),
    .Y(_026_)
  );
  NOR _149_ (
    .A(_054_),
    .B(_085_),
    .Y(_027_)
  );
  NOR _150_ (
    .A(_063_),
    .B(_013_),
    .Y(_028_)
  );
  NOR _151_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  NAND _152_ (
    .A(_026_),
    .B(_029_),
    .Y(_000_[2])
  );
  NAND _153_ (
    .A(data_out[3]),
    .B(_014_),
    .Y(_030_)
  );
  NOR _154_ (
    .A(_055_),
    .B(_085_),
    .Y(_031_)
  );
  NOR _155_ (
    .A(_064_),
    .B(_013_),
    .Y(_032_)
  );
  NOR _156_ (
    .A(_031_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _157_ (
    .A(_030_),
    .B(_033_),
    .Y(_000_[3])
  );
  NAND _158_ (
    .A(data_out[4]),
    .B(_014_),
    .Y(_034_)
  );
  NOR _159_ (
    .A(_056_),
    .B(_085_),
    .Y(_035_)
  );
  NOR _160_ (
    .A(_065_),
    .B(_013_),
    .Y(_036_)
  );
  NOR _161_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  NAND _162_ (
    .A(_034_),
    .B(_037_),
    .Y(_000_[4])
  );
  NAND _163_ (
    .A(data_out[5]),
    .B(_014_),
    .Y(_038_)
  );
  NOR _164_ (
    .A(_057_),
    .B(_085_),
    .Y(_039_)
  );
  NOR _165_ (
    .A(_066_),
    .B(_013_),
    .Y(_040_)
  );
  NOR _166_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _167_ (
    .A(_038_),
    .B(_041_),
    .Y(_000_[5])
  );
  NAND _168_ (
    .A(data_out[6]),
    .B(_014_),
    .Y(_042_)
  );
  NOR _169_ (
    .A(_058_),
    .B(_085_),
    .Y(_043_)
  );
  NOR _170_ (
    .A(_067_),
    .B(_013_),
    .Y(_044_)
  );
  NOR _171_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _172_ (
    .A(_042_),
    .B(_045_),
    .Y(_000_[6])
  );
  NAND _173_ (
    .A(data_out[7]),
    .B(_014_),
    .Y(_046_)
  );
  NOR _174_ (
    .A(_059_),
    .B(_085_),
    .Y(_047_)
  );
  NOR _175_ (
    .A(_068_),
    .B(_013_),
    .Y(_048_)
  );
  NOR _176_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _177_ (
    .A(_046_),
    .B(_049_),
    .Y(_000_[7])
  );
  NOR _178_ (
    .A(reset),
    .B(selector),
    .Y(_010_)
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _179_ (
    .C(clk),
    .D(_001_),
    .Q(outValid)
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _180_ (
    .C(clk),
    .D(_002_),
    .Q(data_out[0])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _181_ (
    .C(clk),
    .D(_003_),
    .Q(data_out[1])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _182_ (
    .C(clk),
    .D(_004_),
    .Q(data_out[2])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _183_ (
    .C(clk),
    .D(_005_),
    .Q(data_out[3])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _184_ (
    .C(clk),
    .D(_006_),
    .Q(data_out[4])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _185_ (
    .C(clk),
    .D(_007_),
    .Q(data_out[5])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _186_ (
    .C(clk),
    .D(_008_),
    .Q(data_out[6])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _187_ (
    .C(clk),
    .D(_009_),
    .Q(data_out[7])
  );
  (* src = "Mux2x1_8Bits_estruct.v:40.5-49.8" *)
  DFF _188_ (
    .C(clk),
    .D(_010_),
    .Q(selector)
  );
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[0] = _000_[0];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[1] = _000_[1];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[2] = _000_[2];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[3] = _000_[3];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[4] = _000_[4];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[5] = _000_[5];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[6] = _000_[6];
  (* src = "Mux2x1_8Bits_estruct.v:15.5-38.8" *)
  always @*
    if (!reset) ValorAnterior[7] = _000_[7];
endmodule

(* src = "Recirculacion_estruct.v:1.1-75.10" *)
module Recirculacion_estruct(In0, In1, In2, In3, validIn, data_mux0, data_Probador0, data_mux1, data_Probador1, data_mux2, data_Probador2, data_mux3, data_Probador3);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  (* src = "Recirculacion_estruct.v:2.17-2.20" *)
  input [7:0] In0;
  (* src = "Recirculacion_estruct.v:2.22-2.25" *)
  input [7:0] In1;
  (* src = "Recirculacion_estruct.v:2.27-2.30" *)
  input [7:0] In2;
  (* src = "Recirculacion_estruct.v:2.32-2.35" *)
  input [7:0] In3;
  (* src = "Recirculacion_estruct.v:5.22-5.36" *)
  output [7:0] data_Probador0;
  (* src = "Recirculacion_estruct.v:7.22-7.36" *)
  output [7:0] data_Probador1;
  (* src = "Recirculacion_estruct.v:9.22-9.36" *)
  output [7:0] data_Probador2;
  (* src = "Recirculacion_estruct.v:11.22-11.36" *)
  output [7:0] data_Probador3;
  (* src = "Recirculacion_estruct.v:4.22-4.31" *)
  output [7:0] data_mux0;
  (* src = "Recirculacion_estruct.v:6.22-6.31" *)
  output [7:0] data_mux1;
  (* src = "Recirculacion_estruct.v:8.22-8.31" *)
  output [7:0] data_mux2;
  (* src = "Recirculacion_estruct.v:10.22-10.31" *)
  output [7:0] data_mux3;
  (* src = "Recirculacion_estruct.v:3.11-3.18" *)
  input validIn;
  NAND _064_ (
    .A(validIn),
    .B(In2[7]),
    .Y(_045_)
  );
  NOT _065_ (
    .A(_045_),
    .Y(data_mux2[7])
  );
  NOR _066_ (
    .A(validIn),
    .B(_006_),
    .Y(data_Probador2[0])
  );
  NOR _067_ (
    .A(validIn),
    .B(_007_),
    .Y(data_Probador2[1])
  );
  NOR _068_ (
    .A(validIn),
    .B(_008_),
    .Y(data_Probador2[2])
  );
  NOR _069_ (
    .A(validIn),
    .B(_009_),
    .Y(data_Probador2[3])
  );
  NOR _070_ (
    .A(validIn),
    .B(_010_),
    .Y(data_Probador2[4])
  );
  NOR _071_ (
    .A(validIn),
    .B(_011_),
    .Y(data_Probador2[5])
  );
  NOR _072_ (
    .A(validIn),
    .B(_012_),
    .Y(data_Probador2[6])
  );
  NOR _073_ (
    .A(validIn),
    .B(_013_),
    .Y(data_Probador2[7])
  );
  NAND _074_ (
    .A(validIn),
    .B(In1[0]),
    .Y(_046_)
  );
  NOT _075_ (
    .A(_046_),
    .Y(data_mux1[0])
  );
  NAND _076_ (
    .A(validIn),
    .B(In1[1]),
    .Y(_047_)
  );
  NOT _077_ (
    .A(_047_),
    .Y(data_mux1[1])
  );
  NAND _078_ (
    .A(validIn),
    .B(In1[2]),
    .Y(_048_)
  );
  NOT _079_ (
    .A(_048_),
    .Y(data_mux1[2])
  );
  NAND _080_ (
    .A(validIn),
    .B(In1[3]),
    .Y(_049_)
  );
  NOT _081_ (
    .A(_049_),
    .Y(data_mux1[3])
  );
  NAND _082_ (
    .A(validIn),
    .B(In1[4]),
    .Y(_050_)
  );
  NOT _083_ (
    .A(_050_),
    .Y(data_mux1[4])
  );
  NAND _084_ (
    .A(validIn),
    .B(In1[5]),
    .Y(_051_)
  );
  NOT _085_ (
    .A(_051_),
    .Y(data_mux1[5])
  );
  NAND _086_ (
    .A(validIn),
    .B(In1[6]),
    .Y(_052_)
  );
  NOT _087_ (
    .A(_052_),
    .Y(data_mux1[6])
  );
  NAND _088_ (
    .A(validIn),
    .B(In1[7]),
    .Y(_053_)
  );
  NOT _089_ (
    .A(_053_),
    .Y(data_mux1[7])
  );
  NOR _090_ (
    .A(validIn),
    .B(_014_),
    .Y(data_Probador1[0])
  );
  NOR _091_ (
    .A(validIn),
    .B(_015_),
    .Y(data_Probador1[1])
  );
  NOR _092_ (
    .A(validIn),
    .B(_016_),
    .Y(data_Probador1[2])
  );
  NOR _093_ (
    .A(validIn),
    .B(_017_),
    .Y(data_Probador1[3])
  );
  NOR _094_ (
    .A(validIn),
    .B(_018_),
    .Y(data_Probador1[4])
  );
  NOR _095_ (
    .A(validIn),
    .B(_019_),
    .Y(data_Probador1[5])
  );
  NOR _096_ (
    .A(validIn),
    .B(_020_),
    .Y(data_Probador1[6])
  );
  NOR _097_ (
    .A(validIn),
    .B(_021_),
    .Y(data_Probador1[7])
  );
  NAND _098_ (
    .A(validIn),
    .B(In0[0]),
    .Y(_054_)
  );
  NOT _099_ (
    .A(_054_),
    .Y(data_mux0[0])
  );
  NAND _100_ (
    .A(validIn),
    .B(In0[1]),
    .Y(_055_)
  );
  NOT _101_ (
    .A(_055_),
    .Y(data_mux0[1])
  );
  NAND _102_ (
    .A(validIn),
    .B(In0[2]),
    .Y(_056_)
  );
  NOT _103_ (
    .A(_056_),
    .Y(data_mux0[2])
  );
  NAND _104_ (
    .A(validIn),
    .B(In0[3]),
    .Y(_057_)
  );
  NOT _105_ (
    .A(_057_),
    .Y(data_mux0[3])
  );
  NAND _106_ (
    .A(validIn),
    .B(In0[4]),
    .Y(_058_)
  );
  NOT _107_ (
    .A(_058_),
    .Y(data_mux0[4])
  );
  NAND _108_ (
    .A(validIn),
    .B(In0[5]),
    .Y(_059_)
  );
  NOT _109_ (
    .A(_059_),
    .Y(data_mux0[5])
  );
  NAND _110_ (
    .A(validIn),
    .B(In0[6]),
    .Y(_060_)
  );
  NOT _111_ (
    .A(_060_),
    .Y(data_mux0[6])
  );
  NAND _112_ (
    .A(validIn),
    .B(In0[7]),
    .Y(_061_)
  );
  NOT _113_ (
    .A(_061_),
    .Y(data_mux0[7])
  );
  NOR _114_ (
    .A(validIn),
    .B(_022_),
    .Y(data_Probador0[0])
  );
  NOR _115_ (
    .A(validIn),
    .B(_023_),
    .Y(data_Probador0[1])
  );
  NOR _116_ (
    .A(validIn),
    .B(_024_),
    .Y(data_Probador0[2])
  );
  NOR _117_ (
    .A(validIn),
    .B(_025_),
    .Y(data_Probador0[3])
  );
  NOR _118_ (
    .A(validIn),
    .B(_026_),
    .Y(data_Probador0[4])
  );
  NOR _119_ (
    .A(validIn),
    .B(_027_),
    .Y(data_Probador0[5])
  );
  NOR _120_ (
    .A(validIn),
    .B(_028_),
    .Y(data_Probador0[6])
  );
  NOR _121_ (
    .A(validIn),
    .B(_029_),
    .Y(data_Probador0[7])
  );
  NOT _122_ (
    .A(In3[0]),
    .Y(_062_)
  );
  NOT _123_ (
    .A(In3[1]),
    .Y(_063_)
  );
  NOT _124_ (
    .A(In3[2]),
    .Y(_000_)
  );
  NOT _125_ (
    .A(In3[3]),
    .Y(_001_)
  );
  NOT _126_ (
    .A(In3[4]),
    .Y(_002_)
  );
  NOT _127_ (
    .A(In3[5]),
    .Y(_003_)
  );
  NOT _128_ (
    .A(In3[6]),
    .Y(_004_)
  );
  NOT _129_ (
    .A(In3[7]),
    .Y(_005_)
  );
  NOT _130_ (
    .A(In2[0]),
    .Y(_006_)
  );
  NOT _131_ (
    .A(In2[1]),
    .Y(_007_)
  );
  NOT _132_ (
    .A(In2[2]),
    .Y(_008_)
  );
  NOT _133_ (
    .A(In2[3]),
    .Y(_009_)
  );
  NOT _134_ (
    .A(In2[4]),
    .Y(_010_)
  );
  NOT _135_ (
    .A(In2[5]),
    .Y(_011_)
  );
  NOT _136_ (
    .A(In2[6]),
    .Y(_012_)
  );
  NOT _137_ (
    .A(In2[7]),
    .Y(_013_)
  );
  NOT _138_ (
    .A(In1[0]),
    .Y(_014_)
  );
  NOT _139_ (
    .A(In1[1]),
    .Y(_015_)
  );
  NOT _140_ (
    .A(In1[2]),
    .Y(_016_)
  );
  NOT _141_ (
    .A(In1[3]),
    .Y(_017_)
  );
  NOT _142_ (
    .A(In1[4]),
    .Y(_018_)
  );
  NOT _143_ (
    .A(In1[5]),
    .Y(_019_)
  );
  NOT _144_ (
    .A(In1[6]),
    .Y(_020_)
  );
  NOT _145_ (
    .A(In1[7]),
    .Y(_021_)
  );
  NOT _146_ (
    .A(In0[0]),
    .Y(_022_)
  );
  NOT _147_ (
    .A(In0[1]),
    .Y(_023_)
  );
  NOT _148_ (
    .A(In0[2]),
    .Y(_024_)
  );
  NOT _149_ (
    .A(In0[3]),
    .Y(_025_)
  );
  NOT _150_ (
    .A(In0[4]),
    .Y(_026_)
  );
  NOT _151_ (
    .A(In0[5]),
    .Y(_027_)
  );
  NOT _152_ (
    .A(In0[6]),
    .Y(_028_)
  );
  NOT _153_ (
    .A(In0[7]),
    .Y(_029_)
  );
  NAND _154_ (
    .A(In3[0]),
    .B(validIn),
    .Y(_030_)
  );
  NOT _155_ (
    .A(_030_),
    .Y(data_mux3[0])
  );
  NAND _156_ (
    .A(validIn),
    .B(In3[1]),
    .Y(_031_)
  );
  NOT _157_ (
    .A(_031_),
    .Y(data_mux3[1])
  );
  NAND _158_ (
    .A(validIn),
    .B(In3[2]),
    .Y(_032_)
  );
  NOT _159_ (
    .A(_032_),
    .Y(data_mux3[2])
  );
  NAND _160_ (
    .A(validIn),
    .B(In3[3]),
    .Y(_033_)
  );
  NOT _161_ (
    .A(_033_),
    .Y(data_mux3[3])
  );
  NAND _162_ (
    .A(validIn),
    .B(In3[4]),
    .Y(_034_)
  );
  NOT _163_ (
    .A(_034_),
    .Y(data_mux3[4])
  );
  NAND _164_ (
    .A(validIn),
    .B(In3[5]),
    .Y(_035_)
  );
  NOT _165_ (
    .A(_035_),
    .Y(data_mux3[5])
  );
  NAND _166_ (
    .A(validIn),
    .B(In3[6]),
    .Y(_036_)
  );
  NOT _167_ (
    .A(_036_),
    .Y(data_mux3[6])
  );
  NAND _168_ (
    .A(validIn),
    .B(In3[7]),
    .Y(_037_)
  );
  NOT _169_ (
    .A(_037_),
    .Y(data_mux3[7])
  );
  NOR _170_ (
    .A(_062_),
    .B(validIn),
    .Y(data_Probador3[0])
  );
  NOR _171_ (
    .A(validIn),
    .B(_063_),
    .Y(data_Probador3[1])
  );
  NOR _172_ (
    .A(validIn),
    .B(_000_),
    .Y(data_Probador3[2])
  );
  NOR _173_ (
    .A(validIn),
    .B(_001_),
    .Y(data_Probador3[3])
  );
  NOR _174_ (
    .A(validIn),
    .B(_002_),
    .Y(data_Probador3[4])
  );
  NOR _175_ (
    .A(validIn),
    .B(_003_),
    .Y(data_Probador3[5])
  );
  NOR _176_ (
    .A(validIn),
    .B(_004_),
    .Y(data_Probador3[6])
  );
  NOR _177_ (
    .A(validIn),
    .B(_005_),
    .Y(data_Probador3[7])
  );
  NAND _178_ (
    .A(validIn),
    .B(In2[0]),
    .Y(_038_)
  );
  NOT _179_ (
    .A(_038_),
    .Y(data_mux2[0])
  );
  NAND _180_ (
    .A(validIn),
    .B(In2[1]),
    .Y(_039_)
  );
  NOT _181_ (
    .A(_039_),
    .Y(data_mux2[1])
  );
  NAND _182_ (
    .A(validIn),
    .B(In2[2]),
    .Y(_040_)
  );
  NOT _183_ (
    .A(_040_),
    .Y(data_mux2[2])
  );
  NAND _184_ (
    .A(validIn),
    .B(In2[3]),
    .Y(_041_)
  );
  NOT _185_ (
    .A(_041_),
    .Y(data_mux2[3])
  );
  NAND _186_ (
    .A(validIn),
    .B(In2[4]),
    .Y(_042_)
  );
  NOT _187_ (
    .A(_042_),
    .Y(data_mux2[4])
  );
  NAND _188_ (
    .A(validIn),
    .B(In2[5]),
    .Y(_043_)
  );
  NOT _189_ (
    .A(_043_),
    .Y(data_mux2[5])
  );
  NAND _190_ (
    .A(validIn),
    .B(In2[6]),
    .Y(_044_)
  );
  NOT _191_ (
    .A(_044_),
    .Y(data_mux2[6])
  );
endmodule

(* top =  1  *)
(* src = "phy_tx_estruct.v:4.1-102.10" *)
module phy_tx_estruct(In0, In1, In2, In3, clk, clk_2f, clk_4f, valid0, valid1, valid2, valid3, validIn, reset, data_PSA_estruct, valid_PSA_estruct, data_Probador0, data_Probador1, data_Probador2, data_Probador3);
  (* src = "phy_tx_estruct.v:5.17-5.20" *)
  input [7:0] In0;
  (* src = "phy_tx_estruct.v:30.12-30.20" *)
  wire [7:0] In0_good;
  (* src = "phy_tx_estruct.v:6.17-6.20" *)
  input [7:0] In1;
  (* src = "phy_tx_estruct.v:30.22-30.30" *)
  wire [7:0] In1_good;
  (* src = "phy_tx_estruct.v:7.17-7.20" *)
  input [7:0] In2;
  (* src = "phy_tx_estruct.v:30.32-30.40" *)
  wire [7:0] In2_good;
  (* src = "phy_tx_estruct.v:8.17-8.20" *)
  input [7:0] In3;
  (* src = "phy_tx_estruct.v:30.42-30.50" *)
  wire [7:0] In3_good;
  (* src = "phy_tx_estruct.v:9.11-9.14" *)
  input clk;
  (* src = "phy_tx_estruct.v:10.11-10.17" *)
  input clk_2f;
  (* src = "phy_tx_estruct.v:11.11-11.17" *)
  input clk_4f;
  (* src = "phy_tx_estruct.v:15.18-15.37" *)
  output [7:0] data_PSA_estruct;
  (* src = "phy_tx_estruct.v:19.18-19.32" *)
  output [7:0] data_Probador0;
  (* src = "phy_tx_estruct.v:20.18-20.32" *)
  output [7:0] data_Probador1;
  (* src = "phy_tx_estruct.v:21.18-21.32" *)
  output [7:0] data_Probador2;
  (* src = "phy_tx_estruct.v:22.18-22.32" *)
  output [7:0] data_Probador3;
  (* src = "phy_tx_estruct.v:27.12-27.21" *)
  wire [7:0] out_temp1;
  (* src = "phy_tx_estruct.v:27.23-27.32" *)
  wire [7:0] out_temp2;
  (* src = "phy_tx_estruct.v:14.11-14.16" *)
  input reset;
  (* src = "phy_tx_estruct.v:12.11-12.17" *)
  input valid0;
  (* src = "phy_tx_estruct.v:12.19-12.25" *)
  input valid1;
  (* src = "phy_tx_estruct.v:12.27-12.33" *)
  input valid2;
  (* src = "phy_tx_estruct.v:12.35-12.41" *)
  input valid3;
  (* src = "phy_tx_estruct.v:13.11-13.18" *)
  input validIn;
  (* src = "phy_tx_estruct.v:16.12-16.32" *)
  output valid_PSA_estruct;
  (* src = "phy_tx_estruct.v:28.6-28.17" *)
  wire valid_out_1;
  (* src = "phy_tx_estruct.v:28.19-28.30" *)
  wire valid_out_2;
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_estruct.v:63.14-72.2" *)
  Mux2x1_8Bits_estruct MUX2x1_1 (
    .In0(In1_good),
    .In1(In0_good),
    .clk(clk_2f),
    .data_out(out_temp1),
    .outValid(valid_out_1),
    .reset(reset),
    .valid0(valid1),
    .valid1(valid0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_estruct.v:74.14-83.2" *)
  Mux2x1_8Bits_estruct MUX2x1_2 (
    .In0(In3_good),
    .In1(In2_good),
    .clk(clk_2f),
    .data_out(out_temp2),
    .outValid(valid_out_2),
    .reset(reset),
    .valid0(valid3),
    .valid1(valid2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_estruct.v:90.14-99.2" *)
  Mux2x1_8Bits_estruct MUX2x1_3 (
    .In0(out_temp2),
    .In1(out_temp1),
    .clk(clk_4f),
    .data_out(data_PSA_estruct),
    .outValid(valid_PSA_estruct),
    .reset(reset),
    .valid0(valid_out_2),
    .valid1(valid_out_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_estruct.v:38.15-52.2" *)
  Recirculacion_estruct Recirculacion_testbench (
    .In0(In0),
    .In1(In1),
    .In2(In2),
    .In3(In3),
    .data_Probador0(data_Probador0),
    .data_Probador1(data_Probador1),
    .data_Probador2(data_Probador2),
    .data_Probador3(data_Probador3),
    .data_mux0(In0_good),
    .data_mux1(In1_good),
    .data_mux2(In2_good),
    .data_mux3(In3_good),
    .validIn(validIn)
  );
endmodule
