/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "Recirculacion_estruct.v:1.1-75.10" *)
module Recirculacion_estruct(In0, In1, In2, In3, validIn, data_mux0, data_Probador0, data_mux1, data_Probador1, data_mux2, data_Probador2, data_mux3, data_Probador3);
  (* src = "Recirculacion_estruct.v:2.17-2.20" *)
  input [7:0] In0;
  (* src = "Recirculacion_estruct.v:2.22-2.25" *)
  input [7:0] In1;
  (* src = "Recirculacion_estruct.v:2.27-2.30" *)
  input [7:0] In2;
  (* src = "Recirculacion_estruct.v:2.32-2.35" *)
  input [7:0] In3;
  (* src = "Recirculacion_estruct.v:5.22-5.36" *)
  output [7:0] data_Probador0;
  (* src = "Recirculacion_estruct.v:7.22-7.36" *)
  output [7:0] data_Probador1;
  (* src = "Recirculacion_estruct.v:9.22-9.36" *)
  output [7:0] data_Probador2;
  (* src = "Recirculacion_estruct.v:11.22-11.36" *)
  output [7:0] data_Probador3;
  (* src = "Recirculacion_estruct.v:4.22-4.31" *)
  output [7:0] data_mux0;
  (* src = "Recirculacion_estruct.v:6.22-6.31" *)
  output [7:0] data_mux1;
  (* src = "Recirculacion_estruct.v:8.22-8.31" *)
  output [7:0] data_mux2;
  (* src = "Recirculacion_estruct.v:10.22-10.31" *)
  output [7:0] data_mux3;
  (* src = "Recirculacion_estruct.v:3.11-3.18" *)
  input validIn;
  assign data_mux3 = validIn ? (* full_case = 32'd1 *) (* src = "Recirculacion_estruct.v:64.12-64.24|Recirculacion.v:64.9-71.12" *) In3 : 8'h00;
  assign data_Probador3 = validIn ? (* full_case = 32'd1 *) (* src = "Recirculacion_estruct.v:64.12-64.24|Recirculacion.v:64.9-71.12" *) 8'h00 : In3;
  assign data_mux2 = validIn ? (* full_case = 32'd1 *) (* src = "Recirculacion_estruct.v:49.12-49.24|Recirculacion.v:49.9-56.12" *) In2 : 8'h00;
  assign data_Probador2 = validIn ? (* full_case = 32'd1 *) (* src = "Recirculacion_estruct.v:49.12-49.24|Recirculacion.v:49.9-56.12" *) 8'h00 : In2;
  assign data_mux1 = validIn ? (* full_case = 32'd1 *) (* src = "Recirculacion_estruct.v:34.12-34.24|Recirculacion.v:34.9-41.12" *) In1 : 8'h00;
  assign data_Probador1 = validIn ? (* full_case = 32'd1 *) (* src = "Recirculacion_estruct.v:34.12-34.24|Recirculacion.v:34.9-41.12" *) 8'h00 : In1;
  assign data_mux0 = validIn ? (* full_case = 32'd1 *) (* src = "Recirculacion_estruct.v:19.12-19.24|Recirculacion.v:19.9-26.12" *) In0 : 8'h00;
  assign data_Probador0 = validIn ? (* full_case = 32'd1 *) (* src = "Recirculacion_estruct.v:19.12-19.24|Recirculacion.v:19.9-26.12" *) 8'h00 : In0;
endmodule
