/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* src = "Demux_1x2_8Bits_estructural.v:1" *)
module Demux_1x2_8Bits_estructural(In, clk_2f, validIn, reset, outValid0_estructural, outValid1_estructural, data_out0_estructural, data_out1_estructural);
  (* src = "Demux_1x2_8Bits_estructural.v:27" *)
  wire [7:0] _000_;
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  wire [7:0] _001_;
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  wire _002_;
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  (* src = "Demux_1x2_8Bits_estructural.v:2" *)
  input [7:0] In;
  (* src = "Demux_1x2_8Bits_estructural.v:9" *)
  wire [7:0] ValorAnterior_out1;
  (* src = "Demux_1x2_8Bits_estructural.v:3" *)
  input clk_2f;
  (* src = "Demux_1x2_8Bits_estructural.v:5" *)
  output [7:0] data_out0_estructural;
  (* src = "Demux_1x2_8Bits_estructural.v:5" *)
  output [7:0] data_out1_estructural;
  (* src = "Demux_1x2_8Bits_estructural.v:4" *)
  output outValid0_estructural;
  (* src = "Demux_1x2_8Bits_estructural.v:4" *)
  output outValid1_estructural;
  (* src = "Demux_1x2_8Bits_estructural.v:3" *)
  input reset;
  (* src = "Demux_1x2_8Bits_estructural.v:3" *)
  input validIn;
  (* src = "Demux_1x2_8Bits_estructural.v:10" *)
  wire validTemp_In1;
  NOT _031_ (
    .A(clk_2f),
    .Y(_012_)
  );
  NOT _032_ (
    .A(ValorAnterior_out1[0]),
    .Y(_013_)
  );
  NOT _033_ (
    .A(ValorAnterior_out1[1]),
    .Y(_014_)
  );
  NOT _034_ (
    .A(ValorAnterior_out1[2]),
    .Y(_015_)
  );
  NOT _035_ (
    .A(ValorAnterior_out1[3]),
    .Y(_016_)
  );
  NOT _036_ (
    .A(ValorAnterior_out1[4]),
    .Y(_017_)
  );
  NOT _037_ (
    .A(ValorAnterior_out1[5]),
    .Y(_018_)
  );
  NOT _038_ (
    .A(ValorAnterior_out1[6]),
    .Y(_019_)
  );
  NOT _039_ (
    .A(ValorAnterior_out1[7]),
    .Y(_020_)
  );
  NOT _040_ (
    .A(validTemp_In1),
    .Y(_021_)
  );
  NOT _041_ (
    .A(In[0]),
    .Y(_022_)
  );
  NOT _042_ (
    .A(In[1]),
    .Y(_023_)
  );
  NOT _043_ (
    .A(In[2]),
    .Y(_024_)
  );
  NOT _044_ (
    .A(In[3]),
    .Y(_025_)
  );
  NOT _045_ (
    .A(In[4]),
    .Y(_026_)
  );
  NOT _046_ (
    .A(In[5]),
    .Y(_027_)
  );
  NOT _047_ (
    .A(In[6]),
    .Y(_028_)
  );
  NOT _048_ (
    .A(In[7]),
    .Y(_029_)
  );
  NOT _049_ (
    .A(validIn),
    .Y(_030_)
  );
  NOR _050_ (
    .A(_013_),
    .B(reset),
    .Y(_001_[0])
  );
  NOR _051_ (
    .A(reset),
    .B(_014_),
    .Y(_001_[1])
  );
  NOR _052_ (
    .A(reset),
    .B(_015_),
    .Y(_001_[2])
  );
  NOR _053_ (
    .A(reset),
    .B(_016_),
    .Y(_001_[3])
  );
  NOR _054_ (
    .A(reset),
    .B(_017_),
    .Y(_001_[4])
  );
  NOR _055_ (
    .A(reset),
    .B(_018_),
    .Y(_001_[5])
  );
  NOR _056_ (
    .A(reset),
    .B(_019_),
    .Y(_001_[6])
  );
  NOR _057_ (
    .A(reset),
    .B(_020_),
    .Y(_001_[7])
  );
  NOR _058_ (
    .A(reset),
    .B(_021_),
    .Y(_002_)
  );
  NOR _059_ (
    .A(reset),
    .B(_022_),
    .Y(_000_[0])
  );
  NOR _060_ (
    .A(reset),
    .B(_023_),
    .Y(_000_[1])
  );
  NOR _061_ (
    .A(reset),
    .B(_024_),
    .Y(_000_[2])
  );
  NOR _062_ (
    .A(reset),
    .B(_025_),
    .Y(_000_[3])
  );
  NOR _063_ (
    .A(reset),
    .B(_026_),
    .Y(_000_[4])
  );
  NOR _064_ (
    .A(reset),
    .B(_027_),
    .Y(_000_[5])
  );
  NOR _065_ (
    .A(reset),
    .B(_028_),
    .Y(_000_[6])
  );
  NOR _066_ (
    .A(reset),
    .B(_029_),
    .Y(_000_[7])
  );
  NOR _067_ (
    .A(reset),
    .B(_030_),
    .Y(_003_)
  );
  NOT _068_ (
    .A(clk_2f),
    .Y(_004_)
  );
  NOT _069_ (
    .A(clk_2f),
    .Y(_005_)
  );
  NOT _070_ (
    .A(clk_2f),
    .Y(_006_)
  );
  NOT _071_ (
    .A(clk_2f),
    .Y(_007_)
  );
  NOT _072_ (
    .A(clk_2f),
    .Y(_008_)
  );
  NOT _073_ (
    .A(clk_2f),
    .Y(_009_)
  );
  NOT _074_ (
    .A(clk_2f),
    .Y(_010_)
  );
  NOT _075_ (
    .A(clk_2f),
    .Y(_011_)
  );
  (* src = "Demux_1x2_8Bits_estructural.v:27" *)
  DFF _076_ (
    .C(_004_),
    .D(_000_[7]),
    .Q(ValorAnterior_out1[7])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:27" *)
  DFF _077_ (
    .C(_005_),
    .D(_003_),
    .Q(validTemp_In1)
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _078_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(data_out0_estructural[0])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _079_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(data_out0_estructural[1])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _080_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(data_out0_estructural[2])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _081_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(data_out0_estructural[3])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _082_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(data_out0_estructural[4])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _083_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(data_out0_estructural[5])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _084_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(data_out0_estructural[6])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _085_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(data_out0_estructural[7])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _086_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(data_out1_estructural[0])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _087_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(data_out1_estructural[1])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _088_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(data_out1_estructural[2])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _089_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(data_out1_estructural[3])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _090_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(data_out1_estructural[4])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _091_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(data_out1_estructural[5])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _092_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(data_out1_estructural[6])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _093_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(data_out1_estructural[7])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _094_ (
    .C(clk_2f),
    .D(_002_),
    .Q(outValid0_estructural)
  );
  (* src = "Demux_1x2_8Bits_estructural.v:12" *)
  DFF _095_ (
    .C(clk_2f),
    .D(_003_),
    .Q(outValid1_estructural)
  );
  (* src = "Demux_1x2_8Bits_estructural.v:27" *)
  DFF _096_ (
    .C(_006_),
    .D(_000_[0]),
    .Q(ValorAnterior_out1[0])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:27" *)
  DFF _097_ (
    .C(_007_),
    .D(_000_[1]),
    .Q(ValorAnterior_out1[1])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:27" *)
  DFF _098_ (
    .C(_008_),
    .D(_000_[2]),
    .Q(ValorAnterior_out1[2])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:27" *)
  DFF _099_ (
    .C(_009_),
    .D(_000_[3]),
    .Q(ValorAnterior_out1[3])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:27" *)
  DFF _100_ (
    .C(_010_),
    .D(_000_[4]),
    .Q(ValorAnterior_out1[4])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:27" *)
  DFF _101_ (
    .C(_011_),
    .D(_000_[5]),
    .Q(ValorAnterior_out1[5])
  );
  (* src = "Demux_1x2_8Bits_estructural.v:27" *)
  DFF _102_ (
    .C(_012_),
    .D(_000_[6]),
    .Q(ValorAnterior_out1[6])
  );
endmodule

(* top =  1  *)
(* src = "Demux_1x4_8Bits_estructural.v:3" *)
module Demux_1x4_8Bits_estructural(data2send_to_LDMX_estruct, clk_4f, clk_2f, clk, valid_out_to_LDMX_estruct, reset, outValid0_estructural, outValid1_estructural, outValid2_estructural, outValid3_estructural, data_out0_estructural, data_out1_estructural, data_out2_estructural, data_out3_estructural);
  (* src = "Demux_1x4_8Bits_estructural.v:33" *)
  wire _0_;
  (* src = "Demux_1x4_8Bits_estructural.v:6" *)
  input clk;
  (* src = "Demux_1x4_8Bits_estructural.v:6" *)
  input clk_2f;
  (* src = "Demux_1x4_8Bits_estructural.v:6" *)
  input clk_4f;
  (* src = "Demux_1x4_8Bits_estructural.v:5" *)
  input [7:0] data2send_to_LDMX_estruct;
  (* src = "Demux_1x4_8Bits_estructural.v:8" *)
  output [7:0] data_out0_estructural;
  (* src = "Demux_1x4_8Bits_estructural.v:8" *)
  output [7:0] data_out1_estructural;
  (* src = "Demux_1x4_8Bits_estructural.v:8" *)
  output [7:0] data_out2_estructural;
  (* src = "Demux_1x4_8Bits_estructural.v:8" *)
  output [7:0] data_out3_estructural;
  (* src = "Demux_1x4_8Bits_estructural.v:7" *)
  output outValid0_estructural;
  (* src = "Demux_1x4_8Bits_estructural.v:7" *)
  output outValid1_estructural;
  (* src = "Demux_1x4_8Bits_estructural.v:7" *)
  output outValid2_estructural;
  (* src = "Demux_1x4_8Bits_estructural.v:7" *)
  output outValid3_estructural;
  (* src = "Demux_1x4_8Bits_estructural.v:6" *)
  input reset;
  (* src = "Demux_1x4_8Bits_estructural.v:12" *)
  wire [7:0] salida0Demux1;
  (* src = "Demux_1x4_8Bits_estructural.v:12" *)
  wire [7:0] salida1Demux1;
  (* src = "Demux_1x4_8Bits_estructural.v:13" *)
  wire valid0Temp;
  (* src = "Demux_1x4_8Bits_estructural.v:13" *)
  wire valid1Temp;
  (* src = "Demux_1x4_8Bits_estructural.v:6" *)
  input valid_out_to_LDMX_estruct;
  NOT _1_ (
    .A(clk),
    .Y(_0_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Demux_1x4_8Bits_estructural.v:17" *)
  Demux_1x2_8Bits_estructural Demux1 (
    .In(data2send_to_LDMX_estruct),
    .clk_2f(clk_2f),
    .data_out0_estructural(salida0Demux1),
    .data_out1_estructural(salida1Demux1),
    .outValid0_estructural(valid0Temp),
    .outValid1_estructural(valid1Temp),
    .reset(reset),
    .validIn(valid_out_to_LDMX_estruct)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Demux_1x4_8Bits_estructural.v:31" *)
  Demux_1x2_8Bits_estructural Demux2 (
    .In(salida0Demux1),
    .clk_2f(_0_),
    .data_out0_estructural(data_out0_estructural),
    .data_out1_estructural(data_out2_estructural),
    .outValid0_estructural(outValid0_estructural),
    .outValid1_estructural(outValid2_estructural),
    .reset(reset),
    .validIn(valid0Temp)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Demux_1x4_8Bits_estructural.v:42" *)
  Demux_1x2_8Bits_estructural Demux3 (
    .In(salida1Demux1),
    .clk_2f(_0_),
    .data_out0_estructural(data_out1_estructural),
    .data_out1_estructural(data_out3_estructural),
    .outValid0_estructural(outValid1_estructural),
    .outValid1_estructural(outValid3_estructural),
    .reset(reset),
    .validIn(valid1Temp)
  );
endmodule
