/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "Mux2x1_8Bits_estruct.v:3" *)
module Mux2x1_8Bits_estruct(In0, In1, clk, valid0, valid1, reset, outValid, data_out);
  (* src = "Mux2x1_8Bits_estruct.v:35" *)
  wire [7:0] _000_;
  (* src = "Mux2x1_8Bits_estruct.v:35" *)
  wire _001_;
  (* src = "Mux2x1_8Bits_estruct.v:35" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  (* src = "Mux2x1_8Bits_estruct.v:4" *)
  input [7:0] In0;
  (* src = "Mux2x1_8Bits_estruct.v:4" *)
  input [7:0] In1;
  (* src = "Mux2x1_8Bits_estruct.v:5" *)
  input clk;
  (* src = "Mux2x1_8Bits_estruct.v:8" *)
  output [7:0] data_out;
  (* src = "Mux2x1_8Bits_estruct.v:7" *)
  output outValid;
  (* src = "Mux2x1_8Bits_estruct.v:6" *)
  input reset;
  (* src = "Mux2x1_8Bits_estruct.v:13" *)
  wire selector;
  (* src = "Mux2x1_8Bits_estruct.v:5" *)
  input valid0;
  (* src = "Mux2x1_8Bits_estruct.v:5" *)
  input valid1;
  NOT _053_ (
    .A(valid0),
    .Y(_003_)
  );
  NOT _054_ (
    .A(selector),
    .Y(_004_)
  );
  NOR _055_ (
    .A(reset),
    .B(selector),
    .Y(_002_)
  );
  NOR _056_ (
    .A(_003_),
    .B(selector),
    .Y(_005_)
  );
  NAND _057_ (
    .A(valid0),
    .B(_004_),
    .Y(_006_)
  );
  NOR _058_ (
    .A(In0[0]),
    .B(_006_),
    .Y(_007_)
  );
  NAND _059_ (
    .A(valid1),
    .B(selector),
    .Y(_008_)
  );
  NOT _060_ (
    .A(_008_),
    .Y(_009_)
  );
  NOR _061_ (
    .A(In1[0]),
    .B(_008_),
    .Y(_010_)
  );
  NOR _062_ (
    .A(_007_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _063_ (
    .A(reset),
    .B(_011_),
    .Y(_012_)
  );
  NOR _064_ (
    .A(_005_),
    .B(_009_),
    .Y(_013_)
  );
  NOR _065_ (
    .A(reset),
    .B(_013_),
    .Y(_014_)
  );
  NOT _066_ (
    .A(_014_),
    .Y(_015_)
  );
  NOR _067_ (
    .A(data_out[0]),
    .B(_014_),
    .Y(_016_)
  );
  NOR _068_ (
    .A(_012_),
    .B(_016_),
    .Y(_000_[0])
  );
  NOR _069_ (
    .A(In0[1]),
    .B(_006_),
    .Y(_017_)
  );
  NOR _070_ (
    .A(In1[1]),
    .B(_008_),
    .Y(_018_)
  );
  NOR _071_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _072_ (
    .A(reset),
    .B(_019_),
    .Y(_020_)
  );
  NOR _073_ (
    .A(data_out[1]),
    .B(_014_),
    .Y(_021_)
  );
  NOR _074_ (
    .A(_020_),
    .B(_021_),
    .Y(_000_[1])
  );
  NOR _075_ (
    .A(In0[2]),
    .B(_006_),
    .Y(_022_)
  );
  NOR _076_ (
    .A(In1[2]),
    .B(_008_),
    .Y(_023_)
  );
  NOR _077_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  NOR _078_ (
    .A(reset),
    .B(_024_),
    .Y(_025_)
  );
  NOR _079_ (
    .A(data_out[2]),
    .B(_014_),
    .Y(_026_)
  );
  NOR _080_ (
    .A(_025_),
    .B(_026_),
    .Y(_000_[2])
  );
  NOR _081_ (
    .A(In0[3]),
    .B(_006_),
    .Y(_027_)
  );
  NOR _082_ (
    .A(In1[3]),
    .B(_008_),
    .Y(_028_)
  );
  NOR _083_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _084_ (
    .A(reset),
    .B(_029_),
    .Y(_030_)
  );
  NOR _085_ (
    .A(data_out[3]),
    .B(_014_),
    .Y(_031_)
  );
  NOR _086_ (
    .A(_030_),
    .B(_031_),
    .Y(_000_[3])
  );
  NOR _087_ (
    .A(In0[4]),
    .B(_006_),
    .Y(_032_)
  );
  NOR _088_ (
    .A(In1[4]),
    .B(_008_),
    .Y(_033_)
  );
  NOR _089_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _090_ (
    .A(reset),
    .B(_034_),
    .Y(_035_)
  );
  NOR _091_ (
    .A(data_out[4]),
    .B(_014_),
    .Y(_036_)
  );
  NOR _092_ (
    .A(_035_),
    .B(_036_),
    .Y(_000_[4])
  );
  NOR _093_ (
    .A(In0[5]),
    .B(_006_),
    .Y(_037_)
  );
  NOR _094_ (
    .A(In1[5]),
    .B(_008_),
    .Y(_038_)
  );
  NOR _095_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _096_ (
    .A(reset),
    .B(_039_),
    .Y(_040_)
  );
  NOR _097_ (
    .A(data_out[5]),
    .B(_014_),
    .Y(_041_)
  );
  NOR _098_ (
    .A(_040_),
    .B(_041_),
    .Y(_000_[5])
  );
  NOR _099_ (
    .A(In0[6]),
    .B(_006_),
    .Y(_042_)
  );
  NOR _100_ (
    .A(In1[6]),
    .B(_008_),
    .Y(_043_)
  );
  NOR _101_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  NOR _102_ (
    .A(reset),
    .B(_044_),
    .Y(_045_)
  );
  NOR _103_ (
    .A(data_out[6]),
    .B(_014_),
    .Y(_046_)
  );
  NOR _104_ (
    .A(_045_),
    .B(_046_),
    .Y(_000_[6])
  );
  NOR _105_ (
    .A(In0[7]),
    .B(_006_),
    .Y(_047_)
  );
  NOR _106_ (
    .A(In1[7]),
    .B(_008_),
    .Y(_048_)
  );
  NOR _107_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _108_ (
    .A(reset),
    .B(_049_),
    .Y(_050_)
  );
  NOR _109_ (
    .A(data_out[7]),
    .B(_014_),
    .Y(_051_)
  );
  NOR _110_ (
    .A(_050_),
    .B(_051_),
    .Y(_000_[7])
  );
  NAND _111_ (
    .A(reset),
    .B(outValid),
    .Y(_052_)
  );
  NAND _112_ (
    .A(_015_),
    .B(_052_),
    .Y(_001_)
  );
  (* src = "Mux2x1_8Bits_estruct.v:35" *)
  DFF _113_ (
    .C(clk),
    .D(_001_),
    .Q(outValid)
  );
  (* src = "Mux2x1_8Bits_estruct.v:35" *)
  DFF _114_ (
    .C(clk),
    .D(_000_[0]),
    .Q(data_out[0])
  );
  (* src = "Mux2x1_8Bits_estruct.v:35" *)
  DFF _115_ (
    .C(clk),
    .D(_000_[1]),
    .Q(data_out[1])
  );
  (* src = "Mux2x1_8Bits_estruct.v:35" *)
  DFF _116_ (
    .C(clk),
    .D(_000_[2]),
    .Q(data_out[2])
  );
  (* src = "Mux2x1_8Bits_estruct.v:35" *)
  DFF _117_ (
    .C(clk),
    .D(_000_[3]),
    .Q(data_out[3])
  );
  (* src = "Mux2x1_8Bits_estruct.v:35" *)
  DFF _118_ (
    .C(clk),
    .D(_000_[4]),
    .Q(data_out[4])
  );
  (* src = "Mux2x1_8Bits_estruct.v:35" *)
  DFF _119_ (
    .C(clk),
    .D(_000_[5]),
    .Q(data_out[5])
  );
  (* src = "Mux2x1_8Bits_estruct.v:35" *)
  DFF _120_ (
    .C(clk),
    .D(_000_[6]),
    .Q(data_out[6])
  );
  (* src = "Mux2x1_8Bits_estruct.v:35" *)
  DFF _121_ (
    .C(clk),
    .D(_000_[7]),
    .Q(data_out[7])
  );
  (* src = "Mux2x1_8Bits_estruct.v:35" *)
  DFF _122_ (
    .C(clk),
    .D(_002_),
    .Q(selector)
  );
endmodule
