/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "ParaleloSerial_verde_estruct.v:1" *)
module ParaleloSerial_verde_estruct(clk_4f, clk_32f, active_to_PS, reset, data_out_estruct);
  (* src = "ParaleloSerial_verde_estruct.v:10" *)
  wire _00_;
  (* src = "ParaleloSerial_verde_estruct.v:10" *)
  wire [2:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  (* src = "ParaleloSerial_verde_estruct.v:2" *)
  input active_to_PS;
  (* src = "ParaleloSerial_verde_estruct.v:2" *)
  input clk_32f;
  (* src = "ParaleloSerial_verde_estruct.v:2" *)
  input clk_4f;
  (* src = "ParaleloSerial_verde_estruct.v:4" *)
  output data_out_estruct;
  (* src = "ParaleloSerial_verde_estruct.v:3" *)
  input reset;
  (* src = "ParaleloSerial_verde_estruct.v:7" *)
  wire [2:0] selector;
  NOT _18_ (
    .A(selector[0]),
    .Y(_02_)
  );
  NOT _19_ (
    .A(selector[1]),
    .Y(_03_)
  );
  NOT _20_ (
    .A(selector[2]),
    .Y(_04_)
  );
  NOT _21_ (
    .A(reset),
    .Y(_05_)
  );
  NOR _22_ (
    .A(selector[0]),
    .B(reset),
    .Y(_01_[0])
  );
  NAND _23_ (
    .A(selector[0]),
    .B(_03_),
    .Y(_06_)
  );
  NOR _24_ (
    .A(selector[0]),
    .B(_03_),
    .Y(_07_)
  );
  NOR _25_ (
    .A(reset),
    .B(_07_),
    .Y(_08_)
  );
  NAND _26_ (
    .A(_06_),
    .B(_08_),
    .Y(_01_[1])
  );
  NAND _27_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_09_)
  );
  NAND _28_ (
    .A(_04_),
    .B(_09_),
    .Y(_10_)
  );
  NAND _29_ (
    .A(selector[1]),
    .B(selector[2]),
    .Y(_11_)
  );
  NAND _30_ (
    .A(_05_),
    .B(_11_),
    .Y(_12_)
  );
  NOR _31_ (
    .A(_02_),
    .B(_11_),
    .Y(_13_)
  );
  NAND _32_ (
    .A(_05_),
    .B(_10_),
    .Y(_14_)
  );
  NOR _33_ (
    .A(_13_),
    .B(_14_),
    .Y(_01_[2])
  );
  NOR _34_ (
    .A(selector[2]),
    .B(active_to_PS),
    .Y(_15_)
  );
  NOT _35_ (
    .A(_15_),
    .Y(_16_)
  );
  NOR _36_ (
    .A(_06_),
    .B(_16_),
    .Y(_17_)
  );
  NOR _37_ (
    .A(_12_),
    .B(_17_),
    .Y(_00_)
  );
  (* src = "ParaleloSerial_verde_estruct.v:10" *)
  DFF _38_ (
    .C(clk_32f),
    .D(_00_),
    .Q(data_out_estruct)
  );
  (* src = "ParaleloSerial_verde_estruct.v:10" *)
  DFF _39_ (
    .C(clk_32f),
    .D(_01_[0]),
    .Q(selector[0])
  );
  (* src = "ParaleloSerial_verde_estruct.v:10" *)
  DFF _40_ (
    .C(clk_32f),
    .D(_01_[1]),
    .Q(selector[1])
  );
  (* src = "ParaleloSerial_verde_estruct.v:10" *)
  DFF _41_ (
    .C(clk_32f),
    .D(_01_[2]),
    .Q(selector[2])
  );
endmodule
