/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "ParaleloSerial_azul_estruct.v:1" *)
module ParaleloSerial_azul_estruct(data_PSA_estruct, clk_4f, clk_32f, valid_PSA_estruct, reset, data_out_estruct);
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  wire [7:0] _000_;
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  wire _001_;
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  wire _002_;
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  wire _003_;
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  wire [2:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  (* src = "ParaleloSerial_azul_estruct.v:3" *)
  input clk_32f;
  (* src = "ParaleloSerial_azul_estruct.v:3" *)
  input clk_4f;
  (* src = "ParaleloSerial_azul_estruct.v:8" *)
  wire [7:0] data2send;
  (* src = "ParaleloSerial_azul_estruct.v:2" *)
  input [7:0] data_PSA_estruct;
  (* src = "ParaleloSerial_azul_estruct.v:5" *)
  output data_out_estruct;
  (* src = "ParaleloSerial_azul_estruct.v:10" *)
  wire idontknow;
  (* src = "ParaleloSerial_azul_estruct.v:10" *)
  wire lastbit;
  (* src = "ParaleloSerial_azul_estruct.v:4" *)
  input reset;
  (* src = "ParaleloSerial_azul_estruct.v:9" *)
  wire [2:0] selector;
  (* src = "ParaleloSerial_azul_estruct.v:3" *)
  input valid_PSA_estruct;
  NOT _088_ (
    .A(selector[1]),
    .Y(_034_)
  );
  NOT _089_ (
    .A(selector[0]),
    .Y(_035_)
  );
  NOT _090_ (
    .A(data2send[1]),
    .Y(_036_)
  );
  NOT _091_ (
    .A(reset),
    .Y(_037_)
  );
  NOT _092_ (
    .A(data2send[0]),
    .Y(_038_)
  );
  NOT _093_ (
    .A(valid_PSA_estruct),
    .Y(_039_)
  );
  NOT _094_ (
    .A(data_PSA_estruct[5]),
    .Y(_040_)
  );
  NOT _095_ (
    .A(data2send[5]),
    .Y(_041_)
  );
  NOR _096_ (
    .A(selector[1]),
    .B(selector[0]),
    .Y(_042_)
  );
  NOT _097_ (
    .A(_042_),
    .Y(_043_)
  );
  NOR _098_ (
    .A(selector[2]),
    .B(_043_),
    .Y(_044_)
  );
  NOR _099_ (
    .A(idontknow),
    .B(_044_),
    .Y(_045_)
  );
  NAND _100_ (
    .A(_036_),
    .B(_044_),
    .Y(_046_)
  );
  NAND _101_ (
    .A(_037_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _102_ (
    .A(_045_),
    .B(_047_),
    .Y(_002_)
  );
  NAND _103_ (
    .A(data2send[7]),
    .B(_042_),
    .Y(_048_)
  );
  NOR _104_ (
    .A(_034_),
    .B(_035_),
    .Y(_049_)
  );
  NAND _105_ (
    .A(data2send[4]),
    .B(_049_),
    .Y(_050_)
  );
  NOR _106_ (
    .A(_034_),
    .B(selector[0]),
    .Y(_051_)
  );
  NAND _107_ (
    .A(selector[1]),
    .B(_035_),
    .Y(_052_)
  );
  NOR _108_ (
    .A(_041_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _109_ (
    .A(selector[1]),
    .B(_035_),
    .Y(_054_)
  );
  NAND _110_ (
    .A(data2send[6]),
    .B(_054_),
    .Y(_055_)
  );
  NAND _111_ (
    .A(_050_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _112_ (
    .A(selector[2]),
    .B(_053_),
    .Y(_057_)
  );
  NAND _113_ (
    .A(_048_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _114_ (
    .A(_056_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _115_ (
    .A(data2send[2]),
    .B(_054_),
    .Y(_060_)
  );
  NAND _116_ (
    .A(lastbit),
    .B(_049_),
    .Y(_061_)
  );
  NAND _117_ (
    .A(idontknow),
    .B(_051_),
    .Y(_062_)
  );
  NAND _118_ (
    .A(data2send[3]),
    .B(_042_),
    .Y(_063_)
  );
  NAND _119_ (
    .A(_060_),
    .B(_062_),
    .Y(_064_)
  );
  NAND _120_ (
    .A(_061_),
    .B(_063_),
    .Y(_065_)
  );
  NOR _121_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _122_ (
    .A(selector[2]),
    .B(_066_),
    .Y(_067_)
  );
  NAND _123_ (
    .A(_037_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _124_ (
    .A(_059_),
    .B(_068_),
    .Y(_001_)
  );
  NOR _125_ (
    .A(lastbit),
    .B(_044_),
    .Y(_069_)
  );
  NAND _126_ (
    .A(_038_),
    .B(_044_),
    .Y(_070_)
  );
  NAND _127_ (
    .A(_037_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _128_ (
    .A(_069_),
    .B(_071_),
    .Y(_003_)
  );
  NOR _129_ (
    .A(selector[0]),
    .B(reset),
    .Y(_004_[0])
  );
  NOR _130_ (
    .A(reset),
    .B(_054_),
    .Y(_072_)
  );
  NAND _131_ (
    .A(_052_),
    .B(_072_),
    .Y(_004_[1])
  );
  NAND _132_ (
    .A(selector[2]),
    .B(_049_),
    .Y(_073_)
  );
  NOR _133_ (
    .A(selector[2]),
    .B(_049_),
    .Y(_074_)
  );
  NOT _134_ (
    .A(_074_),
    .Y(_075_)
  );
  NAND _135_ (
    .A(_073_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _136_ (
    .A(reset),
    .B(_076_),
    .Y(_004_[2])
  );
  NAND _137_ (
    .A(selector[2]),
    .B(_051_),
    .Y(_077_)
  );
  NAND _138_ (
    .A(data_PSA_estruct[0]),
    .B(valid_PSA_estruct),
    .Y(_078_)
  );
  NOR _139_ (
    .A(_077_),
    .B(_078_),
    .Y(_079_)
  );
  NAND _140_ (
    .A(data2send[0]),
    .B(_077_),
    .Y(_080_)
  );
  NOT _141_ (
    .A(_080_),
    .Y(_081_)
  );
  NOR _142_ (
    .A(_079_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _143_ (
    .A(reset),
    .B(_082_),
    .Y(_000_[0])
  );
  NAND _144_ (
    .A(valid_PSA_estruct),
    .B(data_PSA_estruct[1]),
    .Y(_083_)
  );
  NOR _145_ (
    .A(_077_),
    .B(_083_),
    .Y(_084_)
  );
  NAND _146_ (
    .A(data2send[1]),
    .B(_077_),
    .Y(_085_)
  );
  NOT _147_ (
    .A(_085_),
    .Y(_086_)
  );
  NOR _148_ (
    .A(_084_),
    .B(_086_),
    .Y(_087_)
  );
  NOR _149_ (
    .A(reset),
    .B(_087_),
    .Y(_000_[1])
  );
  NOR _150_ (
    .A(_039_),
    .B(data_PSA_estruct[2]),
    .Y(_005_)
  );
  NOR _151_ (
    .A(_077_),
    .B(_005_),
    .Y(_006_)
  );
  NAND _152_ (
    .A(data2send[2]),
    .B(_077_),
    .Y(_007_)
  );
  NOT _153_ (
    .A(_007_),
    .Y(_008_)
  );
  NOR _154_ (
    .A(_006_),
    .B(_008_),
    .Y(_009_)
  );
  NOR _155_ (
    .A(reset),
    .B(_009_),
    .Y(_000_[2])
  );
  NOR _156_ (
    .A(_039_),
    .B(data_PSA_estruct[3]),
    .Y(_010_)
  );
  NOR _157_ (
    .A(_077_),
    .B(_010_),
    .Y(_011_)
  );
  NAND _158_ (
    .A(data2send[3]),
    .B(_077_),
    .Y(_012_)
  );
  NOT _159_ (
    .A(_012_),
    .Y(_013_)
  );
  NOR _160_ (
    .A(_011_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _161_ (
    .A(reset),
    .B(_014_),
    .Y(_000_[3])
  );
  NOR _162_ (
    .A(_039_),
    .B(data_PSA_estruct[4]),
    .Y(_015_)
  );
  NOR _163_ (
    .A(_077_),
    .B(_015_),
    .Y(_016_)
  );
  NAND _164_ (
    .A(data2send[4]),
    .B(_077_),
    .Y(_017_)
  );
  NOT _165_ (
    .A(_017_),
    .Y(_018_)
  );
  NOR _166_ (
    .A(_016_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _167_ (
    .A(reset),
    .B(_019_),
    .Y(_000_[4])
  );
  NAND _168_ (
    .A(valid_PSA_estruct),
    .B(_040_),
    .Y(_020_)
  );
  NOR _169_ (
    .A(_077_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _170_ (
    .A(_041_),
    .B(_077_),
    .Y(_022_)
  );
  NAND _171_ (
    .A(_037_),
    .B(_022_),
    .Y(_023_)
  );
  NOR _172_ (
    .A(_021_),
    .B(_023_),
    .Y(_000_[5])
  );
  NAND _173_ (
    .A(valid_PSA_estruct),
    .B(data_PSA_estruct[6]),
    .Y(_024_)
  );
  NOR _174_ (
    .A(_077_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _175_ (
    .A(data2send[6]),
    .B(_077_),
    .Y(_026_)
  );
  NOT _176_ (
    .A(_026_),
    .Y(_027_)
  );
  NOR _177_ (
    .A(_025_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _178_ (
    .A(reset),
    .B(_028_),
    .Y(_000_[6])
  );
  NOR _179_ (
    .A(_039_),
    .B(data_PSA_estruct[7]),
    .Y(_029_)
  );
  NOR _180_ (
    .A(_077_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _181_ (
    .A(data2send[7]),
    .B(_077_),
    .Y(_031_)
  );
  NOT _182_ (
    .A(_031_),
    .Y(_032_)
  );
  NOR _183_ (
    .A(_030_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _184_ (
    .A(reset),
    .B(_033_),
    .Y(_000_[7])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _185_ (
    .C(clk_32f),
    .D(_000_[0]),
    .Q(data2send[0])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _186_ (
    .C(clk_32f),
    .D(_000_[1]),
    .Q(data2send[1])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _187_ (
    .C(clk_32f),
    .D(_000_[2]),
    .Q(data2send[2])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _188_ (
    .C(clk_32f),
    .D(_000_[3]),
    .Q(data2send[3])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _189_ (
    .C(clk_32f),
    .D(_000_[4]),
    .Q(data2send[4])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _190_ (
    .C(clk_32f),
    .D(_000_[5]),
    .Q(data2send[5])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _191_ (
    .C(clk_32f),
    .D(_000_[6]),
    .Q(data2send[6])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _192_ (
    .C(clk_32f),
    .D(_000_[7]),
    .Q(data2send[7])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _193_ (
    .C(clk_32f),
    .D(_004_[0]),
    .Q(selector[0])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _194_ (
    .C(clk_32f),
    .D(_004_[1]),
    .Q(selector[1])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _195_ (
    .C(clk_32f),
    .D(_004_[2]),
    .Q(selector[2])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _196_ (
    .C(clk_32f),
    .D(_003_),
    .Q(lastbit)
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _197_ (
    .C(clk_32f),
    .D(_001_),
    .Q(data_out_estruct)
  );
  (* src = "ParaleloSerial_azul_estruct.v:12" *)
  DFF _198_ (
    .C(clk_32f),
    .D(_002_),
    .Q(idontknow)
  );
endmodule
