/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "ParaleloSerial_verde_estruct.v:1.1-115.10" *)
module ParaleloSerial_verde_estruct(clk_4f, clk_32f, active_to_PS, reset, data_out_estruct);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "ParaleloSerial_verde_estruct.v:2.28-2.40" *)
  input active_to_PS;
  (* src = "ParaleloSerial_verde_estruct.v:2.19-2.26" *)
  input clk_32f;
  (* src = "ParaleloSerial_verde_estruct.v:2.11-2.17" *)
  input clk_4f;
  (* src = "ParaleloSerial_verde_estruct.v:4.16-4.24" *)
  output data_out_estruct;
  (* src = "ParaleloSerial_verde_estruct.v:3.11-3.16" *)
  input reset;
  (* src = "ParaleloSerial_verde_estruct.v:7.15-7.23" *)
  wire [2:0] selector;
  NOT _20_ (
    .A(reset),
    .Y(_04_)
  );
  NOT _21_ (
    .A(selector[2]),
    .Y(_05_)
  );
  NOT _22_ (
    .A(selector[0]),
    .Y(_06_)
  );
  NOT _23_ (
    .A(selector[1]),
    .Y(_07_)
  );
  NAND _24_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_08_)
  );
  NAND _25_ (
    .A(_05_),
    .B(_08_),
    .Y(_09_)
  );
  NOR _26_ (
    .A(reset),
    .B(selector[0]),
    .Y(_00_)
  );
  NAND _27_ (
    .A(selector[2]),
    .B(selector[1]),
    .Y(_10_)
  );
  NAND _28_ (
    .A(_04_),
    .B(_10_),
    .Y(_11_)
  );
  NOR _29_ (
    .A(_06_),
    .B(_10_),
    .Y(_12_)
  );
  NAND _30_ (
    .A(_04_),
    .B(_09_),
    .Y(_13_)
  );
  NOR _31_ (
    .A(_12_),
    .B(_13_),
    .Y(_02_)
  );
  NAND _32_ (
    .A(selector[0]),
    .B(_07_),
    .Y(_14_)
  );
  NOR _33_ (
    .A(selector[0]),
    .B(_07_),
    .Y(_15_)
  );
  NOR _34_ (
    .A(reset),
    .B(_15_),
    .Y(_16_)
  );
  NAND _35_ (
    .A(_14_),
    .B(_16_),
    .Y(_01_)
  );
  NOR _36_ (
    .A(selector[2]),
    .B(active_to_PS),
    .Y(_17_)
  );
  NOT _37_ (
    .A(_17_),
    .Y(_18_)
  );
  NOR _38_ (
    .A(_14_),
    .B(_18_),
    .Y(_19_)
  );
  NOR _39_ (
    .A(_11_),
    .B(_19_),
    .Y(_03_)
  );
  (* src = "ParaleloSerial_verde_estruct.v:10.5-113.8" *)
  DFF _40_ (
    .C(clk_32f),
    .D(_00_),
    .Q(selector[0])
  );
  (* src = "ParaleloSerial_verde_estruct.v:10.5-113.8" *)
  DFF _41_ (
    .C(clk_32f),
    .D(_01_),
    .Q(selector[1])
  );
  (* src = "ParaleloSerial_verde_estruct.v:10.5-113.8" *)
  DFF _42_ (
    .C(clk_32f),
    .D(_02_),
    .Q(selector[2])
  );
  (* src = "ParaleloSerial_verde_estruct.v:10.5-113.8" *)
  DFF _43_ (
    .C(clk_32f),
    .D(_03_),
    .Q(data_out_estruct)
  );
endmodule
