/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "Recirculacion_estruct.v:1" *)
module Recirculacion_estruct(In0, In1, In2, In3, valid0, valid1, valid2, valid3, recirculacion_estruct, data_mux0, data_Probador0_estruct, data_mux1, data_Probador1_estruct, data_mux2, data_Probador2_estruct, data_mux3, data_Probador3_estruct, valid0_mux, valid1_mux, valid2_mux, valid3_mux, valid0_probador, valid1_probador, valid2_probador, valid3_probador);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  (* src = "Recirculacion_estruct.v:2" *)
  input [7:0] In0;
  (* src = "Recirculacion_estruct.v:2" *)
  input [7:0] In1;
  (* src = "Recirculacion_estruct.v:2" *)
  input [7:0] In2;
  (* src = "Recirculacion_estruct.v:2" *)
  input [7:0] In3;
  (* src = "Recirculacion_estruct.v:6" *)
  output [7:0] data_Probador0_estruct;
  (* src = "Recirculacion_estruct.v:8" *)
  output [7:0] data_Probador1_estruct;
  (* src = "Recirculacion_estruct.v:10" *)
  output [7:0] data_Probador2_estruct;
  (* src = "Recirculacion_estruct.v:12" *)
  output [7:0] data_Probador3_estruct;
  (* src = "Recirculacion_estruct.v:5" *)
  output [7:0] data_mux0;
  (* src = "Recirculacion_estruct.v:7" *)
  output [7:0] data_mux1;
  (* src = "Recirculacion_estruct.v:9" *)
  output [7:0] data_mux2;
  (* src = "Recirculacion_estruct.v:11" *)
  output [7:0] data_mux3;
  (* src = "Recirculacion_estruct.v:4" *)
  input recirculacion_estruct;
  (* src = "Recirculacion_estruct.v:3" *)
  input valid0;
  (* src = "Recirculacion_estruct.v:13" *)
  output valid0_mux;
  (* src = "Recirculacion_estruct.v:14" *)
  output valid0_probador;
  (* src = "Recirculacion_estruct.v:3" *)
  input valid1;
  (* src = "Recirculacion_estruct.v:13" *)
  output valid1_mux;
  (* src = "Recirculacion_estruct.v:14" *)
  output valid1_probador;
  (* src = "Recirculacion_estruct.v:3" *)
  input valid2;
  (* src = "Recirculacion_estruct.v:13" *)
  output valid2_mux;
  (* src = "Recirculacion_estruct.v:14" *)
  output valid2_probador;
  (* src = "Recirculacion_estruct.v:3" *)
  input valid3;
  (* src = "Recirculacion_estruct.v:13" *)
  output valid3_mux;
  (* src = "Recirculacion_estruct.v:14" *)
  output valid3_probador;
  NOT _072_ (
    .A(In3[0]),
    .Y(_000_)
  );
  NOT _073_ (
    .A(In3[1]),
    .Y(_001_)
  );
  NOT _074_ (
    .A(In3[2]),
    .Y(_002_)
  );
  NOT _075_ (
    .A(In3[3]),
    .Y(_003_)
  );
  NOT _076_ (
    .A(In3[4]),
    .Y(_004_)
  );
  NOT _077_ (
    .A(In3[5]),
    .Y(_005_)
  );
  NOT _078_ (
    .A(In3[6]),
    .Y(_006_)
  );
  NOT _079_ (
    .A(In3[7]),
    .Y(_007_)
  );
  NOT _080_ (
    .A(valid3),
    .Y(_008_)
  );
  NOT _081_ (
    .A(valid2),
    .Y(_009_)
  );
  NOT _082_ (
    .A(In2[0]),
    .Y(_010_)
  );
  NOT _083_ (
    .A(In2[1]),
    .Y(_011_)
  );
  NOT _084_ (
    .A(In2[2]),
    .Y(_012_)
  );
  NOT _085_ (
    .A(In2[3]),
    .Y(_013_)
  );
  NOT _086_ (
    .A(In2[4]),
    .Y(_014_)
  );
  NOT _087_ (
    .A(In2[5]),
    .Y(_015_)
  );
  NOT _088_ (
    .A(In2[6]),
    .Y(_016_)
  );
  NOT _089_ (
    .A(In2[7]),
    .Y(_017_)
  );
  NOT _090_ (
    .A(In1[0]),
    .Y(_018_)
  );
  NOT _091_ (
    .A(In1[1]),
    .Y(_019_)
  );
  NOT _092_ (
    .A(In1[2]),
    .Y(_020_)
  );
  NOT _093_ (
    .A(In1[3]),
    .Y(_021_)
  );
  NOT _094_ (
    .A(In1[4]),
    .Y(_022_)
  );
  NOT _095_ (
    .A(In1[5]),
    .Y(_023_)
  );
  NOT _096_ (
    .A(In1[6]),
    .Y(_024_)
  );
  NOT _097_ (
    .A(In1[7]),
    .Y(_025_)
  );
  NOT _098_ (
    .A(valid1),
    .Y(_026_)
  );
  NOT _099_ (
    .A(In0[0]),
    .Y(_027_)
  );
  NOT _100_ (
    .A(In0[1]),
    .Y(_028_)
  );
  NOT _101_ (
    .A(In0[2]),
    .Y(_029_)
  );
  NOT _102_ (
    .A(In0[3]),
    .Y(_030_)
  );
  NOT _103_ (
    .A(In0[4]),
    .Y(_031_)
  );
  NOT _104_ (
    .A(In0[5]),
    .Y(_032_)
  );
  NOT _105_ (
    .A(In0[6]),
    .Y(_033_)
  );
  NOT _106_ (
    .A(In0[7]),
    .Y(_034_)
  );
  NOT _107_ (
    .A(valid0),
    .Y(_035_)
  );
  NAND _108_ (
    .A(In3[0]),
    .B(recirculacion_estruct),
    .Y(_036_)
  );
  NOT _109_ (
    .A(_036_),
    .Y(data_mux3[0])
  );
  NAND _110_ (
    .A(recirculacion_estruct),
    .B(In3[1]),
    .Y(_037_)
  );
  NOT _111_ (
    .A(_037_),
    .Y(data_mux3[1])
  );
  NAND _112_ (
    .A(recirculacion_estruct),
    .B(In3[2]),
    .Y(_038_)
  );
  NOT _113_ (
    .A(_038_),
    .Y(data_mux3[2])
  );
  NAND _114_ (
    .A(recirculacion_estruct),
    .B(In3[3]),
    .Y(_039_)
  );
  NOT _115_ (
    .A(_039_),
    .Y(data_mux3[3])
  );
  NAND _116_ (
    .A(recirculacion_estruct),
    .B(In3[4]),
    .Y(_040_)
  );
  NOT _117_ (
    .A(_040_),
    .Y(data_mux3[4])
  );
  NAND _118_ (
    .A(recirculacion_estruct),
    .B(In3[5]),
    .Y(_041_)
  );
  NOT _119_ (
    .A(_041_),
    .Y(data_mux3[5])
  );
  NAND _120_ (
    .A(recirculacion_estruct),
    .B(In3[6]),
    .Y(_042_)
  );
  NOT _121_ (
    .A(_042_),
    .Y(data_mux3[6])
  );
  NAND _122_ (
    .A(recirculacion_estruct),
    .B(In3[7]),
    .Y(_043_)
  );
  NOT _123_ (
    .A(_043_),
    .Y(data_mux3[7])
  );
  NOR _124_ (
    .A(recirculacion_estruct),
    .B(_008_),
    .Y(valid3_probador)
  );
  NAND _125_ (
    .A(recirculacion_estruct),
    .B(valid3),
    .Y(_044_)
  );
  NOT _126_ (
    .A(_044_),
    .Y(valid3_mux)
  );
  NOR _127_ (
    .A(_000_),
    .B(recirculacion_estruct),
    .Y(data_Probador3_estruct[0])
  );
  NOR _128_ (
    .A(recirculacion_estruct),
    .B(_001_),
    .Y(data_Probador3_estruct[1])
  );
  NOR _129_ (
    .A(recirculacion_estruct),
    .B(_002_),
    .Y(data_Probador3_estruct[2])
  );
  NOR _130_ (
    .A(recirculacion_estruct),
    .B(_003_),
    .Y(data_Probador3_estruct[3])
  );
  NOR _131_ (
    .A(recirculacion_estruct),
    .B(_004_),
    .Y(data_Probador3_estruct[4])
  );
  NOR _132_ (
    .A(recirculacion_estruct),
    .B(_005_),
    .Y(data_Probador3_estruct[5])
  );
  NOR _133_ (
    .A(recirculacion_estruct),
    .B(_006_),
    .Y(data_Probador3_estruct[6])
  );
  NOR _134_ (
    .A(recirculacion_estruct),
    .B(_007_),
    .Y(data_Probador3_estruct[7])
  );
  NOR _135_ (
    .A(recirculacion_estruct),
    .B(_009_),
    .Y(valid2_probador)
  );
  NOR _136_ (
    .A(recirculacion_estruct),
    .B(_010_),
    .Y(data_Probador2_estruct[0])
  );
  NOR _137_ (
    .A(recirculacion_estruct),
    .B(_011_),
    .Y(data_Probador2_estruct[1])
  );
  NOR _138_ (
    .A(recirculacion_estruct),
    .B(_012_),
    .Y(data_Probador2_estruct[2])
  );
  NOR _139_ (
    .A(recirculacion_estruct),
    .B(_013_),
    .Y(data_Probador2_estruct[3])
  );
  NOR _140_ (
    .A(recirculacion_estruct),
    .B(_014_),
    .Y(data_Probador2_estruct[4])
  );
  NOR _141_ (
    .A(recirculacion_estruct),
    .B(_015_),
    .Y(data_Probador2_estruct[5])
  );
  NOR _142_ (
    .A(recirculacion_estruct),
    .B(_016_),
    .Y(data_Probador2_estruct[6])
  );
  NOR _143_ (
    .A(recirculacion_estruct),
    .B(_017_),
    .Y(data_Probador2_estruct[7])
  );
  NAND _144_ (
    .A(recirculacion_estruct),
    .B(valid2),
    .Y(_045_)
  );
  NOT _145_ (
    .A(_045_),
    .Y(valid2_mux)
  );
  NAND _146_ (
    .A(recirculacion_estruct),
    .B(In2[0]),
    .Y(_046_)
  );
  NOT _147_ (
    .A(_046_),
    .Y(data_mux2[0])
  );
  NAND _148_ (
    .A(recirculacion_estruct),
    .B(In2[1]),
    .Y(_047_)
  );
  NOT _149_ (
    .A(_047_),
    .Y(data_mux2[1])
  );
  NAND _150_ (
    .A(recirculacion_estruct),
    .B(In2[2]),
    .Y(_048_)
  );
  NOT _151_ (
    .A(_048_),
    .Y(data_mux2[2])
  );
  NAND _152_ (
    .A(recirculacion_estruct),
    .B(In2[3]),
    .Y(_049_)
  );
  NOT _153_ (
    .A(_049_),
    .Y(data_mux2[3])
  );
  NAND _154_ (
    .A(recirculacion_estruct),
    .B(In2[4]),
    .Y(_050_)
  );
  NOT _155_ (
    .A(_050_),
    .Y(data_mux2[4])
  );
  NAND _156_ (
    .A(recirculacion_estruct),
    .B(In2[5]),
    .Y(_051_)
  );
  NOT _157_ (
    .A(_051_),
    .Y(data_mux2[5])
  );
  NAND _158_ (
    .A(recirculacion_estruct),
    .B(In2[6]),
    .Y(_052_)
  );
  NOT _159_ (
    .A(_052_),
    .Y(data_mux2[6])
  );
  NAND _160_ (
    .A(recirculacion_estruct),
    .B(In2[7]),
    .Y(_053_)
  );
  NOT _161_ (
    .A(_053_),
    .Y(data_mux2[7])
  );
  NAND _162_ (
    .A(recirculacion_estruct),
    .B(In1[0]),
    .Y(_054_)
  );
  NOT _163_ (
    .A(_054_),
    .Y(data_mux1[0])
  );
  NAND _164_ (
    .A(recirculacion_estruct),
    .B(In1[1]),
    .Y(_055_)
  );
  NOT _165_ (
    .A(_055_),
    .Y(data_mux1[1])
  );
  NAND _166_ (
    .A(recirculacion_estruct),
    .B(In1[2]),
    .Y(_056_)
  );
  NOT _167_ (
    .A(_056_),
    .Y(data_mux1[2])
  );
  NAND _168_ (
    .A(recirculacion_estruct),
    .B(In1[3]),
    .Y(_057_)
  );
  NOT _169_ (
    .A(_057_),
    .Y(data_mux1[3])
  );
  NAND _170_ (
    .A(recirculacion_estruct),
    .B(In1[4]),
    .Y(_058_)
  );
  NOT _171_ (
    .A(_058_),
    .Y(data_mux1[4])
  );
  NAND _172_ (
    .A(recirculacion_estruct),
    .B(In1[5]),
    .Y(_059_)
  );
  NOT _173_ (
    .A(_059_),
    .Y(data_mux1[5])
  );
  NAND _174_ (
    .A(recirculacion_estruct),
    .B(In1[6]),
    .Y(_060_)
  );
  NOT _175_ (
    .A(_060_),
    .Y(data_mux1[6])
  );
  NAND _176_ (
    .A(recirculacion_estruct),
    .B(In1[7]),
    .Y(_061_)
  );
  NOT _177_ (
    .A(_061_),
    .Y(data_mux1[7])
  );
  NOR _178_ (
    .A(recirculacion_estruct),
    .B(_026_),
    .Y(valid1_probador)
  );
  NAND _179_ (
    .A(recirculacion_estruct),
    .B(valid1),
    .Y(_062_)
  );
  NOT _180_ (
    .A(_062_),
    .Y(valid1_mux)
  );
  NOR _181_ (
    .A(recirculacion_estruct),
    .B(_018_),
    .Y(data_Probador1_estruct[0])
  );
  NOR _182_ (
    .A(recirculacion_estruct),
    .B(_019_),
    .Y(data_Probador1_estruct[1])
  );
  NOR _183_ (
    .A(recirculacion_estruct),
    .B(_020_),
    .Y(data_Probador1_estruct[2])
  );
  NOR _184_ (
    .A(recirculacion_estruct),
    .B(_021_),
    .Y(data_Probador1_estruct[3])
  );
  NOR _185_ (
    .A(recirculacion_estruct),
    .B(_022_),
    .Y(data_Probador1_estruct[4])
  );
  NOR _186_ (
    .A(recirculacion_estruct),
    .B(_023_),
    .Y(data_Probador1_estruct[5])
  );
  NOR _187_ (
    .A(recirculacion_estruct),
    .B(_024_),
    .Y(data_Probador1_estruct[6])
  );
  NOR _188_ (
    .A(recirculacion_estruct),
    .B(_025_),
    .Y(data_Probador1_estruct[7])
  );
  NAND _189_ (
    .A(recirculacion_estruct),
    .B(In0[0]),
    .Y(_063_)
  );
  NOT _190_ (
    .A(_063_),
    .Y(data_mux0[0])
  );
  NAND _191_ (
    .A(recirculacion_estruct),
    .B(In0[1]),
    .Y(_064_)
  );
  NOT _192_ (
    .A(_064_),
    .Y(data_mux0[1])
  );
  NAND _193_ (
    .A(recirculacion_estruct),
    .B(In0[2]),
    .Y(_065_)
  );
  NOT _194_ (
    .A(_065_),
    .Y(data_mux0[2])
  );
  NAND _195_ (
    .A(recirculacion_estruct),
    .B(In0[3]),
    .Y(_066_)
  );
  NOT _196_ (
    .A(_066_),
    .Y(data_mux0[3])
  );
  NAND _197_ (
    .A(recirculacion_estruct),
    .B(In0[4]),
    .Y(_067_)
  );
  NOT _198_ (
    .A(_067_),
    .Y(data_mux0[4])
  );
  NAND _199_ (
    .A(recirculacion_estruct),
    .B(In0[5]),
    .Y(_068_)
  );
  NOT _200_ (
    .A(_068_),
    .Y(data_mux0[5])
  );
  NAND _201_ (
    .A(recirculacion_estruct),
    .B(In0[6]),
    .Y(_069_)
  );
  NOT _202_ (
    .A(_069_),
    .Y(data_mux0[6])
  );
  NAND _203_ (
    .A(recirculacion_estruct),
    .B(In0[7]),
    .Y(_070_)
  );
  NOT _204_ (
    .A(_070_),
    .Y(data_mux0[7])
  );
  NOR _205_ (
    .A(recirculacion_estruct),
    .B(_035_),
    .Y(valid0_probador)
  );
  NAND _206_ (
    .A(recirculacion_estruct),
    .B(valid0),
    .Y(_071_)
  );
  NOT _207_ (
    .A(_071_),
    .Y(valid0_mux)
  );
  NOR _208_ (
    .A(recirculacion_estruct),
    .B(_027_),
    .Y(data_Probador0_estruct[0])
  );
  NOR _209_ (
    .A(recirculacion_estruct),
    .B(_028_),
    .Y(data_Probador0_estruct[1])
  );
  NOR _210_ (
    .A(recirculacion_estruct),
    .B(_029_),
    .Y(data_Probador0_estruct[2])
  );
  NOR _211_ (
    .A(recirculacion_estruct),
    .B(_030_),
    .Y(data_Probador0_estruct[3])
  );
  NOR _212_ (
    .A(recirculacion_estruct),
    .B(_031_),
    .Y(data_Probador0_estruct[4])
  );
  NOR _213_ (
    .A(recirculacion_estruct),
    .B(_032_),
    .Y(data_Probador0_estruct[5])
  );
  NOR _214_ (
    .A(recirculacion_estruct),
    .B(_033_),
    .Y(data_Probador0_estruct[6])
  );
  NOR _215_ (
    .A(recirculacion_estruct),
    .B(_034_),
    .Y(data_Probador0_estruct[7])
  );
endmodule
