/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "SerialParalelo_azul_estruct.v:1" *)
module SerialParalelo_azul_estruct(clk_4f, clk_32f, data_in, reset, recirculacion_estruct);
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  wire [2:0] _000_;
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  wire [7:0] _001_;
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  wire _002_;
  (* src = "SerialParalelo_azul_estruct.v:65" *)
  wire [2:0] _003_;
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  wire _004_;
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  wire _005_;
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  wire _006_;
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  wire _007_;
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  wire _008_;
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  wire _009_;
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  wire _010_;
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  (* src = "SerialParalelo_azul_estruct.v:8" *)
  wire [2:0] BC_counter;
  (* src = "SerialParalelo_azul_estruct.v:2" *)
  input clk_32f;
  (* src = "SerialParalelo_azul_estruct.v:2" *)
  input clk_4f;
  (* src = "SerialParalelo_azul_estruct.v:10" *)
  wire [7:0] data2send;
  (* src = "SerialParalelo_azul_estruct.v:2" *)
  input data_in;
  (* src = "SerialParalelo_azul_estruct.v:3" *)
  output recirculacion_estruct;
  (* src = "SerialParalelo_azul_estruct.v:2" *)
  input reset;
  (* src = "SerialParalelo_azul_estruct.v:7" *)
  wire [2:0] selector;
  (* src = "SerialParalelo_azul_estruct.v:6" *)
  wire temp0;
  (* src = "SerialParalelo_azul_estruct.v:6" *)
  wire temp1;
  (* src = "SerialParalelo_azul_estruct.v:6" *)
  wire temp2;
  (* src = "SerialParalelo_azul_estruct.v:6" *)
  wire temp3;
  (* src = "SerialParalelo_azul_estruct.v:6" *)
  wire temp4;
  (* src = "SerialParalelo_azul_estruct.v:6" *)
  wire temp5;
  (* src = "SerialParalelo_azul_estruct.v:6" *)
  wire temp6;
  (* src = "SerialParalelo_azul_estruct.v:6" *)
  wire temp7;
  NOT _109_ (
    .A(clk_32f),
    .Y(_019_)
  );
  NOT _110_ (
    .A(BC_counter[2]),
    .Y(_076_)
  );
  NOT _111_ (
    .A(data2send[6]),
    .Y(_077_)
  );
  NOT _112_ (
    .A(selector[1]),
    .Y(_078_)
  );
  NOT _113_ (
    .A(selector[2]),
    .Y(_079_)
  );
  NOT _114_ (
    .A(selector[0]),
    .Y(_080_)
  );
  NOT _115_ (
    .A(temp0),
    .Y(_081_)
  );
  NOT _116_ (
    .A(reset),
    .Y(_082_)
  );
  NOT _117_ (
    .A(temp1),
    .Y(_083_)
  );
  NOT _118_ (
    .A(temp2),
    .Y(_084_)
  );
  NOT _119_ (
    .A(temp5),
    .Y(_085_)
  );
  NOT _120_ (
    .A(temp3),
    .Y(_086_)
  );
  NOT _121_ (
    .A(temp4),
    .Y(_087_)
  );
  NOT _122_ (
    .A(BC_counter[0]),
    .Y(_088_)
  );
  NOT _123_ (
    .A(BC_counter[1]),
    .Y(_089_)
  );
  NOT _124_ (
    .A(temp6),
    .Y(_090_)
  );
  NOT _125_ (
    .A(temp7),
    .Y(_091_)
  );
  NOT _126_ (
    .A(data_in),
    .Y(_092_)
  );
  NOT _127_ (
    .A(data2send[2]),
    .Y(_093_)
  );
  NOT _128_ (
    .A(data2send[3]),
    .Y(_094_)
  );
  NOT _129_ (
    .A(data2send[4]),
    .Y(_095_)
  );
  NOT _130_ (
    .A(data2send[5]),
    .Y(_096_)
  );
  NOT _131_ (
    .A(data2send[7]),
    .Y(_097_)
  );
  NOR _132_ (
    .A(_081_),
    .B(reset),
    .Y(_001_[7])
  );
  NOR _133_ (
    .A(reset),
    .B(_083_),
    .Y(_001_[6])
  );
  NOR _134_ (
    .A(reset),
    .B(_084_),
    .Y(_001_[5])
  );
  NOR _135_ (
    .A(reset),
    .B(_085_),
    .Y(_001_[2])
  );
  NOR _136_ (
    .A(reset),
    .B(_086_),
    .Y(_001_[4])
  );
  NOR _137_ (
    .A(reset),
    .B(_087_),
    .Y(_001_[3])
  );
  NOR _138_ (
    .A(reset),
    .B(_090_),
    .Y(_001_[1])
  );
  NOR _139_ (
    .A(reset),
    .B(_091_),
    .Y(_001_[0])
  );
  NOR _140_ (
    .A(_094_),
    .B(_095_),
    .Y(_098_)
  );
  NAND _141_ (
    .A(data2send[3]),
    .B(data2send[4]),
    .Y(_099_)
  );
  NOR _142_ (
    .A(_096_),
    .B(_097_),
    .Y(_100_)
  );
  NAND _143_ (
    .A(data2send[5]),
    .B(data2send[7]),
    .Y(_101_)
  );
  NOR _144_ (
    .A(_099_),
    .B(_101_),
    .Y(_102_)
  );
  NAND _145_ (
    .A(_098_),
    .B(_100_),
    .Y(_103_)
  );
  NOR _146_ (
    .A(data2send[0]),
    .B(data2send[1]),
    .Y(_104_)
  );
  NOT _147_ (
    .A(_104_),
    .Y(_105_)
  );
  NOR _148_ (
    .A(data2send[6]),
    .B(_093_),
    .Y(_106_)
  );
  NAND _149_ (
    .A(_077_),
    .B(data2send[2]),
    .Y(_107_)
  );
  NOR _150_ (
    .A(_105_),
    .B(_107_),
    .Y(_108_)
  );
  NAND _151_ (
    .A(_104_),
    .B(_106_),
    .Y(_020_)
  );
  NOR _152_ (
    .A(_103_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _153_ (
    .A(_102_),
    .B(_108_),
    .Y(_022_)
  );
  NAND _154_ (
    .A(_088_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _155_ (
    .A(_082_),
    .B(_023_),
    .Y(_024_)
  );
  NOR _156_ (
    .A(_088_),
    .B(_022_),
    .Y(_025_)
  );
  NAND _157_ (
    .A(BC_counter[0]),
    .B(_021_),
    .Y(_026_)
  );
  NOR _158_ (
    .A(_024_),
    .B(_025_),
    .Y(_000_[0])
  );
  NOR _159_ (
    .A(BC_counter[1]),
    .B(_025_),
    .Y(_027_)
  );
  NOR _160_ (
    .A(reset),
    .B(_027_),
    .Y(_028_)
  );
  NOR _161_ (
    .A(_089_),
    .B(_026_),
    .Y(_029_)
  );
  NAND _162_ (
    .A(BC_counter[1]),
    .B(_025_),
    .Y(_030_)
  );
  NAND _163_ (
    .A(_028_),
    .B(_030_),
    .Y(_031_)
  );
  NOT _164_ (
    .A(_031_),
    .Y(_000_[1])
  );
  NOR _165_ (
    .A(_076_),
    .B(_029_),
    .Y(_032_)
  );
  NOR _166_ (
    .A(BC_counter[2]),
    .B(_030_),
    .Y(_033_)
  );
  NOR _167_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _168_ (
    .A(reset),
    .B(_034_),
    .Y(_000_[2])
  );
  NAND _169_ (
    .A(selector[0]),
    .B(_082_),
    .Y(_003_[0])
  );
  NAND _170_ (
    .A(selector[1]),
    .B(selector[0]),
    .Y(_035_)
  );
  NOR _171_ (
    .A(selector[1]),
    .B(selector[0]),
    .Y(_036_)
  );
  NOR _172_ (
    .A(reset),
    .B(_036_),
    .Y(_037_)
  );
  NAND _173_ (
    .A(_035_),
    .B(_037_),
    .Y(_038_)
  );
  NOT _174_ (
    .A(_038_),
    .Y(_003_[1])
  );
  NOR _175_ (
    .A(_079_),
    .B(_035_),
    .Y(_039_)
  );
  NAND _176_ (
    .A(_079_),
    .B(_035_),
    .Y(_040_)
  );
  NAND _177_ (
    .A(_082_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _178_ (
    .A(_039_),
    .B(_041_),
    .Y(_003_[2])
  );
  NOR _179_ (
    .A(recirculacion_estruct),
    .B(_033_),
    .Y(_042_)
  );
  NOR _180_ (
    .A(reset),
    .B(_042_),
    .Y(_002_)
  );
  NAND _181_ (
    .A(_092_),
    .B(_039_),
    .Y(_043_)
  );
  NAND _182_ (
    .A(_082_),
    .B(_043_),
    .Y(_044_)
  );
  NOR _183_ (
    .A(temp7),
    .B(_039_),
    .Y(_045_)
  );
  NOR _184_ (
    .A(_044_),
    .B(_045_),
    .Y(_011_)
  );
  NOR _185_ (
    .A(_078_),
    .B(selector[0]),
    .Y(_046_)
  );
  NAND _186_ (
    .A(selector[2]),
    .B(_046_),
    .Y(_047_)
  );
  NAND _187_ (
    .A(_090_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _188_ (
    .A(data_in),
    .B(_047_),
    .Y(_049_)
  );
  NAND _189_ (
    .A(_082_),
    .B(_048_),
    .Y(_050_)
  );
  NOR _190_ (
    .A(_049_),
    .B(_050_),
    .Y(_010_)
  );
  NOR _191_ (
    .A(selector[1]),
    .B(_080_),
    .Y(_051_)
  );
  NAND _192_ (
    .A(selector[2]),
    .B(_051_),
    .Y(_052_)
  );
  NAND _193_ (
    .A(_085_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _194_ (
    .A(data_in),
    .B(_052_),
    .Y(_054_)
  );
  NAND _195_ (
    .A(_082_),
    .B(_053_),
    .Y(_055_)
  );
  NOR _196_ (
    .A(_054_),
    .B(_055_),
    .Y(_009_)
  );
  NAND _197_ (
    .A(selector[2]),
    .B(_036_),
    .Y(_056_)
  );
  NAND _198_ (
    .A(_087_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _199_ (
    .A(data_in),
    .B(_056_),
    .Y(_058_)
  );
  NAND _200_ (
    .A(_082_),
    .B(_057_),
    .Y(_059_)
  );
  NOR _201_ (
    .A(_058_),
    .B(_059_),
    .Y(_008_)
  );
  NAND _202_ (
    .A(_079_),
    .B(_036_),
    .Y(_060_)
  );
  NAND _203_ (
    .A(_081_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _204_ (
    .A(data_in),
    .B(_060_),
    .Y(_062_)
  );
  NAND _205_ (
    .A(_082_),
    .B(_061_),
    .Y(_063_)
  );
  NOR _206_ (
    .A(_062_),
    .B(_063_),
    .Y(_004_)
  );
  NOR _207_ (
    .A(selector[2]),
    .B(_035_),
    .Y(_064_)
  );
  NOR _208_ (
    .A(temp3),
    .B(_064_),
    .Y(_065_)
  );
  NAND _209_ (
    .A(_092_),
    .B(_064_),
    .Y(_066_)
  );
  NAND _210_ (
    .A(_082_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _211_ (
    .A(_065_),
    .B(_067_),
    .Y(_007_)
  );
  NAND _212_ (
    .A(_079_),
    .B(_046_),
    .Y(_068_)
  );
  NAND _213_ (
    .A(_084_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _214_ (
    .A(data_in),
    .B(_068_),
    .Y(_070_)
  );
  NAND _215_ (
    .A(_082_),
    .B(_069_),
    .Y(_071_)
  );
  NOR _216_ (
    .A(_070_),
    .B(_071_),
    .Y(_006_)
  );
  NAND _217_ (
    .A(_079_),
    .B(_051_),
    .Y(_072_)
  );
  NAND _218_ (
    .A(_083_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _219_ (
    .A(data_in),
    .B(_072_),
    .Y(_074_)
  );
  NAND _220_ (
    .A(_082_),
    .B(_073_),
    .Y(_075_)
  );
  NOR _221_ (
    .A(_074_),
    .B(_075_),
    .Y(_005_)
  );
  NOT _222_ (
    .A(clk_32f),
    .Y(_012_)
  );
  NOT _223_ (
    .A(clk_32f),
    .Y(_013_)
  );
  NOT _224_ (
    .A(clk_32f),
    .Y(_014_)
  );
  NOT _225_ (
    .A(clk_32f),
    .Y(_015_)
  );
  NOT _226_ (
    .A(clk_32f),
    .Y(_016_)
  );
  NOT _227_ (
    .A(clk_32f),
    .Y(_017_)
  );
  NOT _228_ (
    .A(clk_32f),
    .Y(_018_)
  );
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  DFF _229_ (
    .C(clk_4f),
    .D(_002_),
    .Q(recirculacion_estruct)
  );
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  DFF _230_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(BC_counter[0])
  );
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  DFF _231_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(BC_counter[1])
  );
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  DFF _232_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(BC_counter[2])
  );
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  DFF _233_ (
    .C(clk_4f),
    .D(_001_[0]),
    .Q(data2send[0])
  );
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  DFF _234_ (
    .C(clk_4f),
    .D(_001_[1]),
    .Q(data2send[1])
  );
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  DFF _235_ (
    .C(clk_4f),
    .D(_001_[2]),
    .Q(data2send[2])
  );
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  DFF _236_ (
    .C(clk_4f),
    .D(_001_[3]),
    .Q(data2send[3])
  );
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  DFF _237_ (
    .C(clk_4f),
    .D(_001_[4]),
    .Q(data2send[4])
  );
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  DFF _238_ (
    .C(clk_4f),
    .D(_001_[5]),
    .Q(data2send[5])
  );
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  DFF _239_ (
    .C(clk_4f),
    .D(_001_[6]),
    .Q(data2send[6])
  );
  (* src = "SerialParalelo_azul_estruct.v:77" *)
  DFF _240_ (
    .C(clk_4f),
    .D(_001_[7]),
    .Q(data2send[7])
  );
  (* src = "SerialParalelo_azul_estruct.v:65" *)
  DFF _241_ (
    .C(clk_32f),
    .D(_003_[0]),
    .Q(selector[0])
  );
  (* src = "SerialParalelo_azul_estruct.v:65" *)
  DFF _242_ (
    .C(clk_32f),
    .D(_003_[1]),
    .Q(selector[1])
  );
  (* src = "SerialParalelo_azul_estruct.v:65" *)
  DFF _243_ (
    .C(clk_32f),
    .D(_003_[2]),
    .Q(selector[2])
  );
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  DFF _244_ (
    .C(_012_),
    .D(_005_),
    .Q(temp1)
  );
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  DFF _245_ (
    .C(_013_),
    .D(_006_),
    .Q(temp2)
  );
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  DFF _246_ (
    .C(_014_),
    .D(_007_),
    .Q(temp3)
  );
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  DFF _247_ (
    .C(_015_),
    .D(_004_),
    .Q(temp0)
  );
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  DFF _248_ (
    .C(_016_),
    .D(_008_),
    .Q(temp4)
  );
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  DFF _249_ (
    .C(_017_),
    .D(_009_),
    .Q(temp5)
  );
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  DFF _250_ (
    .C(_018_),
    .D(_010_),
    .Q(temp6)
  );
  (* src = "SerialParalelo_azul_estruct.v:13" *)
  DFF _251_ (
    .C(_019_),
    .D(_011_),
    .Q(temp7)
  );
endmodule
