/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "SerialParalelo_verde_estruct.v:1" *)
module SerialParalelo_verde_estruct(clk_4f, clk_32f, data_in, reset, data2send_to_LDMX_estruct, active_estruct_to_PS, valid_out_to_LDMX_estruct);
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  wire [2:0] _000_;
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  wire _001_;
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  wire [7:0] _002_;
  (* src = "SerialParalelo_verde_estruct.v:64" *)
  wire [2:0] _003_;
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  wire _004_;
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  wire _005_;
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  wire _006_;
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  wire _007_;
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  wire _008_;
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  wire _009_;
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  wire _010_;
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  wire _011_;
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  (* src = "SerialParalelo_verde_estruct.v:9" *)
  wire [2:0] BC_counter;
  (* src = "SerialParalelo_verde_estruct.v:4" *)
  output active_estruct_to_PS;
  (* src = "SerialParalelo_verde_estruct.v:2" *)
  input clk_32f;
  (* src = "SerialParalelo_verde_estruct.v:2" *)
  input clk_4f;
  (* src = "SerialParalelo_verde_estruct.v:3" *)
  output [7:0] data2send_to_LDMX_estruct;
  (* src = "SerialParalelo_verde_estruct.v:2" *)
  input data_in;
  (* src = "SerialParalelo_verde_estruct.v:2" *)
  input reset;
  (* src = "SerialParalelo_verde_estruct.v:8" *)
  wire [2:0] selector;
  (* src = "SerialParalelo_verde_estruct.v:7" *)
  wire temp0;
  (* src = "SerialParalelo_verde_estruct.v:7" *)
  wire temp1;
  (* src = "SerialParalelo_verde_estruct.v:7" *)
  wire temp2;
  (* src = "SerialParalelo_verde_estruct.v:7" *)
  wire temp3;
  (* src = "SerialParalelo_verde_estruct.v:7" *)
  wire temp4;
  (* src = "SerialParalelo_verde_estruct.v:7" *)
  wire temp5;
  (* src = "SerialParalelo_verde_estruct.v:7" *)
  wire temp6;
  (* src = "SerialParalelo_verde_estruct.v:7" *)
  wire temp7;
  (* src = "SerialParalelo_verde_estruct.v:4" *)
  output valid_out_to_LDMX_estruct;
  NOT _116_ (
    .A(clk_32f),
    .Y(_020_)
  );
  NOT _117_ (
    .A(BC_counter[2]),
    .Y(_084_)
  );
  NOT _118_ (
    .A(data2send_to_LDMX_estruct[0]),
    .Y(_085_)
  );
  NOT _119_ (
    .A(data2send_to_LDMX_estruct[1]),
    .Y(_086_)
  );
  NOT _120_ (
    .A(data2send_to_LDMX_estruct[6]),
    .Y(_087_)
  );
  NOT _121_ (
    .A(selector[1]),
    .Y(_088_)
  );
  NOT _122_ (
    .A(selector[0]),
    .Y(_089_)
  );
  NOT _123_ (
    .A(selector[2]),
    .Y(_090_)
  );
  NOT _124_ (
    .A(temp0),
    .Y(_091_)
  );
  NOT _125_ (
    .A(reset),
    .Y(_092_)
  );
  NOT _126_ (
    .A(temp1),
    .Y(_093_)
  );
  NOT _127_ (
    .A(temp2),
    .Y(_094_)
  );
  NOT _128_ (
    .A(temp5),
    .Y(_095_)
  );
  NOT _129_ (
    .A(temp3),
    .Y(_096_)
  );
  NOT _130_ (
    .A(temp4),
    .Y(_097_)
  );
  NOT _131_ (
    .A(temp6),
    .Y(_098_)
  );
  NOT _132_ (
    .A(temp7),
    .Y(_099_)
  );
  NOT _133_ (
    .A(BC_counter[0]),
    .Y(_100_)
  );
  NOT _134_ (
    .A(BC_counter[1]),
    .Y(_101_)
  );
  NOT _135_ (
    .A(data_in),
    .Y(_102_)
  );
  NOT _136_ (
    .A(data2send_to_LDMX_estruct[2]),
    .Y(_103_)
  );
  NOR _137_ (
    .A(_091_),
    .B(reset),
    .Y(_002_[7])
  );
  NOR _138_ (
    .A(reset),
    .B(_093_),
    .Y(_002_[6])
  );
  NOR _139_ (
    .A(reset),
    .B(_094_),
    .Y(_002_[5])
  );
  NOR _140_ (
    .A(reset),
    .B(_095_),
    .Y(_002_[2])
  );
  NOR _141_ (
    .A(reset),
    .B(_096_),
    .Y(_002_[4])
  );
  NOR _142_ (
    .A(reset),
    .B(_097_),
    .Y(_002_[3])
  );
  NOR _143_ (
    .A(reset),
    .B(_098_),
    .Y(_002_[1])
  );
  NOR _144_ (
    .A(reset),
    .B(_099_),
    .Y(_002_[0])
  );
  NAND _145_ (
    .A(active_estruct_to_PS),
    .B(_092_),
    .Y(_104_)
  );
  NOR _146_ (
    .A(BC_counter[2]),
    .B(reset),
    .Y(_105_)
  );
  NAND _147_ (
    .A(data2send_to_LDMX_estruct[3]),
    .B(data2send_to_LDMX_estruct[4]),
    .Y(_106_)
  );
  NAND _148_ (
    .A(data2send_to_LDMX_estruct[5]),
    .B(data2send_to_LDMX_estruct[7]),
    .Y(_107_)
  );
  NOR _149_ (
    .A(_106_),
    .B(_107_),
    .Y(_108_)
  );
  NOT _150_ (
    .A(_108_),
    .Y(_109_)
  );
  NOR _151_ (
    .A(data2send_to_LDMX_estruct[0]),
    .B(data2send_to_LDMX_estruct[1]),
    .Y(_110_)
  );
  NAND _152_ (
    .A(_085_),
    .B(_086_),
    .Y(_111_)
  );
  NOR _153_ (
    .A(data2send_to_LDMX_estruct[6]),
    .B(_103_),
    .Y(_112_)
  );
  NAND _154_ (
    .A(_087_),
    .B(data2send_to_LDMX_estruct[2]),
    .Y(_113_)
  );
  NOR _155_ (
    .A(_111_),
    .B(_113_),
    .Y(_114_)
  );
  NAND _156_ (
    .A(_110_),
    .B(_112_),
    .Y(_115_)
  );
  NOR _157_ (
    .A(_109_),
    .B(_115_),
    .Y(_021_)
  );
  NAND _158_ (
    .A(_108_),
    .B(_114_),
    .Y(_022_)
  );
  NOR _159_ (
    .A(_100_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _160_ (
    .A(BC_counter[0]),
    .B(_021_),
    .Y(_024_)
  );
  NAND _161_ (
    .A(BC_counter[1]),
    .B(_023_),
    .Y(_025_)
  );
  NAND _162_ (
    .A(data2send_to_LDMX_estruct[3]),
    .B(data2send_to_LDMX_estruct[7]),
    .Y(_026_)
  );
  NOT _163_ (
    .A(_026_),
    .Y(_027_)
  );
  NOR _164_ (
    .A(data2send_to_LDMX_estruct[1]),
    .B(data2send_to_LDMX_estruct[6]),
    .Y(_028_)
  );
  NAND _165_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  NAND _166_ (
    .A(data2send_to_LDMX_estruct[4]),
    .B(data2send_to_LDMX_estruct[5]),
    .Y(_030_)
  );
  NOT _167_ (
    .A(_030_),
    .Y(_031_)
  );
  NOR _168_ (
    .A(data2send_to_LDMX_estruct[0]),
    .B(_103_),
    .Y(_032_)
  );
  NAND _169_ (
    .A(_031_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _170_ (
    .A(_029_),
    .B(_033_),
    .Y(_034_)
  );
  NAND _171_ (
    .A(BC_counter[0]),
    .B(_034_),
    .Y(_035_)
  );
  NOR _172_ (
    .A(_101_),
    .B(_035_),
    .Y(_036_)
  );
  NAND _173_ (
    .A(_105_),
    .B(_036_),
    .Y(_037_)
  );
  NAND _174_ (
    .A(_104_),
    .B(_037_),
    .Y(_001_)
  );
  NOR _175_ (
    .A(BC_counter[0]),
    .B(_021_),
    .Y(_038_)
  );
  NAND _176_ (
    .A(_092_),
    .B(_024_),
    .Y(_039_)
  );
  NOR _177_ (
    .A(_038_),
    .B(_039_),
    .Y(_000_[0])
  );
  NAND _178_ (
    .A(_101_),
    .B(_024_),
    .Y(_040_)
  );
  NAND _179_ (
    .A(_092_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _180_ (
    .A(_036_),
    .B(_041_),
    .Y(_000_[1])
  );
  NOR _181_ (
    .A(_084_),
    .B(reset),
    .Y(_042_)
  );
  NAND _182_ (
    .A(_025_),
    .B(_042_),
    .Y(_043_)
  );
  NAND _183_ (
    .A(_037_),
    .B(_043_),
    .Y(_000_[2])
  );
  NOR _184_ (
    .A(_104_),
    .B(_021_),
    .Y(_012_)
  );
  NAND _185_ (
    .A(selector[0]),
    .B(_092_),
    .Y(_003_[0])
  );
  NAND _186_ (
    .A(selector[1]),
    .B(selector[0]),
    .Y(_044_)
  );
  NOR _187_ (
    .A(selector[1]),
    .B(selector[0]),
    .Y(_045_)
  );
  NOR _188_ (
    .A(reset),
    .B(_045_),
    .Y(_046_)
  );
  NAND _189_ (
    .A(_044_),
    .B(_046_),
    .Y(_047_)
  );
  NOT _190_ (
    .A(_047_),
    .Y(_003_[1])
  );
  NOR _191_ (
    .A(_090_),
    .B(_044_),
    .Y(_048_)
  );
  NAND _192_ (
    .A(_090_),
    .B(_044_),
    .Y(_049_)
  );
  NAND _193_ (
    .A(_092_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _194_ (
    .A(_048_),
    .B(_050_),
    .Y(_003_[2])
  );
  NAND _195_ (
    .A(_102_),
    .B(_048_),
    .Y(_051_)
  );
  NAND _196_ (
    .A(_092_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _197_ (
    .A(temp7),
    .B(_048_),
    .Y(_053_)
  );
  NOR _198_ (
    .A(_052_),
    .B(_053_),
    .Y(_011_)
  );
  NOR _199_ (
    .A(_088_),
    .B(selector[0]),
    .Y(_054_)
  );
  NAND _200_ (
    .A(selector[2]),
    .B(_054_),
    .Y(_055_)
  );
  NAND _201_ (
    .A(_098_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _202_ (
    .A(data_in),
    .B(_055_),
    .Y(_057_)
  );
  NAND _203_ (
    .A(_092_),
    .B(_056_),
    .Y(_058_)
  );
  NOR _204_ (
    .A(_057_),
    .B(_058_),
    .Y(_010_)
  );
  NOR _205_ (
    .A(selector[1]),
    .B(_089_),
    .Y(_059_)
  );
  NAND _206_ (
    .A(selector[2]),
    .B(_059_),
    .Y(_060_)
  );
  NAND _207_ (
    .A(_095_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _208_ (
    .A(data_in),
    .B(_060_),
    .Y(_062_)
  );
  NAND _209_ (
    .A(_092_),
    .B(_061_),
    .Y(_063_)
  );
  NOR _210_ (
    .A(_062_),
    .B(_063_),
    .Y(_009_)
  );
  NAND _211_ (
    .A(selector[2]),
    .B(_045_),
    .Y(_064_)
  );
  NAND _212_ (
    .A(_097_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _213_ (
    .A(data_in),
    .B(_064_),
    .Y(_066_)
  );
  NAND _214_ (
    .A(_092_),
    .B(_065_),
    .Y(_067_)
  );
  NOR _215_ (
    .A(_066_),
    .B(_067_),
    .Y(_008_)
  );
  NOR _216_ (
    .A(selector[2]),
    .B(_044_),
    .Y(_068_)
  );
  NOR _217_ (
    .A(temp3),
    .B(_068_),
    .Y(_069_)
  );
  NAND _218_ (
    .A(_102_),
    .B(_068_),
    .Y(_070_)
  );
  NAND _219_ (
    .A(_092_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _220_ (
    .A(_069_),
    .B(_071_),
    .Y(_007_)
  );
  NAND _221_ (
    .A(_090_),
    .B(_054_),
    .Y(_072_)
  );
  NAND _222_ (
    .A(_094_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _223_ (
    .A(data_in),
    .B(_072_),
    .Y(_074_)
  );
  NAND _224_ (
    .A(_092_),
    .B(_073_),
    .Y(_075_)
  );
  NOR _225_ (
    .A(_074_),
    .B(_075_),
    .Y(_006_)
  );
  NAND _226_ (
    .A(_090_),
    .B(_059_),
    .Y(_076_)
  );
  NAND _227_ (
    .A(_093_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _228_ (
    .A(data_in),
    .B(_076_),
    .Y(_078_)
  );
  NAND _229_ (
    .A(_092_),
    .B(_077_),
    .Y(_079_)
  );
  NOR _230_ (
    .A(_078_),
    .B(_079_),
    .Y(_005_)
  );
  NAND _231_ (
    .A(_090_),
    .B(_045_),
    .Y(_080_)
  );
  NAND _232_ (
    .A(_091_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _233_ (
    .A(data_in),
    .B(_080_),
    .Y(_082_)
  );
  NAND _234_ (
    .A(_092_),
    .B(_081_),
    .Y(_083_)
  );
  NOR _235_ (
    .A(_082_),
    .B(_083_),
    .Y(_004_)
  );
  NOT _236_ (
    .A(clk_32f),
    .Y(_013_)
  );
  NOT _237_ (
    .A(clk_32f),
    .Y(_014_)
  );
  NOT _238_ (
    .A(clk_32f),
    .Y(_015_)
  );
  NOT _239_ (
    .A(clk_32f),
    .Y(_016_)
  );
  NOT _240_ (
    .A(clk_32f),
    .Y(_017_)
  );
  NOT _241_ (
    .A(clk_32f),
    .Y(_018_)
  );
  NOT _242_ (
    .A(clk_32f),
    .Y(_019_)
  );
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  DFF _243_ (
    .C(clk_4f),
    .D(_012_),
    .Q(valid_out_to_LDMX_estruct)
  );
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  DFF _244_ (
    .C(clk_4f),
    .D(_002_[0]),
    .Q(data2send_to_LDMX_estruct[0])
  );
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  DFF _245_ (
    .C(clk_4f),
    .D(_002_[1]),
    .Q(data2send_to_LDMX_estruct[1])
  );
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  DFF _246_ (
    .C(clk_4f),
    .D(_002_[2]),
    .Q(data2send_to_LDMX_estruct[2])
  );
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  DFF _247_ (
    .C(clk_4f),
    .D(_002_[3]),
    .Q(data2send_to_LDMX_estruct[3])
  );
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  DFF _248_ (
    .C(clk_4f),
    .D(_002_[4]),
    .Q(data2send_to_LDMX_estruct[4])
  );
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  DFF _249_ (
    .C(clk_4f),
    .D(_002_[5]),
    .Q(data2send_to_LDMX_estruct[5])
  );
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  DFF _250_ (
    .C(clk_4f),
    .D(_002_[6]),
    .Q(data2send_to_LDMX_estruct[6])
  );
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  DFF _251_ (
    .C(clk_4f),
    .D(_002_[7]),
    .Q(data2send_to_LDMX_estruct[7])
  );
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  DFF _252_ (
    .C(clk_4f),
    .D(_001_),
    .Q(active_estruct_to_PS)
  );
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  DFF _253_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(BC_counter[0])
  );
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  DFF _254_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(BC_counter[1])
  );
  (* src = "SerialParalelo_verde_estruct.v:76" *)
  DFF _255_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(BC_counter[2])
  );
  (* src = "SerialParalelo_verde_estruct.v:64" *)
  DFF _256_ (
    .C(clk_32f),
    .D(_003_[0]),
    .Q(selector[0])
  );
  (* src = "SerialParalelo_verde_estruct.v:64" *)
  DFF _257_ (
    .C(clk_32f),
    .D(_003_[1]),
    .Q(selector[1])
  );
  (* src = "SerialParalelo_verde_estruct.v:64" *)
  DFF _258_ (
    .C(clk_32f),
    .D(_003_[2]),
    .Q(selector[2])
  );
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  DFF _259_ (
    .C(_013_),
    .D(_004_),
    .Q(temp0)
  );
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  DFF _260_ (
    .C(_014_),
    .D(_005_),
    .Q(temp1)
  );
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  DFF _261_ (
    .C(_015_),
    .D(_006_),
    .Q(temp2)
  );
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  DFF _262_ (
    .C(_016_),
    .D(_007_),
    .Q(temp3)
  );
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  DFF _263_ (
    .C(_017_),
    .D(_008_),
    .Q(temp4)
  );
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  DFF _264_ (
    .C(_018_),
    .D(_009_),
    .Q(temp5)
  );
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  DFF _265_ (
    .C(_019_),
    .D(_010_),
    .Q(temp6)
  );
  (* src = "SerialParalelo_verde_estruct.v:12" *)
  DFF _266_ (
    .C(_020_),
    .D(_011_),
    .Q(temp7)
  );
endmodule
