/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "SerialParalelo_azul_estruct.v:1.1-107.10" *)
module SerialParalelo_azul_estruct(clk_4f, clk_32f, data_in, reset, recirculacion_estruct);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  (* src = "SerialParalelo_azul_estruct.v:8.15-8.25" *)
  wire [2:0] BC_counter;
  (* src = "SerialParalelo_azul_estruct.v:2.19-2.26" *)
  input clk_32f;
  (* src = "SerialParalelo_azul_estruct.v:2.11-2.17" *)
  input clk_4f;
  (* src = "SerialParalelo_azul_estruct.v:10.15-10.24" *)
  wire [7:0] data2send;
  (* src = "SerialParalelo_azul_estruct.v:2.28-2.35" *)
  input data_in;
  (* src = "SerialParalelo_azul_estruct.v:3.16-3.29" *)
  output recirculacion_estruct;
  (* src = "SerialParalelo_azul_estruct.v:2.37-2.42" *)
  input reset;
  (* src = "SerialParalelo_azul_estruct.v:7.15-7.23" *)
  wire [2:0] selector;
  (* src = "SerialParalelo_azul_estruct.v:6.9-6.14" *)
  wire temp0;
  (* src = "SerialParalelo_azul_estruct.v:6.15-6.20" *)
  wire temp1;
  (* src = "SerialParalelo_azul_estruct.v:6.21-6.26" *)
  wire temp2;
  (* src = "SerialParalelo_azul_estruct.v:6.27-6.32" *)
  wire temp3;
  (* src = "SerialParalelo_azul_estruct.v:6.33-6.38" *)
  wire temp4;
  (* src = "SerialParalelo_azul_estruct.v:6.39-6.44" *)
  wire temp5;
  (* src = "SerialParalelo_azul_estruct.v:6.45-6.50" *)
  wire temp6;
  (* src = "SerialParalelo_azul_estruct.v:6.51-6.56" *)
  wire temp7;
  NOT _114_ (
    .A(reset),
    .Y(_076_)
  );
  NOT _115_ (
    .A(data_in),
    .Y(_077_)
  );
  NOT _116_ (
    .A(temp7),
    .Y(_078_)
  );
  NOT _117_ (
    .A(clk_32f),
    .Y(_006_)
  );
  NOT _118_ (
    .A(temp6),
    .Y(_079_)
  );
  NOT _119_ (
    .A(temp5),
    .Y(_080_)
  );
  NOT _120_ (
    .A(temp4),
    .Y(_081_)
  );
  NOT _121_ (
    .A(temp3),
    .Y(_082_)
  );
  NOT _122_ (
    .A(temp2),
    .Y(_083_)
  );
  NOT _123_ (
    .A(temp1),
    .Y(_084_)
  );
  NOT _124_ (
    .A(temp0),
    .Y(_085_)
  );
  NOT _125_ (
    .A(BC_counter[2]),
    .Y(_086_)
  );
  NOT _126_ (
    .A(BC_counter[1]),
    .Y(_087_)
  );
  NOT _127_ (
    .A(BC_counter[0]),
    .Y(_088_)
  );
  NOT _128_ (
    .A(data2send[7]),
    .Y(_089_)
  );
  NOT _129_ (
    .A(selector[2]),
    .Y(_090_)
  );
  NOT _130_ (
    .A(selector[1]),
    .Y(_091_)
  );
  NOT _131_ (
    .A(selector[0]),
    .Y(_092_)
  );
  NOT _132_ (
    .A(data2send[0]),
    .Y(_093_)
  );
  NAND _133_ (
    .A(selector[1]),
    .B(selector[0]),
    .Y(_094_)
  );
  NOT _134_ (
    .A(_094_),
    .Y(_095_)
  );
  NAND _135_ (
    .A(selector[2]),
    .B(_095_),
    .Y(_096_)
  );
  NOR _136_ (
    .A(_077_),
    .B(_096_),
    .Y(_097_)
  );
  NAND _137_ (
    .A(temp7),
    .B(_096_),
    .Y(_098_)
  );
  NOT _138_ (
    .A(_098_),
    .Y(_099_)
  );
  NOR _139_ (
    .A(_097_),
    .B(_099_),
    .Y(_100_)
  );
  NOR _140_ (
    .A(reset),
    .B(_100_),
    .Y(_030_)
  );
  NOR _141_ (
    .A(_091_),
    .B(selector[0]),
    .Y(_101_)
  );
  NAND _142_ (
    .A(selector[2]),
    .B(_101_),
    .Y(_102_)
  );
  NAND _143_ (
    .A(_079_),
    .B(_102_),
    .Y(_103_)
  );
  NOR _144_ (
    .A(data_in),
    .B(_102_),
    .Y(_104_)
  );
  NAND _145_ (
    .A(_076_),
    .B(_103_),
    .Y(_105_)
  );
  NOR _146_ (
    .A(_104_),
    .B(_105_),
    .Y(_029_)
  );
  NOR _147_ (
    .A(selector[1]),
    .B(_092_),
    .Y(_106_)
  );
  NAND _148_ (
    .A(selector[2]),
    .B(_106_),
    .Y(_107_)
  );
  NAND _149_ (
    .A(_080_),
    .B(_107_),
    .Y(_108_)
  );
  NOR _150_ (
    .A(data_in),
    .B(_107_),
    .Y(_109_)
  );
  NAND _151_ (
    .A(_076_),
    .B(_108_),
    .Y(_110_)
  );
  NOR _152_ (
    .A(_109_),
    .B(_110_),
    .Y(_028_)
  );
  NOR _153_ (
    .A(selector[1]),
    .B(selector[0]),
    .Y(_111_)
  );
  NAND _154_ (
    .A(selector[2]),
    .B(_111_),
    .Y(_112_)
  );
  NAND _155_ (
    .A(_081_),
    .B(_112_),
    .Y(_113_)
  );
  NOR _156_ (
    .A(data_in),
    .B(_112_),
    .Y(_031_)
  );
  NAND _157_ (
    .A(_076_),
    .B(_113_),
    .Y(_032_)
  );
  NOR _158_ (
    .A(_031_),
    .B(_032_),
    .Y(_027_)
  );
  NOR _159_ (
    .A(selector[2]),
    .B(_094_),
    .Y(_033_)
  );
  NOR _160_ (
    .A(temp3),
    .B(_033_),
    .Y(_034_)
  );
  NAND _161_ (
    .A(_077_),
    .B(_033_),
    .Y(_035_)
  );
  NAND _162_ (
    .A(_076_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _163_ (
    .A(_034_),
    .B(_036_),
    .Y(_026_)
  );
  NAND _164_ (
    .A(_090_),
    .B(_101_),
    .Y(_037_)
  );
  NAND _165_ (
    .A(_083_),
    .B(_037_),
    .Y(_038_)
  );
  NOR _166_ (
    .A(data_in),
    .B(_037_),
    .Y(_039_)
  );
  NAND _167_ (
    .A(_076_),
    .B(_038_),
    .Y(_040_)
  );
  NOR _168_ (
    .A(_039_),
    .B(_040_),
    .Y(_025_)
  );
  NAND _169_ (
    .A(_090_),
    .B(_106_),
    .Y(_041_)
  );
  NAND _170_ (
    .A(_084_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _171_ (
    .A(data_in),
    .B(_041_),
    .Y(_043_)
  );
  NAND _172_ (
    .A(_076_),
    .B(_042_),
    .Y(_044_)
  );
  NOR _173_ (
    .A(_043_),
    .B(_044_),
    .Y(_024_)
  );
  NAND _174_ (
    .A(_090_),
    .B(_111_),
    .Y(_045_)
  );
  NAND _175_ (
    .A(_085_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _176_ (
    .A(data_in),
    .B(_045_),
    .Y(_047_)
  );
  NAND _177_ (
    .A(_076_),
    .B(_046_),
    .Y(_048_)
  );
  NOR _178_ (
    .A(_047_),
    .B(_048_),
    .Y(_023_)
  );
  NOR _179_ (
    .A(_089_),
    .B(data2send[0]),
    .Y(_049_)
  );
  NAND _180_ (
    .A(data2send[7]),
    .B(_093_),
    .Y(_050_)
  );
  NOR _181_ (
    .A(data2send[1]),
    .B(data2send[6]),
    .Y(_051_)
  );
  NOT _182_ (
    .A(_051_),
    .Y(_052_)
  );
  NOR _183_ (
    .A(_050_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _184_ (
    .A(_049_),
    .B(_051_),
    .Y(_054_)
  );
  NAND _185_ (
    .A(data2send[2]),
    .B(data2send[3]),
    .Y(_055_)
  );
  NAND _186_ (
    .A(data2send[4]),
    .B(data2send[5]),
    .Y(_056_)
  );
  NOR _187_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  NOT _188_ (
    .A(_057_),
    .Y(_058_)
  );
  NOR _189_ (
    .A(_054_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _190_ (
    .A(_053_),
    .B(_057_),
    .Y(_060_)
  );
  NOR _191_ (
    .A(_088_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _192_ (
    .A(BC_counter[0]),
    .B(_059_),
    .Y(_062_)
  );
  NOR _193_ (
    .A(_087_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _194_ (
    .A(BC_counter[1]),
    .B(_061_),
    .Y(_064_)
  );
  NOR _195_ (
    .A(BC_counter[2]),
    .B(_064_),
    .Y(_065_)
  );
  NOR _196_ (
    .A(_086_),
    .B(_063_),
    .Y(_066_)
  );
  NOR _197_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _198_ (
    .A(reset),
    .B(_067_),
    .Y(_022_)
  );
  NAND _199_ (
    .A(_087_),
    .B(_062_),
    .Y(_068_)
  );
  NAND _200_ (
    .A(_076_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _201_ (
    .A(_063_),
    .B(_069_),
    .Y(_021_)
  );
  NAND _202_ (
    .A(_088_),
    .B(_060_),
    .Y(_070_)
  );
  NAND _203_ (
    .A(_076_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _204_ (
    .A(_061_),
    .B(_071_),
    .Y(_020_)
  );
  NOR _205_ (
    .A(recirculacion_estruct),
    .B(_065_),
    .Y(_072_)
  );
  NOR _206_ (
    .A(reset),
    .B(_072_),
    .Y(_019_)
  );
  NOR _207_ (
    .A(selector[2]),
    .B(_095_),
    .Y(_073_)
  );
  NAND _208_ (
    .A(_076_),
    .B(_096_),
    .Y(_074_)
  );
  NOR _209_ (
    .A(_073_),
    .B(_074_),
    .Y(_018_)
  );
  NAND _210_ (
    .A(_076_),
    .B(_094_),
    .Y(_075_)
  );
  NOR _211_ (
    .A(_111_),
    .B(_075_),
    .Y(_017_)
  );
  NAND _212_ (
    .A(_076_),
    .B(selector[0]),
    .Y(_016_)
  );
  NOR _213_ (
    .A(reset),
    .B(_085_),
    .Y(_015_)
  );
  NOR _214_ (
    .A(reset),
    .B(_084_),
    .Y(_014_)
  );
  NOR _215_ (
    .A(reset),
    .B(_083_),
    .Y(_013_)
  );
  NOR _216_ (
    .A(reset),
    .B(_082_),
    .Y(_012_)
  );
  NOR _217_ (
    .A(reset),
    .B(_081_),
    .Y(_011_)
  );
  NOR _218_ (
    .A(reset),
    .B(_080_),
    .Y(_010_)
  );
  NOR _219_ (
    .A(reset),
    .B(_079_),
    .Y(_009_)
  );
  NOR _220_ (
    .A(reset),
    .B(_078_),
    .Y(_008_)
  );
  NOT _221_ (
    .A(clk_32f),
    .Y(_005_)
  );
  NOT _222_ (
    .A(clk_32f),
    .Y(_004_)
  );
  NOT _223_ (
    .A(clk_32f),
    .Y(_003_)
  );
  NOT _224_ (
    .A(clk_32f),
    .Y(_002_)
  );
  NOT _225_ (
    .A(clk_32f),
    .Y(_001_)
  );
  NOT _226_ (
    .A(clk_32f),
    .Y(_000_)
  );
  NOT _227_ (
    .A(clk_32f),
    .Y(_007_)
  );
  (* src = "SerialParalelo_azul_estruct.v:77.1-104.4" *)
  DFF _228_ (
    .C(clk_4f),
    .D(_008_),
    .Q(data2send[0])
  );
  (* src = "SerialParalelo_azul_estruct.v:77.1-104.4" *)
  DFF _229_ (
    .C(clk_4f),
    .D(_009_),
    .Q(data2send[1])
  );
  (* src = "SerialParalelo_azul_estruct.v:77.1-104.4" *)
  DFF _230_ (
    .C(clk_4f),
    .D(_010_),
    .Q(data2send[2])
  );
  (* src = "SerialParalelo_azul_estruct.v:77.1-104.4" *)
  DFF _231_ (
    .C(clk_4f),
    .D(_011_),
    .Q(data2send[3])
  );
  (* src = "SerialParalelo_azul_estruct.v:77.1-104.4" *)
  DFF _232_ (
    .C(clk_4f),
    .D(_012_),
    .Q(data2send[4])
  );
  (* src = "SerialParalelo_azul_estruct.v:77.1-104.4" *)
  DFF _233_ (
    .C(clk_4f),
    .D(_013_),
    .Q(data2send[5])
  );
  (* src = "SerialParalelo_azul_estruct.v:77.1-104.4" *)
  DFF _234_ (
    .C(clk_4f),
    .D(_014_),
    .Q(data2send[6])
  );
  (* src = "SerialParalelo_azul_estruct.v:77.1-104.4" *)
  DFF _235_ (
    .C(clk_4f),
    .D(_015_),
    .Q(data2send[7])
  );
  (* src = "SerialParalelo_azul_estruct.v:65.1-72.4" *)
  DFF _236_ (
    .C(clk_32f),
    .D(_016_),
    .Q(selector[0])
  );
  (* src = "SerialParalelo_azul_estruct.v:65.1-72.4" *)
  DFF _237_ (
    .C(clk_32f),
    .D(_017_),
    .Q(selector[1])
  );
  (* src = "SerialParalelo_azul_estruct.v:65.1-72.4" *)
  DFF _238_ (
    .C(clk_32f),
    .D(_018_),
    .Q(selector[2])
  );
  (* src = "SerialParalelo_azul_estruct.v:77.1-104.4" *)
  DFF _239_ (
    .C(clk_4f),
    .D(_019_),
    .Q(recirculacion_estruct)
  );
  (* src = "SerialParalelo_azul_estruct.v:77.1-104.4" *)
  DFF _240_ (
    .C(clk_4f),
    .D(_020_),
    .Q(BC_counter[0])
  );
  (* src = "SerialParalelo_azul_estruct.v:77.1-104.4" *)
  DFF _241_ (
    .C(clk_4f),
    .D(_021_),
    .Q(BC_counter[1])
  );
  (* src = "SerialParalelo_azul_estruct.v:77.1-104.4" *)
  DFF _242_ (
    .C(clk_4f),
    .D(_022_),
    .Q(BC_counter[2])
  );
  (* src = "SerialParalelo_azul_estruct.v:13.2-61.5" *)
  DFF _243_ (
    .C(_000_),
    .D(_023_),
    .Q(temp0)
  );
  (* src = "SerialParalelo_azul_estruct.v:13.2-61.5" *)
  DFF _244_ (
    .C(_001_),
    .D(_024_),
    .Q(temp1)
  );
  (* src = "SerialParalelo_azul_estruct.v:13.2-61.5" *)
  DFF _245_ (
    .C(_002_),
    .D(_025_),
    .Q(temp2)
  );
  (* src = "SerialParalelo_azul_estruct.v:13.2-61.5" *)
  DFF _246_ (
    .C(_003_),
    .D(_026_),
    .Q(temp3)
  );
  (* src = "SerialParalelo_azul_estruct.v:13.2-61.5" *)
  DFF _247_ (
    .C(_004_),
    .D(_027_),
    .Q(temp4)
  );
  (* src = "SerialParalelo_azul_estruct.v:13.2-61.5" *)
  DFF _248_ (
    .C(_005_),
    .D(_028_),
    .Q(temp5)
  );
  (* src = "SerialParalelo_azul_estruct.v:13.2-61.5" *)
  DFF _249_ (
    .C(_006_),
    .D(_029_),
    .Q(temp6)
  );
  (* src = "SerialParalelo_azul_estruct.v:13.2-61.5" *)
  DFF _250_ (
    .C(_007_),
    .D(_030_),
    .Q(temp7)
  );
endmodule
