/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "ParaleloSerial_azul_estruct.v:1.1-74.10" *)
module ParaleloSerial_azul_estruct(data_in, clk4_f, clk32_f, valid_in, reset, data_out_estruct);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  (* src = "ParaleloSerial_azul_estruct.v:3.19-3.26" *)
  input clk32_f;
  (* src = "ParaleloSerial_azul_estruct.v:3.11-3.17" *)
  input clk4_f;
  (* src = "ParaleloSerial_azul_estruct.v:8.15-8.24" *)
  wire [7:0] data2send;
  (* src = "ParaleloSerial_azul_estruct.v:2.17-2.24" *)
  input [7:0] data_in;
  (* src = "ParaleloSerial_azul_estruct.v:5.16-5.24" *)
  output data_out_estruct;
  (* src = "ParaleloSerial_azul_estruct.v:10.18-10.27" *)
  wire idontknow;
  (* src = "ParaleloSerial_azul_estruct.v:10.9-10.16" *)
  wire lastbit;
  (* src = "ParaleloSerial_azul_estruct.v:4.11-4.16" *)
  input reset;
  (* src = "ParaleloSerial_azul_estruct.v:9.15-9.23" *)
  wire [2:0] selector;
  (* src = "ParaleloSerial_azul_estruct.v:3.28-3.36" *)
  input valid_in;
  NOT _097_ (
    .A(data2send[1]),
    .Y(_043_)
  );
  NOT _098_ (
    .A(reset),
    .Y(_044_)
  );
  NOT _099_ (
    .A(data2send[0]),
    .Y(_045_)
  );
  NOT _100_ (
    .A(selector[2]),
    .Y(_046_)
  );
  NOT _101_ (
    .A(selector[1]),
    .Y(_047_)
  );
  NOT _102_ (
    .A(selector[0]),
    .Y(_048_)
  );
  NOT _103_ (
    .A(valid_in),
    .Y(_049_)
  );
  NOR _104_ (
    .A(selector[1]),
    .B(selector[0]),
    .Y(_050_)
  );
  NOT _105_ (
    .A(_050_),
    .Y(_051_)
  );
  NOR _106_ (
    .A(selector[2]),
    .B(_051_),
    .Y(_052_)
  );
  NOR _107_ (
    .A(lastbit),
    .B(_052_),
    .Y(_053_)
  );
  NAND _108_ (
    .A(_045_),
    .B(_052_),
    .Y(_054_)
  );
  NAND _109_ (
    .A(_044_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _110_ (
    .A(_053_),
    .B(_055_),
    .Y(_012_)
  );
  NOR _111_ (
    .A(_047_),
    .B(selector[0]),
    .Y(_056_)
  );
  NAND _112_ (
    .A(selector[2]),
    .B(_056_),
    .Y(_057_)
  );
  NOR _113_ (
    .A(_049_),
    .B(data_in[7]),
    .Y(_058_)
  );
  NOR _114_ (
    .A(_057_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _115_ (
    .A(data2send[7]),
    .B(_057_),
    .Y(_060_)
  );
  NOT _116_ (
    .A(_060_),
    .Y(_061_)
  );
  NOR _117_ (
    .A(_059_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _118_ (
    .A(reset),
    .B(_062_),
    .Y(_011_)
  );
  NAND _119_ (
    .A(valid_in),
    .B(data_in[6]),
    .Y(_063_)
  );
  NOR _120_ (
    .A(_057_),
    .B(_063_),
    .Y(_064_)
  );
  NAND _121_ (
    .A(data2send[6]),
    .B(_057_),
    .Y(_065_)
  );
  NOT _122_ (
    .A(_065_),
    .Y(_066_)
  );
  NOR _123_ (
    .A(_064_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _124_ (
    .A(reset),
    .B(_067_),
    .Y(_010_)
  );
  NOR _125_ (
    .A(_049_),
    .B(data_in[5]),
    .Y(_068_)
  );
  NOR _126_ (
    .A(_057_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _127_ (
    .A(data2send[5]),
    .B(_057_),
    .Y(_070_)
  );
  NOT _128_ (
    .A(_070_),
    .Y(_071_)
  );
  NOR _129_ (
    .A(_069_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _130_ (
    .A(reset),
    .B(_072_),
    .Y(_009_)
  );
  NOR _131_ (
    .A(_049_),
    .B(data_in[4]),
    .Y(_073_)
  );
  NOR _132_ (
    .A(_057_),
    .B(_073_),
    .Y(_074_)
  );
  NAND _133_ (
    .A(data2send[4]),
    .B(_057_),
    .Y(_075_)
  );
  NOT _134_ (
    .A(_075_),
    .Y(_076_)
  );
  NOR _135_ (
    .A(_074_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _136_ (
    .A(reset),
    .B(_077_),
    .Y(_008_)
  );
  NOR _137_ (
    .A(_049_),
    .B(data_in[3]),
    .Y(_078_)
  );
  NOR _138_ (
    .A(_057_),
    .B(_078_),
    .Y(_079_)
  );
  NAND _139_ (
    .A(data2send[3]),
    .B(_057_),
    .Y(_080_)
  );
  NOT _140_ (
    .A(_080_),
    .Y(_081_)
  );
  NOR _141_ (
    .A(_079_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _142_ (
    .A(reset),
    .B(_082_),
    .Y(_007_)
  );
  NOR _143_ (
    .A(_049_),
    .B(data_in[2]),
    .Y(_083_)
  );
  NOR _144_ (
    .A(_057_),
    .B(_083_),
    .Y(_084_)
  );
  NAND _145_ (
    .A(data2send[2]),
    .B(_057_),
    .Y(_085_)
  );
  NOT _146_ (
    .A(_085_),
    .Y(_086_)
  );
  NOR _147_ (
    .A(_084_),
    .B(_086_),
    .Y(_087_)
  );
  NOR _148_ (
    .A(reset),
    .B(_087_),
    .Y(_006_)
  );
  NAND _149_ (
    .A(valid_in),
    .B(data_in[1]),
    .Y(_088_)
  );
  NOR _150_ (
    .A(_057_),
    .B(_088_),
    .Y(_089_)
  );
  NAND _151_ (
    .A(data2send[1]),
    .B(_057_),
    .Y(_090_)
  );
  NOT _152_ (
    .A(_090_),
    .Y(_091_)
  );
  NOR _153_ (
    .A(_089_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _154_ (
    .A(reset),
    .B(_092_),
    .Y(_005_)
  );
  NAND _155_ (
    .A(data_in[0]),
    .B(valid_in),
    .Y(_093_)
  );
  NOR _156_ (
    .A(_057_),
    .B(_093_),
    .Y(_094_)
  );
  NAND _157_ (
    .A(data2send[0]),
    .B(_057_),
    .Y(_095_)
  );
  NOT _158_ (
    .A(_095_),
    .Y(_096_)
  );
  NOR _159_ (
    .A(_094_),
    .B(_096_),
    .Y(_014_)
  );
  NOR _160_ (
    .A(reset),
    .B(_014_),
    .Y(_004_)
  );
  NOR _161_ (
    .A(_047_),
    .B(_048_),
    .Y(_015_)
  );
  NAND _162_ (
    .A(data2send[4]),
    .B(_015_),
    .Y(_016_)
  );
  NOR _163_ (
    .A(selector[1]),
    .B(_048_),
    .Y(_017_)
  );
  NAND _164_ (
    .A(data2send[6]),
    .B(_017_),
    .Y(_018_)
  );
  NAND _165_ (
    .A(data2send[5]),
    .B(_056_),
    .Y(_019_)
  );
  NAND _166_ (
    .A(data2send[7]),
    .B(_050_),
    .Y(_020_)
  );
  NAND _167_ (
    .A(_018_),
    .B(_019_),
    .Y(_021_)
  );
  NAND _168_ (
    .A(_016_),
    .B(_020_),
    .Y(_022_)
  );
  NOR _169_ (
    .A(selector[2]),
    .B(_022_),
    .Y(_023_)
  );
  NOT _170_ (
    .A(_023_),
    .Y(_024_)
  );
  NOR _171_ (
    .A(_021_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _172_ (
    .A(idontknow),
    .B(_056_),
    .Y(_026_)
  );
  NAND _173_ (
    .A(lastbit),
    .B(_015_),
    .Y(_027_)
  );
  NAND _174_ (
    .A(data2send[3]),
    .B(_050_),
    .Y(_028_)
  );
  NAND _175_ (
    .A(data2send[2]),
    .B(_017_),
    .Y(_029_)
  );
  NAND _176_ (
    .A(selector[2]),
    .B(_028_),
    .Y(_030_)
  );
  NAND _177_ (
    .A(_027_),
    .B(_029_),
    .Y(_031_)
  );
  NOR _178_ (
    .A(_030_),
    .B(_031_),
    .Y(_032_)
  );
  NAND _179_ (
    .A(_026_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _180_ (
    .A(_044_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _181_ (
    .A(_025_),
    .B(_034_),
    .Y(_003_)
  );
  NAND _182_ (
    .A(_046_),
    .B(_015_),
    .Y(_035_)
  );
  NOR _183_ (
    .A(_046_),
    .B(_015_),
    .Y(_036_)
  );
  NOR _184_ (
    .A(reset),
    .B(_036_),
    .Y(_037_)
  );
  NAND _185_ (
    .A(_035_),
    .B(_037_),
    .Y(_002_)
  );
  NOR _186_ (
    .A(reset),
    .B(_050_),
    .Y(_038_)
  );
  NOT _187_ (
    .A(_038_),
    .Y(_039_)
  );
  NOR _188_ (
    .A(_015_),
    .B(_039_),
    .Y(_001_)
  );
  NOR _189_ (
    .A(reset),
    .B(selector[0]),
    .Y(_000_)
  );
  NOR _190_ (
    .A(idontknow),
    .B(_052_),
    .Y(_040_)
  );
  NAND _191_ (
    .A(_043_),
    .B(_052_),
    .Y(_041_)
  );
  NAND _192_ (
    .A(_044_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _193_ (
    .A(_040_),
    .B(_042_),
    .Y(_013_)
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _194_ (
    .C(clk32_f),
    .D(_000_),
    .Q(selector[0])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _195_ (
    .C(clk32_f),
    .D(_001_),
    .Q(selector[1])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _196_ (
    .C(clk32_f),
    .D(_002_),
    .Q(selector[2])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _197_ (
    .C(clk32_f),
    .D(_003_),
    .Q(data_out_estruct)
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _198_ (
    .C(clk32_f),
    .D(_004_),
    .Q(data2send[0])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _199_ (
    .C(clk32_f),
    .D(_005_),
    .Q(data2send[1])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _200_ (
    .C(clk32_f),
    .D(_006_),
    .Q(data2send[2])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _201_ (
    .C(clk32_f),
    .D(_007_),
    .Q(data2send[3])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _202_ (
    .C(clk32_f),
    .D(_008_),
    .Q(data2send[4])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _203_ (
    .C(clk32_f),
    .D(_009_),
    .Q(data2send[5])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _204_ (
    .C(clk32_f),
    .D(_010_),
    .Q(data2send[6])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _205_ (
    .C(clk32_f),
    .D(_011_),
    .Q(data2send[7])
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _206_ (
    .C(clk32_f),
    .D(_012_),
    .Q(lastbit)
  );
  (* src = "ParaleloSerial_azul_estruct.v:12.5-72.8" *)
  DFF _207_ (
    .C(clk32_f),
    .D(_013_),
    .Q(idontknow)
  );
endmodule
