/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "ParaleloSerial_verde_estruct.v:1.1-129.10" *)
module ParaleloSerial_verde_estruct(clk4_f, clk32_f, valid_in, reset, data_out_estruct);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  (* src = "ParaleloSerial_verde_estruct.v:2.19-2.26" *)
  input clk32_f;
  (* src = "ParaleloSerial_verde_estruct.v:2.11-2.17" *)
  input clk4_f;
  (* src = "ParaleloSerial_verde_estruct.v:4.16-4.24" *)
  output data_out_estruct;
  (* src = "ParaleloSerial_verde_estruct.v:3.11-3.16" *)
  input reset;
  (* src = "ParaleloSerial_verde_estruct.v:7.15-7.23" *)
  wire [2:0] selector;
  (* src = "ParaleloSerial_verde_estruct.v:2.28-2.36" *)
  input valid_in;
  NOT _18_ (
    .A(reset),
    .Y(_04_)
  );
  NOT _19_ (
    .A(selector[1]),
    .Y(_05_)
  );
  NAND _20_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_06_)
  );
  NOR _21_ (
    .A(selector[2]),
    .B(_06_),
    .Y(_07_)
  );
  NAND _22_ (
    .A(selector[2]),
    .B(_06_),
    .Y(_08_)
  );
  NOR _23_ (
    .A(reset),
    .B(_07_),
    .Y(_09_)
  );
  NAND _24_ (
    .A(_08_),
    .B(_09_),
    .Y(_02_)
  );
  NAND _25_ (
    .A(selector[0]),
    .B(_05_),
    .Y(_10_)
  );
  NOR _26_ (
    .A(selector[0]),
    .B(_05_),
    .Y(_11_)
  );
  NOR _27_ (
    .A(reset),
    .B(_11_),
    .Y(_12_)
  );
  NAND _28_ (
    .A(_10_),
    .B(_12_),
    .Y(_01_)
  );
  NOR _29_ (
    .A(reset),
    .B(selector[0]),
    .Y(_00_)
  );
  NOR _30_ (
    .A(selector[2]),
    .B(valid_in),
    .Y(_13_)
  );
  NOT _31_ (
    .A(_13_),
    .Y(_14_)
  );
  NOR _32_ (
    .A(_10_),
    .B(_14_),
    .Y(_15_)
  );
  NAND _33_ (
    .A(selector[2]),
    .B(selector[1]),
    .Y(_16_)
  );
  NAND _34_ (
    .A(_04_),
    .B(_16_),
    .Y(_17_)
  );
  NOR _35_ (
    .A(_15_),
    .B(_17_),
    .Y(_03_)
  );
  (* src = "ParaleloSerial_verde_estruct.v:10.5-113.8" *)
  DFF _36_ (
    .C(clk32_f),
    .D(_00_),
    .Q(selector[0])
  );
  (* src = "ParaleloSerial_verde_estruct.v:10.5-113.8" *)
  DFF _37_ (
    .C(clk32_f),
    .D(_01_),
    .Q(selector[1])
  );
  (* src = "ParaleloSerial_verde_estruct.v:10.5-113.8" *)
  DFF _38_ (
    .C(clk32_f),
    .D(_02_),
    .Q(selector[2])
  );
  (* src = "ParaleloSerial_verde_estruct.v:10.5-113.8" *)
  DFF _39_ (
    .C(clk32_f),
    .D(_03_),
    .Q(data_out_estruct)
  );
endmodule
