/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "ParaleloSerial_IDL_estruct.v:1.1-70.10" *)
module ParaleloSerial_IDL_estruct(active, clk_32f, clk_4f, reset, IDL_estruct);
  (* src = "ParaleloSerial_IDL_estruct.v:12.1-58.4" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "ParaleloSerial_IDL_estruct.v:6.16-6.19" *)
  output IDL_estruct;
  reg IDL_estruct;
  (* src = "ParaleloSerial_IDL_estruct.v:2.11-2.17" *)
  input active;
  (* src = "ParaleloSerial_IDL_estruct.v:3.11-3.18" *)
  input clk_32f;
  (* src = "ParaleloSerial_IDL_estruct.v:4.11-4.17" *)
  input clk_4f;
  (* src = "ParaleloSerial_IDL_estruct.v:5.11-5.16" *)
  input reset;
  (* src = "ParaleloSerial_IDL_estruct.v:9.11-9.19" *)
  wire [2:0] selector;
  NOT _22_ (
    .A(reset),
    .Y(_04_)
  );
  NAND _23_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_05_)
  );
  NOR _24_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_06_)
  );
  NOT _25_ (
    .A(_06_),
    .Y(_07_)
  );
  NAND _26_ (
    .A(_05_),
    .B(_07_),
    .Y(_08_)
  );
  NAND _27_ (
    .A(_04_),
    .B(_08_),
    .Y(_02_)
  );
  NAND _28_ (
    .A(_04_),
    .B(selector[0]),
    .Y(_01_)
  );
  NAND _29_ (
    .A(selector[0]),
    .B(active),
    .Y(_09_)
  );
  NOT _30_ (
    .A(_09_),
    .Y(_10_)
  );
  NOR _31_ (
    .A(selector[2]),
    .B(selector[1]),
    .Y(_11_)
  );
  NOR _32_ (
    .A(selector[0]),
    .B(active),
    .Y(_12_)
  );
  NOT _33_ (
    .A(_12_),
    .Y(_13_)
  );
  NAND _34_ (
    .A(_11_),
    .B(_13_),
    .Y(_14_)
  );
  NOR _35_ (
    .A(_10_),
    .B(_14_),
    .Y(_15_)
  );
  NAND _36_ (
    .A(selector[2]),
    .B(selector[1]),
    .Y(_16_)
  );
  NAND _37_ (
    .A(_04_),
    .B(_16_),
    .Y(_17_)
  );
  NOR _38_ (
    .A(_15_),
    .B(_17_),
    .Y(_00_)
  );
  NOR _39_ (
    .A(selector[2]),
    .B(_05_),
    .Y(_18_)
  );
  NAND _40_ (
    .A(selector[2]),
    .B(_05_),
    .Y(_19_)
  );
  NOT _41_ (
    .A(_19_),
    .Y(_20_)
  );
  NOR _42_ (
    .A(_18_),
    .B(_20_),
    .Y(_21_)
  );
  NAND _43_ (
    .A(_04_),
    .B(_21_),
    .Y(_03_)
  );
  (* src = "ParaleloSerial_IDL_estruct.v:61.1-68.4" *)
  DFF _44_ (
    .C(clk_32f),
    .D(_01_),
    .Q(selector[0])
  );
  (* src = "ParaleloSerial_IDL_estruct.v:61.1-68.4" *)
  DFF _45_ (
    .C(clk_32f),
    .D(_02_),
    .Q(selector[1])
  );
  (* src = "ParaleloSerial_IDL_estruct.v:61.1-68.4" *)
  DFF _46_ (
    .C(clk_32f),
    .D(_03_),
    .Q(selector[2])
  );
  (* src = "ParaleloSerial_IDL_estruct.v:12.1-58.4" *)
  always @*
    if (!1'h0) IDL_estruct = _00_;
endmodule
