/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "SerialParalelo_estruct.v:1.1-88.10" *)
module SerialParalelo_estruct(clk_4f, clk_32f, data_in, data2send_estruct, data_out_estruct, active_estruct, valid_out_estruct);
  (* src = "SerialParalelo_estruct.v:38.1-40.4" *)
  wire [2:0] _000_;
  (* src = "SerialParalelo_estruct.v:39.15-39.25" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _001_;
  (* src = "SerialParalelo_estruct.v:59.20-59.32" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  (* src = "SerialParalelo_estruct.v:58.8-58.24" *)
  wire _045_;
  (* src = "SerialParalelo_estruct.v:16.8-16.32" *)
  wire _046_;
  (* src = "SerialParalelo_estruct.v:5.15-5.25" *)
  wire [3:0] BC_counter;
  (* src = "SerialParalelo_estruct.v:4.16-4.22" *)
  output active_estruct;
  (* src = "SerialParalelo_estruct.v:11.9-11.19" *)
  wire active_estruct_aux;
  (* src = "SerialParalelo_estruct.v:2.19-2.26" *)
  input clk_32f;
  (* src = "SerialParalelo_estruct.v:2.11-2.17" *)
  input clk_4f;
  (* src = "SerialParalelo_estruct.v:9.15-9.23" *)
  reg [2:0] cont_aux = 3'h0;
  (* src = "SerialParalelo_estruct.v:3.22-3.31" *)
  output [7:0] data2send_estruct;
  reg [7:0] data2send_estruct;
  (* src = "SerialParalelo_estruct.v:2.28-2.35" *)
  input data_in;
  (* src = "SerialParalelo_estruct.v:3.33-3.41" *)
  output [7:0] data_out_estruct;
  reg [7:0] data_out_estruct;
  (* src = "SerialParalelo_estruct.v:7.15-7.23" *)
  reg [2:0] selector = 3'h3;
  (* src = "SerialParalelo_estruct.v:8.15-8.27" *)
  reg [2:0] selectorprev = 3'h3;
  (* src = "SerialParalelo_estruct.v:6.9-6.14" *)
  reg temp0;
  (* src = "SerialParalelo_estruct.v:6.15-6.20" *)
  reg temp1;
  (* src = "SerialParalelo_estruct.v:6.21-6.26" *)
  reg temp2;
  (* src = "SerialParalelo_estruct.v:6.27-6.32" *)
  reg temp3;
  (* src = "SerialParalelo_estruct.v:6.33-6.38" *)
  reg temp4;
  (* src = "SerialParalelo_estruct.v:6.39-6.44" *)
  reg temp5;
  (* src = "SerialParalelo_estruct.v:6.45-6.50" *)
  reg temp6;
  (* src = "SerialParalelo_estruct.v:6.51-6.56" *)
  reg temp7;
  (* src = "SerialParalelo_estruct.v:10.9-10.18" *)
  reg valid_aux = 1'h0;
  (* src = "SerialParalelo_estruct.v:4.24-4.33" *)
  output valid_out_estruct;
  reg valid_out_estruct;
  assign { _001_[31:3], _000_ } = selector + (* src = "SerialParalelo_estruct.v:39.15-39.25" *) 32'd1;
  assign _002_ = cont_aux + (* src = "SerialParalelo_estruct.v:59.20-59.32" *) 32'd1;
  (* src = "SerialParalelo_estruct.v:56.1-63.4" *)
  always @(posedge clk_4f)
    if (_045_) cont_aux <= _002_[2:0];
  assign _004_ = ~ (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _046_;
  assign _005_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _035_, _034_, _033_, _032_, _031_, _030_, _029_ };
  assign _007_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _036_, _004_ };
  assign _008_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _037_, _034_, _033_, _032_, _031_, _030_, _029_ };
  assign _010_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _038_, _004_ };
  assign _011_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _037_, _035_, _033_, _032_, _031_, _030_, _029_ };
  assign _013_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _039_, _004_ };
  assign _014_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _037_, _035_, _034_, _032_, _031_, _030_, _029_ };
  assign _016_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _040_, _004_ };
  assign _017_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _037_, _035_, _034_, _033_, _031_, _030_, _029_ };
  assign _019_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _041_, _004_ };
  assign _020_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _037_, _035_, _034_, _033_, _032_, _030_, _029_ };
  assign _022_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _042_, _004_ };
  assign _023_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _037_, _035_, _034_, _033_, _032_, _031_, _029_ };
  assign _025_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _043_, _004_ };
  assign _026_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _037_, _035_, _034_, _033_, _032_, _031_, _030_ };
  assign _028_ = | (* src = "SerialParalelo_estruct.v:15.2-36.5" *) { _044_, _004_ };
  assign _006_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _005_;
  assign _036_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _006_;
  assign _009_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _008_;
  assign _038_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _009_;
  assign _012_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _011_;
  assign _039_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _012_;
  assign _015_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _014_;
  assign _040_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _015_;
  assign _018_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _017_;
  assign _041_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _018_;
  assign _021_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _020_;
  assign _042_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _021_;
  assign _024_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _023_;
  assign _043_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _024_;
  assign _027_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _026_;
  assign _044_ = _046_ & (* src = "SerialParalelo_estruct.v:15.2-36.5" *) _027_;
  (* src = "SerialParalelo_estruct.v:81.1-85.4" *)
  always @*
    if (active_estruct) data_out_estruct = data2send_estruct;
  (* src = "SerialParalelo_estruct.v:69.1-75.4" *)
  always @*
    if (_003_) valid_aux = 1'h1;
  (* src = "SerialParalelo_estruct.v:15.2-36.5" *)
  always @*
    if (!_007_) temp0 = data_in;
  (* src = "SerialParalelo_estruct.v:15.2-36.5" *)
  always @*
    if (!_010_) temp1 = data_in;
  (* src = "SerialParalelo_estruct.v:15.2-36.5" *)
  always @*
    if (!_013_) temp2 = data_in;
  (* src = "SerialParalelo_estruct.v:15.2-36.5" *)
  always @*
    if (!_016_) temp3 = data_in;
  (* src = "SerialParalelo_estruct.v:15.2-36.5" *)
  always @*
    if (!_019_) temp4 = data_in;
  (* src = "SerialParalelo_estruct.v:15.2-36.5" *)
  always @*
    if (!_022_) temp5 = data_in;
  (* src = "SerialParalelo_estruct.v:15.2-36.5" *)
  always @*
    if (!_025_) temp6 = data_in;
  (* src = "SerialParalelo_estruct.v:15.2-36.5" *)
  always @*
    if (!_028_) temp7 = data_in;
  assign _045_ = data2send_estruct == (* src = "SerialParalelo_estruct.v:58.8-58.24" *) 8'hbc;
  assign _003_ = cont_aux == (* src = "SerialParalelo_estruct.v:71.8-71.21" *) 3'h4;
  assign _046_ = selector != (* src = "SerialParalelo_estruct.v:16.8-16.32" *) selectorprev;
  (* src = "SerialParalelo_estruct.v:77.1-79.4" *)
  always @(posedge clk_4f)
    valid_out_estruct <= valid_aux;
  (* src = "SerialParalelo_estruct.v:45.1-54.8" *)
  always @(posedge clk_4f)
    data2send_estruct <= { temp0, temp1, temp2, temp3, temp4, temp5, temp6, temp7 };
  (* src = "SerialParalelo_estruct.v:41.1-43.4" *)
  always @(negedge clk_32f)
    selectorprev <= selector;
  (* src = "SerialParalelo_estruct.v:38.1-40.4" *)
  always @(posedge clk_32f)
    selector <= _000_;
  assign _029_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo_estruct.v:17.5-34.12" *) 3'h7;
  assign _030_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo_estruct.v:17.5-34.12" *) 3'h6;
  assign _031_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo_estruct.v:17.5-34.12" *) 3'h5;
  assign _032_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo_estruct.v:17.5-34.12" *) 3'h4;
  assign _033_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo_estruct.v:17.5-34.12" *) 3'h3;
  assign _034_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo_estruct.v:17.5-34.12" *) 3'h2;
  assign _035_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo_estruct.v:17.5-34.12" *) 3'h1;
  assign _037_ = ! (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo_estruct.v:17.5-34.12" *) selector;
  assign active_estruct = _003_ ? (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:71.8-71.21|SerialParalelo_estruct.v:71.5-74.8" *) 1'h1 : 1'h0;
  assign _001_[2:0] = _000_;
  assign BC_counter = { 1'h0, cont_aux };
  assign active_estruct_aux = 1'h0;
endmodule
