/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "SerialParalelo_estruct.v:1.1-85.10" *)
module SerialParalelo_estruct(clk_4f, clk_32f, data_in, data2send_estruct, data_out_estruct, active_estruct, valid_out_estruct);
  (* src = "SerialParalelo_estruct.v:38.1-40.4" *)
  wire [2:0] _00_;
  (* src = "SerialParalelo_estruct.v:39.15-39.25" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _01_;
  (* src = "SerialParalelo_estruct.v:56.20-56.32" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "SerialParalelo_estruct.v:55.8-55.24" *)
  wire _20_;
  (* src = "SerialParalelo_estruct.v:5.15-5.25" *)
  wire [3:0] BC_counter;
  (* src = "SerialParalelo_estruct.v:4.16-4.22" *)
  output active_estruct;
  (* src = "SerialParalelo_estruct.v:10.9-10.19" *)
  wire active_estruct_aux;
  (* src = "SerialParalelo_estruct.v:2.19-2.26" *)
  input clk_32f;
  (* src = "SerialParalelo_estruct.v:2.11-2.17" *)
  input clk_4f;
  (* src = "SerialParalelo_estruct.v:8.15-8.23" *)
  reg [2:0] cont_aux = 3'h0;
  (* src = "SerialParalelo_estruct.v:3.22-3.31" *)
  output [7:0] data2send_estruct;
  reg [7:0] data2send_estruct;
  (* src = "SerialParalelo_estruct.v:2.28-2.35" *)
  input data_in;
  (* src = "SerialParalelo_estruct.v:3.33-3.41" *)
  output [7:0] data_out_estruct;
  reg [7:0] data_out_estruct;
  (* src = "SerialParalelo_estruct.v:7.15-7.23" *)
  reg [2:0] selector = 3'h3;
  (* src = "SerialParalelo_estruct.v:6.9-6.14" *)
  reg temp0;
  (* src = "SerialParalelo_estruct.v:6.15-6.20" *)
  reg temp1;
  (* src = "SerialParalelo_estruct.v:6.21-6.26" *)
  reg temp2;
  (* src = "SerialParalelo_estruct.v:6.27-6.32" *)
  reg temp3;
  (* src = "SerialParalelo_estruct.v:6.33-6.38" *)
  reg temp4;
  (* src = "SerialParalelo_estruct.v:6.39-6.44" *)
  reg temp5;
  (* src = "SerialParalelo_estruct.v:6.45-6.50" *)
  reg temp6;
  (* src = "SerialParalelo_estruct.v:6.51-6.56" *)
  reg temp7;
  (* src = "SerialParalelo_estruct.v:9.9-9.18" *)
  reg valid_aux = 1'h0;
  (* src = "SerialParalelo_estruct.v:4.24-4.33" *)
  output valid_out_estruct;
  reg valid_out_estruct;
  assign { _01_[31:3], _00_ } = selector + (* src = "SerialParalelo_estruct.v:39.15-39.25" *) 32'd1;
  assign _02_ = cont_aux + (* src = "SerialParalelo_estruct.v:56.20-56.32" *) 32'd1;
  (* src = "SerialParalelo_estruct.v:53.1-60.4" *)
  always @(posedge clk_4f)
    if (_20_) cont_aux <= _02_[2:0];
  assign _04_ = | (* src = "SerialParalelo_estruct.v:14.2-36.5" *) { _18_, _17_, _16_, _15_, _14_, _13_, _12_ };
  assign _05_ = | (* src = "SerialParalelo_estruct.v:14.2-36.5" *) { _19_, _18_, _17_, _16_, _15_, _14_, _13_ };
  assign _06_ = | (* src = "SerialParalelo_estruct.v:14.2-36.5" *) { _19_, _18_, _17_, _16_, _15_, _14_, _12_ };
  assign _07_ = | (* src = "SerialParalelo_estruct.v:14.2-36.5" *) { _19_, _18_, _17_, _16_, _15_, _13_, _12_ };
  assign _08_ = | (* src = "SerialParalelo_estruct.v:14.2-36.5" *) { _19_, _18_, _17_, _16_, _14_, _13_, _12_ };
  assign _09_ = | (* src = "SerialParalelo_estruct.v:14.2-36.5" *) { _19_, _18_, _17_, _15_, _14_, _13_, _12_ };
  assign _10_ = | (* src = "SerialParalelo_estruct.v:14.2-36.5" *) { _19_, _18_, _16_, _15_, _14_, _13_, _12_ };
  assign _11_ = | (* src = "SerialParalelo_estruct.v:14.2-36.5" *) { _19_, _17_, _16_, _15_, _14_, _13_, _12_ };
  (* src = "SerialParalelo_estruct.v:78.1-82.4" *)
  always @*
    if (active_estruct) data_out_estruct = data2send_estruct;
  (* src = "SerialParalelo_estruct.v:66.1-72.4" *)
  always @*
    if (_03_) valid_aux = 1'h1;
  (* src = "SerialParalelo_estruct.v:14.2-36.5" *)
  always @*
    if (!_04_) temp0 = data_in;
  (* src = "SerialParalelo_estruct.v:14.2-36.5" *)
  always @*
    if (!_05_) temp1 = data_in;
  (* src = "SerialParalelo_estruct.v:14.2-36.5" *)
  always @*
    if (!_06_) temp2 = data_in;
  (* src = "SerialParalelo_estruct.v:14.2-36.5" *)
  always @*
    if (!_07_) temp3 = data_in;
  (* src = "SerialParalelo_estruct.v:14.2-36.5" *)
  always @*
    if (!_08_) temp4 = data_in;
  (* src = "SerialParalelo_estruct.v:14.2-36.5" *)
  always @*
    if (!_09_) temp5 = data_in;
  (* src = "SerialParalelo_estruct.v:14.2-36.5" *)
  always @*
    if (!_10_) temp6 = data_in;
  (* src = "SerialParalelo_estruct.v:14.2-36.5" *)
  always @*
    if (!_11_) temp7 = data_in;
  assign _20_ = data2send_estruct == (* src = "SerialParalelo_estruct.v:55.8-55.24" *) 8'hbc;
  assign _03_ = cont_aux == (* src = "SerialParalelo_estruct.v:68.8-68.21" *) 3'h4;
  (* src = "SerialParalelo_estruct.v:74.1-76.4" *)
  always @(posedge clk_4f)
    valid_out_estruct <= valid_aux;
  (* src = "SerialParalelo_estruct.v:42.1-51.8" *)
  always @(posedge clk_4f)
    data2send_estruct <= { temp7, temp6, temp5, temp4, temp3, temp2, temp1, temp0 };
  (* src = "SerialParalelo_estruct.v:38.1-40.4" *)
  always @(posedge clk_32f)
    selector <= _00_;
  assign _17_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo.v:16.5-34.12" *) 3'h1;
  assign _18_ = ! (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo.v:16.5-34.12" *) selector;
  assign active_estruct = _03_ ? (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:68.8-68.21|SerialParalelo.v:68.5-71.8" *) 1'h1 : 1'h0;
  assign _19_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo.v:16.5-34.12" *) 3'h7;
  assign _12_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo.v:16.5-34.12" *) 3'h6;
  assign _13_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo.v:16.5-34.12" *) 3'h5;
  assign _14_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo.v:16.5-34.12" *) 3'h4;
  assign _15_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo.v:16.5-34.12" *) 3'h3;
  assign _16_ = selector == (* full_case = 32'd1 *) (* src = "SerialParalelo_estruct.v:0.0-0.0|SerialParalelo.v:16.5-34.12" *) 3'h2;
  assign _01_[2:0] = _00_;
  assign BC_counter = { 1'h0, cont_aux };
  assign active_estruct_aux = 1'h0;
endmodule
