/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "ParaleloSerial_estruct.v:1.1-63.10" *)
module ParaleloSerial_estruct(data_in, clk4_f, clk32_f, valid_in, data_out_estruct);
  (* src = "ParaleloSerial_estruct.v:11.5-19.8" *)
  wire [7:0] _000_;
  (* src = "ParaleloSerial_estruct.v:27.5-60.8" *)
  wire _001_;
  (* src = "ParaleloSerial_estruct.v:11.5-19.8" *)
  wire [2:0] _002_;
  (* src = "ParaleloSerial_estruct.v:27.5-60.8" *)
  wire _003_;
  (* src = "ParaleloSerial_estruct.v:21.5-25.8" *)
  wire [2:0] _004_;
  (* src = "ParaleloSerial_estruct.v:27.5-60.8" *)
  wire _005_;
  (* src = "ParaleloSerial_estruct.v:8.15-8.25" *)
  wire [2:0] _006_;
  (* src = "ParaleloSerial_estruct.v:27.5-60.8" *)
  wire _007_;
  (* src = "ParaleloSerial_estruct.v:27.5-60.8" *)
  wire _008_;
  (* src = "ParaleloSerial_estruct.v:27.5-60.8" *)
  wire _009_;
  (* src = "ParaleloSerial_estruct.v:27.5-60.8" *)
  wire _010_;
  (* src = "ParaleloSerial_estruct.v:27.5-60.8" *)
  wire _011_;
  (* src = "ParaleloSerial_estruct.v:27.5-60.8" *)
  wire _012_;
  (* src = "ParaleloSerial_estruct.v:23.23-23.37" *)
  wire [31:0] _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  (* src = "ParaleloSerial_estruct.v:12.12-12.25" *)
  wire _047_;
  (* src = "ParaleloSerial_estruct.v:28.8-28.21" *)
  wire _048_;
  (* src = "ParaleloSerial_estruct.v:32.8-32.21" *)
  wire _049_;
  (* src = "ParaleloSerial_estruct.v:36.8-36.21" *)
  wire _050_;
  (* src = "ParaleloSerial_estruct.v:40.8-40.21" *)
  wire _051_;
  (* src = "ParaleloSerial_estruct.v:44.8-44.21" *)
  wire _052_;
  (* src = "ParaleloSerial_estruct.v:48.8-48.21" *)
  wire _053_;
  (* src = "ParaleloSerial_estruct.v:52.8-52.21" *)
  wire _054_;
  (* src = "ParaleloSerial_estruct.v:56.8-56.21" *)
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire [7:0] _072_;
  wire _073_;
  wire [2:0] _074_;
  wire _075_;
  (* src = "ParaleloSerial_estruct.v:3.19-3.26" *)
  input clk32_f;
  (* src = "ParaleloSerial_estruct.v:3.11-3.17" *)
  input clk4_f;
  (* src = "ParaleloSerial_estruct.v:7.15-7.24" *)
  reg [7:0] data2send;
  (* src = "ParaleloSerial_estruct.v:2.17-2.24" *)
  input [7:0] data_in;
  (* src = "ParaleloSerial_estruct.v:4.16-4.24" *)
  output data_out_estruct;
  reg data_out_estruct;
  (* src = "ParaleloSerial_estruct.v:8.15-8.23" *)
  reg [2:0] selector = 3'h0;
  (* src = "ParaleloSerial_estruct.v:3.28-3.36" *)
  input valid_in;
  assign _013_ = { 29'h00000000, selector } + (* src = "ParaleloSerial_estruct.v:23.23-23.37" *) 32'd1;
  assign _015_ = ~ (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _055_;
  assign _016_ = ~ (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _054_;
  assign _017_ = ~ (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _053_;
  assign _018_ = ~ (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _052_;
  assign _019_ = ~ (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _051_;
  assign _020_ = ~ (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _050_;
  assign _021_ = ~ (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _049_;
  assign _022_ = ~ (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _048_;
  assign _023_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _039_;
  assign _024_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _023_;
  assign _025_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _040_;
  assign _026_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) 1'h1;
  assign _027_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _041_;
  assign _028_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _027_;
  assign _029_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _042_;
  assign _030_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _029_;
  assign _031_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _043_;
  assign _032_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _031_;
  assign _033_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _044_;
  assign _034_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _033_;
  assign _035_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _045_;
  assign _036_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _035_;
  assign _037_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _046_;
  assign _038_ = | (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _037_;
  assign _040_ = _015_ & (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _024_;
  assign _041_ = _022_ & (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _026_;
  assign _042_ = _021_ & (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _028_;
  assign _043_ = _020_ & (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _030_;
  assign _044_ = _019_ & (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _032_;
  assign _045_ = _018_ & (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _034_;
  assign _046_ = _017_ & (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _036_;
  assign _039_ = _016_ & (* src = "ParaleloSerial_estruct.v:27.5-60.8" *) _038_;
  assign _014_ = ~ _025_;
  (* src = "ParaleloSerial_estruct.v:27.5-60.8" *)
  always @*
    if (_014_) data_out_estruct = _056_;
  assign _047_ = valid_in == (* src = "ParaleloSerial_estruct.v:12.12-12.25" *) 32'd0;
  assign _048_ = selector == (* src = "ParaleloSerial_estruct.v:28.8-28.21" *) 32'd0;
  assign _049_ = selector == (* src = "ParaleloSerial_estruct.v:32.8-32.21" *) 32'd1;
  assign _050_ = selector == (* src = "ParaleloSerial_estruct.v:36.8-36.21" *) 32'd2;
  assign _051_ = selector == (* src = "ParaleloSerial_estruct.v:40.8-40.21" *) 32'd3;
  assign _052_ = selector == (* src = "ParaleloSerial_estruct.v:44.8-44.21" *) 32'd4;
  assign _053_ = selector == (* src = "ParaleloSerial_estruct.v:48.8-48.21" *) 32'd5;
  assign _054_ = selector == (* src = "ParaleloSerial_estruct.v:52.8-52.21" *) 32'd6;
  assign _055_ = selector == (* src = "ParaleloSerial_estruct.v:56.8-56.21" *) 32'd7;
  (* src = "ParaleloSerial_estruct.v:21.5-25.8" *)
  always @(posedge clk32_f)
    selector <= _013_[2:0];
  (* src = "ParaleloSerial_estruct.v:11.5-19.8" *)
  always @(posedge clk4_f)
    data2send <= _072_;
  (* src = "ParaleloSerial_estruct.v:11.5-19.8" *)
  always @(posedge clk4_f)
    selector <= _074_;
  assign _056_ = _057_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_estruct.v:56.8-56.21|ParaleloSerial.v:56.5-58.8" *) data2send[0] : _011_;
  assign _058_ = _059_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_estruct.v:52.8-52.21|ParaleloSerial.v:52.5-54.8" *) data2send[1] : _010_;
  assign _060_ = _061_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_estruct.v:48.8-48.21|ParaleloSerial.v:48.5-50.8" *) data2send[2] : _009_;
  assign _062_ = _063_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_estruct.v:44.8-44.21|ParaleloSerial.v:44.5-46.8" *) data2send[3] : _008_;
  assign _064_ = _065_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_estruct.v:40.8-40.21|ParaleloSerial.v:40.5-42.8" *) data2send[4] : _007_;
  assign _066_ = _067_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_estruct.v:36.8-36.21|ParaleloSerial.v:36.5-38.8" *) data2send[5] : _005_;
  assign _068_ = _069_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_estruct.v:32.8-32.21|ParaleloSerial.v:32.5-34.8" *) data2send[6] : _003_;
  assign _070_ = _071_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_estruct.v:28.8-28.21|ParaleloSerial.v:28.5-30.8" *) data2send[7] : data2send[7];
  assign _072_ = _073_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_estruct.v:12.12-12.25|ParaleloSerial.v:12.9-18.12" *) 8'hbc : data_in;
  assign _074_ = _075_ ? (* full_case = 32'd1 *) (* src = "ParaleloSerial_estruct.v:12.12-12.25|ParaleloSerial.v:12.9-18.12" *) 3'h0 : selector;
  assign _006_ = 3'h0;
  assign _001_ = _012_;
  assign _004_ = _013_[2:0];
  assign _057_ = _055_;
  assign _012_ = _056_;
  assign _059_ = _054_;
  assign _011_ = _058_;
  assign _061_ = _053_;
  assign _010_ = _060_;
  assign _063_ = _052_;
  assign _009_ = _062_;
  assign _065_ = _051_;
  assign _008_ = _064_;
  assign _067_ = _050_;
  assign _007_ = _066_;
  assign _069_ = _049_;
  assign _005_ = _068_;
  assign _071_ = _048_;
  assign _003_ = _070_;
  assign _073_ = _047_;
  assign _000_ = _072_;
  assign _075_ = _047_;
  assign _002_ = _074_;
endmodule
